### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Gaut9a8m** [reactchartjs/react-chartjs-2#1004]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Polar chart must work fine.

### Reproduction

frequent

### chart.js version

v4.0.0

### react-chartjs-2 version

v4.0.0

**Comment by dangreen** [comment]
@Gaut9a8m Hi. Please provide clear issue description and reproduction.

**Comment by dangreen** [comment]
@Gaut9a8m Hi. Issue is still relevant for you?

**Comment by dangreen** [comment]
Closed due to inactivity
