### ISSUE TITLE
[Bug]: Type definition for ChartOptions

### ISSUE THREAD

**Issue by JBaczuk** [reactchartjs/react-chartjs-2#1009]
### Current and expected behavior

I posted this issue in [chart.js repo](https://github.com/chartjs/Chart.js/issues/9085#issuecomment-1020631573), but I think it is related to this lib and its type definitions.

With these options,

```
const options = {
    scales: {
      y: {
        min: 0,
      },
      x: {
        type: 'time', // << ts error
      ...
```
I got this error:

Type 'string' is not assignable to type '"timeseries" | undefined'.

So, I added as any (not ideal):

type: 'time' as any,

If there is a more correct way, I'd love to know.

Here's my reproduction:

https://github.com/JBaczuk/chartjs-9085-repro

![image](https://user-images.githubusercontent.com/8162417/151010016-157cd2a1-7ce0-4e2b-9b1b-12af6797c529.png)

### Reproduction

https://github.com/JBaczuk/chartjs-9085-repro

### chart.js version

v3.7.0

### react-chartjs-2 version

v4.0.0

### Possible solution

unsure

**Comment by dangreen** [comment]
@JBaczuk Hi.

1) You should use `as const` syntax: `type: 'timeseries' as const`
2) If you expect `'time'` type, then you should ask about that in Chart.js repo, because react-chartjs-2 reuse types from Chart.js

**Comment by JBaczuk** [comment]
> 

using `'timeseries' as const` throws this error:

![image](https://user-images.githubusercontent.com/8162417/151033638-c31c71de-fb76-44ec-9cd1-5099a979badd.png)

**Comment by dangreen** [comment]
@JBaczuk Did you try `type: 'time' as const` ?

**Comment by JBaczuk** [comment]
> @JBaczuk Did you try `type: 'time' as const` ?

Yeah:

```
Types of property 'type' are incompatible.
              Type '"time"' is not assignable to type '"timeseries" | undefined'.ts(2322)
```

**Comment by dangreen** [comment]
@JBaczuk Ok. Will see it soon.

**Comment by nthakar87** [comment]
Hi Guys,

chart.js version
v3.7.0

react-chartjs-2 version
v4.0.0

We are running into similar error:
Type error: Type '{ maintainAspectRatio: boolean; plugins: { title: { display: boolean; text: string; color: string; font: { size: number; weight: string; }; padding: number; }; legend: { display: boolean; align: "end"; labels: { ...; }; }; tooltip: { ...; }; }; scales: { ...; }; }' is not assignable to type '_DeepPartialObject<CoreChartOptions<"bar"> & ElementChartOptions<"bar"> & PluginChartOptions<"bar"> & DatasetChartOptions<"bar"> & ScaleChartOptions<...> & BarControllerChartOptions>'.
  Types of property 'scales' are incompatible.
    Type '{ y: { type: string; min: number; max: number; title: { display: boolean; text: string; font: { size: number; lineHeight: number; }; }; grid: { display: boolean; }; ticks: { display: boolean; }; color: string; }; x: { ...; }; }' is not assignable to type '_DeepPartialObject<{ [key: string]: ScaleOptionsByType<keyof CartesianScaleTypeRegistry>; }>'.
      Property 'y' is incompatible with index signature.
        Type '{ type: string; min: number; max: number; title: { display: boolean; text: string; font: { size: number; lineHeight: number; }; }; grid: { display: boolean; }; ticks: { display: boolean; }; color: string; }' is not assignable to type '_DeepPartialObject<{ type: "logarithmic"; } & CartesianScaleOptions & { suggestedMin?: number; suggestedMax?: number; ticks: { format: NumberFormatOptions; }; }> | _DeepPartialObject<...> | _DeepPartialObject<...> | _DeepPartialObject<...> | _DeepPartialObject<...>'.
          Type '{ type: string; min: number; max: number; title: { display: boolean; text: string; font: { size: number; lineHeight: number; }; }; grid: { display: boolean; }; ticks: { display: boolean; }; color: string; }' is not assignable to type '_DeepPartialObject<{ type: "timeseries"; } & CartesianScaleOptions & { min: string | number; max: string | number; suggestedMin: string | number; suggestedMax: string | number; bounds: "data" | "ticks"; adapters: { ...; }; time: { ...; }; ticks: { ...; }; }>'.
            Types of property 'type' are incompatible.
              Type 'string' is not assignable to type '"timeseries"'.

  177 |                 <div>
  178 |                         {/*eslint-disable-next-line*/}
> 179 |                         <Bar data={data} options={options} height={300}/>
      |                                                          ^
  180 |                 </div>
  181 |         );
  182 | };
error Command failed with exit code 1.

Please let us know if you find anything.
- Nirav

**Comment by dangreen** [comment]
@JBaczuk I tried it, all works without issues https://codesandbox.io/s/nifty-water-03zp6?file=/App.tsx

**Comment by dangreen** [comment]
@JBaczuk Did you test it?

**Comment by JBaczuk** [comment]
@dangreen Sorry just saw this. Yes, once I added `as const` to the following lines, as you did, the errors are gone.

```
minUnit: 'minute' as const,
```
and
```
source: 'data' as const,
```

The confusing part is this error gave no indication that those other 2 lines needed additional type casting:

```
Types of property 'type' are incompatible.
              Type '"time"' is not assignable to type '"timeseries" | undefined'.ts(2322)
```

**Comment by dangreen** [comment]
@JBaczuk More stable variant is define type of options explictly:

```ts
import {
  ChartOptions
} from "chart.js";

const options: ChartOptions<"line"> = { /* ... */ };
```
