### ISSUE TITLE
Missing Legend property on Chart ref object in type definition

### ISSUE THREAD

**Issue by EBruchet** [reactchartjs/react-chartjs-2#1012]
### Would you like to work on this feature?

- [x] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

Noticed that the `legend` property is missing from the type definition of the `ref.current` object that's attached to the `Chart` instance.

Console.log of the `ref.current` property:
<img width="1059" alt="Screenshot 2022-02-02 at 18 45 16" src="https://user-images.githubusercontent.com/20384291/152219552-259a4795-b269-41d6-a815-00f5efec9244.png">

### Describe the solution you'd like

I'd like to add this myself, but not sure how to contribute to the project

Hopefully it's just a matter of adding `legend: LegendElement<ChartType>` to the list of `readonly` properties in the class definition of `Chart` (here if I'm not being clear: https://github.com/chartjs/Chart.js/blob/56661e448d8478e7cbce0f30d70d0bf1d2a2da8c/types/index.esm.d.ts#L483)

Again more than happy to create a PR myself but a bit confused on how to 😅

Thanks for any help/info you can give me!

**Comment by dangreen** [comment]
@EBruchet Hi. Yes, you should make PR into chartjs repo.

**Comment by EBruchet** [comment]
Ah sorry about that - realised immediately after that I'd [created the issue in the wrong repo ](https://github.com/chartjs/Chart.js/issues/10121).

Thanks!
