### ISSUE TITLE
[Bug]: Uncaught Error: "radialLinear" is not a registered scale.

### ISSUE THREAD

**Issue by zeckstone** [reactchartjs/react-chartjs-2#1014]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

The library is to plot a polar area chart but throws an error

### Reproduction

https://codesandbox.io/s/peaceful-meninsky-6nn65?file=/App.tsx

### chart.js version

3.7.0

### react-chartjs-2 version

4.0.1

**Comment by dangreen** [comment]
@zeckstone Hi. You should register `RedialLinerScale` component. https://react-chartjs-2.js.org/docs/migration-to-v4#tree-shaking
