### ISSUE TITLE
Fill is not working in line chart of multichart [Bug]: 

### ISSUE THREAD

**Issue by Ajju2211** [reactchartjs/react-chartjs-2#1016]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### In the multi chart line chart is not able to fill the background.
_Here is the screenshot_
![image](https://user-images.githubusercontent.com/43109538/153712837-e7b198fb-6138-4bcb-a99a-c80ae96b93e9.png)

### Reproduction

https://codesandbox.io/s/bold-alex-9xd6o?file=/App.tsx

### chart.js version

v3.7.0

### react-chartjs-2 version

v4.0.1

**Comment by dangreen** [comment]
https://react-chartjs-2.js.org/faq/fill-property
