### ISSUE TITLE
Implement `updateMode` property

### ISSUE THREAD

**Issue by dangreen** [reactchartjs/react-chartjs-2#1024]
### What problem are you trying to solve?

Chart.js' `update()` method can accept update mode as argument.

```ts
(method) Chart<TType, TData, TLabel>.update(mode?: "resize" | "reset" | "none" | "hide" | "show" | "normal" | "active" | undefined): void
```

Currently, react-chartjs-2 doesn't support passing update mode to Chart.js.

### Describe the solution you'd like

Need to implement the `updateMode` property to pass it to every `chartRef.current.update()` call.

Source: https://github.com/reactchartjs/react-chartjs-2/issues/1006

**Comment by Arantiryo** [comment]
Implemented in `4.2.0`.

#1006
