### ISSUE TITLE
React Chart.js v3 : highlight series when mouse on legend

### ISSUE THREAD

**Issue by theotzen** [reactchartjs/react-chartjs-2#1028]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I am using react and chart.js.

I have a Line chart, and I would love to have a highlight on one of the series when the mouse is hovering the according legend.

I found some help but it looks like the code is only working for previous version of chart.js.

### Reproduction

<Line      data={data}      options={{maintainAspectRatio: false,                responsive: true,            interaction: {                         mode: "index",                         intersect: true,                     },                                                                   plugins: {                             tooltips: {                                 mode: "nearest",                                 intersect: false,                                 },                                 hover:                                  {                                     mode: "nearest",                                     intersect: true,                                 },                                                                                                                                       datalabels: {                                     display: false,                                     color: "black",                                 },                                 title: {                                         display: true,                                     text: "Limit"                                         },                                 legend: {                                     onHover: function(event, legendItem, legend) {                                         console.log('allo')                                         var me = this;                                         var options = me.options || {};                                         var hoverOptions = options.hover || {mode: 'nearest'};                                         var index = legendItem.datasetIndex;                                         var ci = legend.chart;                                                                                   for (var i=0; i < ci.$datalabels._datasets.length-1; i++) {                                         var elements = ci.getDatasetMeta(i).data;                                           ci.updateHoverStyle(elements, hoverOptions.mode, false) ; // <<<--- turn off higlight                                             }                                         var elements = ci.getDatasetMeta(index).data;                                             ci.updateHoverStyle(elements, hoverOptions.mode, true) // <<-- Turn on                                                                                   ci.render();                                           },                                     display: true,                                     position: "right",                                                                           }                             },                         }}                                           />

### chart.js version

v3.7.1

### react-chartjs-2 version

^4.0.1

**Comment by dangreen** [comment]
@theotzen Hi. react-chartjs-2 is just the wrapper around Chart.js, so if you are experiencing an issue with charts rendering, please create a related issue in [Chart.js repository](https://github.com/chartjs/Chart.js/issues).
