### ISSUE TITLE
[Bug]: Fill for Line graph not working

### ISSUE THREAD

**Issue by AdamVerner** [reactchartjs/react-chartjs-2#1029]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

`fill: true` (and `backgroundColor`) should add background to the area below line. This is working, when i use Chart.js directly, but not when i use the bindings to pass the datasets. Doesn't work in the examples either.

![image](https://user-images.githubusercontent.com/34060105/157484604-f89d6aac-82f3-4f7d-98b3-fce024ff13aa.png)

### Reproduction

https://codesandbox.io/s/busy-flower-6g0xyz?file=/App.tsx

### chart.js version

3.7.1

### react-chartjs-2 version

4.0.1

**Comment by dangreen** [comment]
https://react-chartjs-2.js.org/faq/fill-property

**Comment by AdamVerner** [comment]
Sorry, i somehow completely missed that, Thanks.

Anyway, wouldn't it be good idea to use the `Filler` in the example if the `backgroundColor` property is set as well? That's probably what confused me.
