### ISSUE TITLE
[Bug]: Canot install chartjs in new version of react 18

### ISSUE THREAD

**Issue by Zaid-maker** [reactchartjs/react-chartjs-2#1033]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I am building my web3 project and i need chart js and chartjs-2 for chart and line things in my project but it gives this error:
![image](https://user-images.githubusercontent.com/53424436/161599208-d5a29b49-d489-48e7-9a9c-79671e0bb524.png)

Please fix this issue i need to complete my project ASAP.

### Reproduction

https://codesandbox.io/s/amazing-chaplygin-2787ux?file=/package.json

### chart.js version

3.7.1

### react-chartjs-2 version

4.0.1

**Comment by pyaw-io** [comment]
having the same issue

**Comment by DavideDA** [comment]
I prefer using node 16.x

From [https://www.cloudsavvyit.com/10779/whats-new-in-node-js-16/](https://www.cloudsavvyit.com/10779/whats-new-in-node-js-16/):

**Comment by clearasvodka** [comment]
Same here.

**Comment by Zaid-maker** [comment]
I am using node js 16 it's a peer dependency issue.

**Comment by jokari4242** [comment]
Same here.

**Comment by masterbater** [comment]
A lot of libraries haven't updated their peer dependency. Just do "npm i react-chartjs-2 chart.js --force" flag until most of packages update their dependency definition. Just dont use the new createRoot of react 18 until packages fully support react 18

**Comment by DavideDA** [comment]
Build/Deploy process is not in my hands: I cannot modify npm install command line 😢

**Comment by Zaid-maker** [comment]
> A lot of libraries haven't updated their peer dependency. Just do "npm i react-chartjs-2 chart.js --force" flag until most of packages update their dependency definition. Just dont use the new createRoot of react 18 until packages fully support react 18

Alright i am trying that.

**Comment by dangreen** [comment]
Hi guys! Please try react-chartjs-2@4.1.0

**Comment by Zaid-maker** [comment]
What? Did they release new version?

**Comment by Zaid-maker** [comment]
Thank you so much for the support :)

**Comment by DavideDA** [comment]
Many thanks!
