### ISSUE TITLE
tryint to draw a triangle using afterDraw() does not render anything on the chart

### ISSUE THREAD

**Issue by regola-Tacens** [reactchartjs/react-chartjs-2#1038]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

i am trying to draw a triangle on top of what is already beeing drawn on my chart

### Reproduction

https://github.com/regola-Tacens/binance-chart/blob/main/binanceChart.js

### chart.js version

3.7.1

### react-chartjs-2 version

4.0.1

### Possible solution

I am trying to utilize the plugins object in options, to render a triangle using afterDraw like so 👍 

```
const options = {
plugins: {
      triangle:{
        afterDraw(chartComponent, args, options){
          const  { ctx } = chartComponent.current

          ctx.save()
          ctx.beginPath()
          ctx.moveTo(0,0)
          ctx.lineTo(20,200)
          ctx.lineTo(20,100)
          ctx.lineTp(0,0)
          ctx.fillStyle='#BCBCBC'
          ctx.fill()
        }
      },
...
}
```

with chartComponent beeing my chart referenced with the useRef hook : 

```
  return (
    <div className="bg-blue-intense rounded-md mt-6 shadow-2xl py-4 px-4 h-110">
      <Chart
        type="line"
        ref={chartComponent}
        options={options}
        data={chartData}
      />
      ;
    </div>
  );
```

nothing ever happens on screen, i can never get afterDraw() to work in this context, what am i doing wrong ?

thank you !!

**Comment by regola-Tacens** [comment]
I have just found out how to do it : 

```
  var chartpluginsset = [
    {
        afterDatasetDraw: (chart) => {
          const  { ctx } = chart

          ctx.save()
          ctx.beginPath()
          ctx.moveTo(200,200)
          ctx.lineTo(200,100)
          ctx.lineTo(20,100)
          ctx.fillStyle='#E24545'
          ctx.fill()
        }
    }
  ];
```

and then in my chart.js React component : 

```
  return (
    <div className="bg-blue-intense rounded-md mt-6 shadow-2xl py-4 px-4 h-110">
      <Chart
        type="line"
        ref={chartComponent}
        options={options}
        data={chartData}
        plugins={chartpluginsset}
      />
      ;
    </div>
  );
```

**Comment by drewthi** [comment]
I have tried to do this same thing, but I am also not getting anything to render. Console logs from within the afterDraw functions don't print to console. I'm not sure what is wrong.

```
const chartpluginsset = [
  {
      afterDatasetDraw: (chart) => {
        const  { ctx } = chart
        console.log(ctx);
        ctx.save()
        ctx.beginPath()
        ctx.moveTo(200,200)
        ctx.lineTo(200,100)
        ctx.lineTo(20,100)
        ctx.fillStyle='#E24545'
        ctx.fill()
      }
  }
];
```

```
export const options = {  
  plugins: {
    chartpluginsset,
    legend: {
      display: false
    },
  }
};
```

```
render() {

    return (
      <div className='chart-container'>
        <div style={{height: '100%', width: '100%'}}>
          <Line 
            ref={myChartRef}
            height={"100%"} 
            width={"100%"} 
            options={options} 
            data={data} />
        </div>
    );
}
```
Do you have any insight on what enabled it to work for you?

**Comment by regola-Tacens** [comment]
yes i think it's because you still need to add the plugins property to your <Line/> component.

you still need to write 


 ```
<Line 
  ref={myChartRef}
 height={"100%"} 
 width={"100%"} 
options={options} 
plugins={chartpluginsset}
 data={data} />
```

probably because the confusing thing is that the plugin property is part of of the options object that you pass on to your component, but it's also a property of the component itself....and eventually they're not the same ...i might be wrong but try it out, it works for me

**Comment by drewthi** [comment]
It worked! Thank you so much. That's exactly why I was confused... Oh well, it works now and I can't complain haha, I appreciate it.
