### ISSUE TITLE
[Bug]: Error: While trying to resolve module react-chartjs-2 this package itself specifies a main module field that could not be resolved (...\node_modules\react-chartjs-2\dist\index.cjs)

### ISSUE THREAD

**Issue by lelsteph** [reactchartjs/react-chartjs-2#1040]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Hello

Under a React Native Node js project
    "react": "17.0.2",
    "react-native": "0.66.4"

I executed installed instructions from `https://react-chartjs-2.js.org/#getting-help`
Trying to use example https://react-chartjs-2.js.org/examples/line-chart

I get
Error: While trying to resolve module react-chartjs-2 from file ...\src\screens\measures\measures-screen.tsx, the package ...\node_modules\react-chartjs-2\package.json was successfully found. However, this package itself specifies a main module field that could not be resolved (...\node_modules\react-chartjs-2\dist\index.cjs. Indeed, none of these files exist:
  * ...\node_modules\react-chartjs-2\dist\index.cjs(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * ...\node_modules\react-chartjs-2\dist\index.cjs\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)

 index.cjs is there in the node folder.

I found seaching google some people add
  resolver: {
    sourceExts: ['jsx', 'js', 'ts', 'tsx'],
  },

in the metro.config.js file, which does not help.

### Reproduction

Install as documented from `https://react-chartjs-2.js.org/#getting-help` and use example https://react-chartjs-2.js.org/examples/line-chart

### chart.js version

v4.1.0

### react-chartjs-2 version

v3.7.1

**Comment by Arantiryo** [comment]
@lelsteph Hi! **react-chartjs-2** is not supposed to be used with React Native. 

You can implement your own solution using Chart.js, [this article](https://danielwiese.com/posts/react-native-canvas-charts/) might be a good place to start.

**Comment by lelsteph** [comment]
Thank you I didn't realized it was not supported for react native, sorry!

**Comment by igorlukanin** [comment]
@lelsteph In my opinion, [Victory](https://awesome.cube.dev/tools/victory) is one of the most interesting charting libraries for React Native. Please feel free to check it out and maybe take a look at [this tutorial](https://cube.dev/blog/react-native-charts-with-cubejs-victory).

**Comment by lelsteph** [comment]
Great Thank you!!
