### ISSUE TITLE
Get innerRadius in plugins(v4)

### ISSUE THREAD

**Issue by juanlet** [reactchartjs/react-chartjs-2#1041]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

Getting the innerRadius on plugins

### Describe the solution you'd like

Right now we can get the innerRadius from

```
const plugins = 
  {beforeDraw: function (chart) {
const datasetCount = chart.getVisibleDatasetCount();
const chartMeta = chart.getDatasetMeta(datasetCount-1).data.at(0);
if (chartMeta) {
	const {innerRadius} = chartMeta.getProps(['innerRadius']);
        ...
}

.....
}
```

It would be nice if that would be exposed in the ctx object for the chart types that should have that property

**Comment by Arantiryo** [comment]
Hi @juanlet 👋 

`react-chartjs-2` is just a wrapper for `Chart.js`, so I would kindly suggest you file the issue in [Chart.js repository](https://github.com/chartjs/Chart.js/issues/).

Also judging by [this issue](https://github.com/chartjs/Chart.js/issues/7217) it looks like `innerRadius` used to be part of chart object but then later was moved to the controller object.
