### ISSUE TITLE
[Bug]: canvas rendered with height=0 width=0 

### ISSUE THREAD

**Issue by shileima** [reactchartjs/react-chartjs-2#1045]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

![image](https://user-images.githubusercontent.com/3283706/170005515-3b5ba1d8-fd5c-4624-8474-e76a1e5bc4f6.png)

### Reproduction

vite2

### chart.js version

3.7.1

### react-chartjs-2 version

4.0.0

### Possible solution

use Chromium/50.0.2661.102
but we add legacy
{
        // targets: ["ie >= 11"],
        targets: {
          chrome: 49,
          edge: 13,
          firefox: 50,
        },
        additionalLegacyPolyfills: ["regenerator-runtime/runtime"],
        renderLegacyChunks: true 
      }

**Comment by Arantiryo** [comment]
Hi @shileima 👋 

Thank you for bringing this up! We believe it's not a bug and each developer should decide for themselves if they would want to transpile dependencies or not. [This article](https://dev.to/cubejs/why-and-how-to-transpile-dependencies-of-your-javascript-application-3phf) might be useful to learn more about the topic.

**Comment by seikosantana** [comment]
@Arantiryo sorry but I just encountered the same problem where on some refreshes it has 0 weight and width but if i resize the view it renders correctly. I'm on react with Ionic, is it related to dependencies?
