### ISSUE TITLE
[Bug]: set fixed width doest work

### ISSUE THREAD

**Issue by nemanja3** [reactchartjs/react-chartjs-2#1051]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

when i set a fixed width it should resize to that value. Height is working fine but width is not.
Example of code that i used on your react-chartjs-2 documentation page:
`<Line width={10} height={169} options={options} data={data} />`
i also added maintainAspectRatio: false in options:
```
export const options = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: {
      position: 'top' as const,
    },
    title: {
      display: true,
      text: 'Chart.js Line Chart',
    },
  },
};
```
If i change the height it works fine on the example but not the width

### Reproduction

https://react-chartjs-2.js.org/examples/line-chart/

### chart.js version

v3.6.0

### react-chartjs-2 version

v4.2.0

**Comment by Arantiryo** [comment]
Hi @nemanja3 👋 

This is actually the intended behavior. If you'd like to set a fixed width, you should set `responsive` to `false`.
