### ISSUE TITLE
[Bug]: Cannot set point radius

### ISSUE THREAD

**Issue by shd101wyy** [reactchartjs/react-chartjs-2#1053]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I set the point radius in options:

```javascript
{
    responsive: true,
    maintainAspectRatio: false,
    // Doesn't work somehow
    elements: {
      point: {
        radius: 5,
        hoverRadius: 8,
      },
    },
   ...
```

But it doesn't work. Any suggestions?

### Reproduction

sorry no sandbox

### chart.js version

3.8.0

### react-chartjs-2 version

4.2.0

**Comment by Arantiryo** [comment]
Hi @shd101wyy 👋 

Should be working just fine. Please take a look at [this code sandbox](https://codesandbox.io/s/recursing-kepler-m46g25?file=/App.tsx) to see if there're any differences with your code.

**Comment by shd101wyy** [comment]
Hi @Arantiryo Thank you! I will take a closer look :+1:
