### ISSUE TITLE
[Bug]: time and timeseries type axis does not work

### ISSUE THREAD

**Issue by nemanja3** [reactchartjs/react-chartjs-2#1056]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

in v2 of react-chart js i used in my x axis object `type="time"`. Now i am using v4 and when i want to use a scale of type time i get an error:
![image](https://user-images.githubusercontent.com/26413661/177050767-5395fb50-2dc8-4661-a9d8-afc5fcd2e7d0.png)
i have read your documentation on migration from v2 to v3. and in the v3 example u also use  `type="time"` :
![image](https://user-images.githubusercontent.com/26413661/177050820-50a04f88-b0e3-460a-93da-f5f3432c38c5.png)

is v4 different regarding the time scales or is there maybe a new sintax i am not familiar to ?
Please help,
Thank you

### Reproduction

https://react-chartjs-2.js.org/examples/line-chart/

### chart.js version

v3.6.0

### react-chartjs-2 version

v4.2.0

**Comment by Arantiryo** [comment]
Hi @nemanja3 

You need to register the `time` scale:
```typescript
import { TimeScale } from "chart.js";

ChartJS.register(TimeScale);
```

You can find a list with all available imports [here](https://www.chartjs.org/docs/latest/getting-started/integration.html#bundlers-webpack-rollup-etc).
