### ISSUE TITLE
Multitype Chart Sample doesn't work after building.

### ISSUE THREAD

**Issue by HalJune1026** [reactchartjs/react-chartjs-2#1063]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

This page's sample doesn't work after building due to tree-shaking.
Chart Component needs to register Controller (this sample needs Bar and Line Controller).
https://react-chartjs-2.js.org/examples/multitype-chart

this can't be reproduced in sandbox.

### Reproduction

https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/chart/multitype?from-embed

### chart.js version

3.8.0

### react-chartjs-2 version

4.3.1

### Possible solution

add BarController, LineController to register.

**Comment by Arantiryo** [comment]
Hi @HalJune1026 👋 

Thank you for bringing this up! I was able to reproduce it and indeed importing and registering `BarController` and `LineController` solves the issue.

I'll make a PR to fix it momentarily.
