### ISSUE TITLE
How to use this wrapper with plugins?

### ISSUE THREAD

**Issue by dwjohnston** [reactchartjs/react-chartjs-2#1066]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

For example there is this Chartjs plugin that creates a box and whisker graph: 

https://github.com/sgratzl/chartjs-chart-boxplot

How would I use it with this library? 

### Describe the solution you'd like

Improved documentation, example usage. 

### Describe alternatives you've considered

Use chartjs directly, use alternative libraries.

**Comment by Arantiryo** [comment]
Hi @dwjohnston 👋 

Thank you for bringing this up! With `chartjs-chart-boxplot` you simply import and register the necessary controllers as described [here](https://github.com/sgratzl/chartjs-chart-boxplot#esm-and-tree-shaking). Please take a look at [this code sandbox](https://codesandbox.io/s/thirsty-marco-jonu1b?file=/App.tsx) with a sample.

And I think we will add a code sandbox with a plugin for the [examples page](https://react-chartjs-2.js.org/examples).

**Comment by dwjohnston** [comment]
Thanks so much!
