### ISSUE TITLE
[Bug]: Uncaught Error: "Category" is not a registered scale.

### ISSUE THREAD

**Issue by AbubakarZorrain** [reactchartjs/react-chartjs-2#1069]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I am using Bar in react through this repo.
But the this uncaught error comes out. Category is not a registered scale. Even I am not using category in my code.
I install react-chartjs-2 not chartjs.
I just import Bar and give data to it.

### Reproduction

not working

### chart.js version

not installed

### react-chartjs-2 version

4.3.1

**Comment by Arantiryo** [comment]
Hi @AbubakarZorrain 👋 

This library is a wrapper for `Chart.js` so you need to install both with one of these commands:
```
npm add react-chartjs-2 chart.js
# or
yarn add react-chartjs-2 chart.js
# or
npm i react-chartjs-2 chart.js
```

**Comment by robinelvin** [comment]
I have just got this error after upgrading `react-chartjs-2` and `chart.js`

```
Error: "category" is not a registered scale.
 ❯ Registry._get ../../node_modules/chart.js/src/core/core.registry.js:178:13
 ❯ Registry.getScale ../../node_modules/chart.js/src/core/core.registry.js:90:17
 ❯ call ../../node_modules/chart.js/src/core/core.controller.js:370:37
 ❯ each ../../node_modules/chart.js/src/helpers/helpers.core.ts:149:12
 ❯ Chart.buildOrUpdateScales ../../node_modules/chart.js/src/core/core.controller.js:355:5
 ❯ Chart._updateScales ../../node_modules/chart.js/src/core/core.controller.js:561:10
 ❯ Chart.update ../../node_modules/chart.js/src/core/core.controller.js:495:10
 ❯ new Chart ../../node_modules/chart.js/src/core/core.controller.js:206:12
 ❯ renderChart ../../node_modules/react-chartjs-2/src/chart.tsx:41:24
 ❯ ../../node_modules/react-chartjs-2/src/chart.tsx:97:5
```

chart.js@4.2.0
react-chartjs-2@5.2.0

**Comment by dangreen** [comment]
@robinelvin https://react-chartjs-2.js.org/faq/registered-scale

**Comment by robinelvin** [comment]
@dangreen Working now. Sorry, I missed the migration guide. Thanks!
