### ISSUE TITLE
Drag across x-axis in combined/line chart 

### ISSUE THREAD

**Issue by Hamza-malikx** [reactchartjs/react-chartjs-2#1070]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

I am trying to use zoom in react-chart-2 ( combined/line chart ) but seems like i am unable to drag the bar along x-axis

`zoom: {
      zoom: {
        wheel: {
          enabled: true, // SET SCROOL ZOOM TO TRUE
        },
        pinch: {
          enabled: true,
        },
        drag: true,
        mode: "xy",
        speed: 2000,
      },
      pan: {
        enabled: true,
        drag: true,
        mode: "xy",
        speed: 100,
      },
    },`
    

### Describe the solution you'd like

Is there something i am missing?
Any kind of help would be appreciated

**Comment by Arantiryo** [comment]
Hi @Hamza-malikx 👋 

I've tried your settings and everything seems to work as it should. Please take a look at [this code sandbox](https://codesandbox.io/s/cranky-merkle-ng2q1k?file=/App.tsx) with an example.

**Comment by Hamza-malikx** [comment]
> Hi @Hamza-malikx 👋
> 
> I've tried your settings and everything seems to work as it should. Please take a look at [this code sandbox](https://codesandbox.io/s/cranky-merkle-ng2q1k?file=/App.tsx) with an example.

I have everything exactly the same as the sandbox u mentioned but it doesn't seem to be working for me though :(

**Comment by Arantiryo** [comment]
Do you think you could make a repo with minimal reproduction?
