### ISSUE TITLE
[Bug]: Error Thrown on Next Build

### ISSUE THREAD

**Issue by LouisJackson** [reactchartjs/react-chartjs-2#1071]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

With NextJS, the library works well on development. But an error is thrown after running the app after building it.
`RangeError: minimumFractionDigits is out of range` 

Tried to setup the easiest example possible on the repo.

### Reproduction

https://github.com/LouisJackson/react-chart-test

### chart.js version

v3.9.1

### react-chartjs-2 version

v4.3.1

**Comment by reactivicky** [comment]
Yes I am facing the same issue. React-chartjs-2 doesnt work with nextjs

**Comment by ktpi2000** [comment]
Getting this same issue.

chartjs: v3.8.0
react-chartjs-2: v4.2.0
next: 12.3.0

**Comment by dangreen** [comment]
Hi guys. react-chartjs-2 is just the wrapper around Chart.js, looks like this issue is in Chart.js, so please create a related problem in the [Chart.js repository](https://github.com/chartjs/Chart.js/issues).

**Comment by LeeLenaleee** [comment]
Putting `swcMinify: false` in `next.config.js` will resolve the issue.

**Comment by Mitrajeet-Golsangi** [comment]
Hello I have tried the `swcMinify : false` method but it did not fix the issue for me. Any ideas ?
I am using : 
react-chart-js v4.3.1
chart-js v3
nextjs v12.3.1

My Next Config:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
	reactStrictMode: true,
	swcMinify: false
};

module.exports = nextConfig;
```
My ChartJS Imports
```js
import React from 'react';
import {
	Chart as ChartJS,
	CategoryScale,
	LinearScale,
	BarElement,
	Title,
	Tooltip,
	Legend,
	defaults,
} from 'chart.js';
import { Bar } from 'react-chartjs-2';

ChartJS.register(
	CategoryScale,
	LinearScale,
	BarElement,
	Title,
	Tooltip,
	Legend
);
```

**Comment by jvandenaardweg** [comment]
Had the same issue, and fixed it by using `swcMinify: false` as stated above.

Just here to say the issue seems fixed in NextJS 13, so you can remove `swcMinify: false`
