### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by itsmejasbirsingh** [reactchartjs/react-chartjs-2#1073]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I 
![image_2022_09_28T07_27_27_874Z](https://user-images.githubusercontent.com/43231159/192716257-2d6f56fd-5e66-4e28-9cf7-9884b398516a.png)
am getting a weird result when resizing the desktop screen

### Reproduction

issue arises when resizing the screen

### chart.js version

2.9.3

### react-chartjs-2 version

2.9.0

**Comment by itsmejasbirsingh** [comment]
Adding position relative works for me.

**Comment by Arantiryo** [comment]
Closing due to versions of `Chart.js` below 3 are no longer supported.
