### ISSUE TITLE
Unit testing difficulty - Failed to create chart: can't acquire context from the given item

### ISSUE THREAD

**Issue by Jordan-Pillai** [reactchartjs/react-chartjs-2#1075]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

I have a BarChart component as follows:

```
  const BarChart = ({ data, options }: BarProps) => {
  const chartRef = useRef<ChartJS<"bar"> | null>(null);

  return (
    <Bar
      options={options}
      data={data}
      ref={chartRef}
      onClick={(event) => {
        const { current: chart } = chartRef;

        if (!chart) return;

        const dataset = getDatasetAtEvent(chart, event);
        const element = getElementAtEvent(chart, event);
        const elements = getElementsAtEvent(chart, event);

        // eslint-disable-next-line no-console
        console.info(dataset, element, elements);
      }}
    />
  );
};
```

I am trying to write unit tests for it however I keep getting the following error message when running the test

 **Failed to create chart: can't acquire context from the given item**

I can't use the suggestion of

`
jest.mock('react-chartjs-2', () => ({
  Bar: () => null
}));
`

because it doesn't render the canvas element

### Describe the solution you'd like

An answer to this problem

**Comment by Arantiryo** [comment]
Hi @Jordan-Pillai :wave:

Have you looked at [the library tests](https://github.com/reactchartjs/react-chartjs-2/blob/master/test/chart.test.tsx)? They should cover most of the use cases.

**Comment by dangreen** [comment]
Closed due to inactivity
