### ISSUE TITLE
[Bug]: Unable to view the guide/ documentation due to codesandbox.io error

### ISSUE THREAD

**Issue by VincensiuD** [reactchartjs/react-chartjs-2#1078]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Unable to view guide from 
https://react-chartjs-2.js.org/examples/scatter-chart

![image](https://user-images.githubusercontent.com/90359816/200201327-61259d5c-98f5-4f2b-8ab5-f90fcab0d746.png

### Reproduction

cannot read the guide from https://react-chartjs-2.js.org/examples/scatter-chart

### chart.js version

v2.0.0

### react-chartjs-2 version

v2.0.0

**Comment by dangreen** [comment]
@VincensiuD Hi. I guess it is a problem with your Internet connection. Please also try to open https://codesandbox.io in the browser.

<img width="1124" alt="Снимок экрана 2022-11-07 в 12 21 27" src="https://user-images.githubusercontent.com/986756/200260584-ae8a6803-06f7-431b-b761-ddf265485335.png">
