### ISSUE TITLE
[Bug]: CodeSanbox examples are not loading

### ISSUE THREAD

**Issue by biganth** [reactchartjs/react-chartjs-2#1079]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

This is probably not the right place to post this but the codesandbox examples on your website are broken.

### Reproduction

Go to https://react-chartjs-2.netlify.app/examples and try to view any example.

### chart.js version

N/A

### react-chartjs-2 version

N/A

### Possible solution

<img width="928" alt="Screen Shot 2022-11-06 at 8 40 07 PM" src="https://user-images.githubusercontent.com/16448/200209688-0c344d9f-66f4-4845-870d-e616733c7d61.png">

**Comment by dangreen** [comment]
@biganth Hi. I guess it is a problem with your Internet connection. Please also try to open https://codesandbox.io in the browser.

<img width="1124" alt="Снимок экрана 2022-11-07 в 12 21 27" src="https://user-images.githubusercontent.com/986756/200260584-ae8a6803-06f7-431b-b761-ddf265485335.png">
