### ISSUE TITLE
Access labels from plugins directly for font colors

### ISSUE THREAD

**Issue by hylink-oscar-caballero** [reactchartjs/react-chartjs-2#1093]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

I want to be able to change each color for labels like in this example from official chart.js channel

https://www.youtube.com/watch?v=u2pNh5_VnkI

### Describe the solution you'd like

Access labels from plugins

```
{
  plugins: {
    legend:{...},
    labels: {
      fontColor: Color[]
    }
  }
}
```

### Describe alternatives you've considered

Extend `PluginOptionsByType` interface to receive labels options.

**Comment by dangreen** [comment]
@hylink-oscar-caballero Hi. react-chartjs-2 is just the wrapper around Chart.js, so if you are experiencing an issue with charts rendering, please create a related issue in Chart.js repository.

https://github.com/chartjs/Chart.js/issues
