### ISSUE TITLE
Support Chart.js v4

### ISSUE THREAD

**Issue by ximex** [reactchartjs/react-chartjs-2#1097]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

Want to use Chart.js v4

### Describe the solution you'd like

Update to support Chart.js v4

### Documentation, Adoption, Migration Strategy

https://github.com/chartjs/Chart.js/releases/tag/v4.0.0-release
https://github.com/chartjs/Chart.js/releases/tag/v4.0.1
https://www.chartjs.org/docs/latest/migration/v4-migration.html

**Comment by dangreen** [comment]
Done in react-chartjs-2 v5
