### ISSUE TITLE
[Bug]: CodeSandbox examples not loading.

### ISSUE THREAD

**Issue by stevensiht** [reactchartjs/react-chartjs-2#1110]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

The examples are not loading in the codesandbox. Every example presents the same error.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/33554212/202455711-28f7ecbe-243a-46ab-a2d4-65472b2b49a4.png">

### Reproduction

https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/bar/vertical?from-embed

### chart.js version

^4.0.0

### react-chartjs-2 version

^4.0.0"

**Comment by gem-hiteshahuja** [comment]
Yes I am facing the same issue on code sandbox

**Comment by dangreen** [comment]
fixed in https://github.com/reactchartjs/react-chartjs-2/commit/0f93ce870ba39a7cd7b911fee8f87d7d69f1ef54
