### ISSUE TITLE
[Bug]: Import Error (Cannot Find Module)

### ISSUE THREAD

**Issue by bonbonsiregar** [reactchartjs/react-chartjs-2#1113]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I'm using chart.js 4.0.0 and react-chartjs-2 5.0.1 but when I try to import the module, it shows error that the module is not found.

```
import React from "react";
import { Chart } from 'react-chartjs-2';
import { Chart as ChartJS, LineController, LineElement, PointElement, LinearScale, Title } from 'chart.js';

ChartJS.register(LineController, LineElement, PointElement, LinearScale, Title);


function LineChart({ chartData }) {
  return (
    <div className="chart-container">
      <h2 style={{ textAlign: "center" }}>Line Chart</h2>
      <Chart
        type='line'
        data={chartData}
        options={{
          plugins: {
            title: {
              display: true,
              text: "Test Data 2016-2020"
            },
            legend: {
              display: false
            }
          }
        }}
      />
    </div>
  );
}

export default LineChart
```

### Reproduction
install chart.js v4.0.0 and react-chartjs-2 v5.0.1

try to import {Line} from "react-chartjs-2"; in any js files and error module not found will appear 

### chart.js version

v4.0.0

### react-chartjs-2 version

v.5.0.1

**Comment by dangreen** [comment]
@bonbonsiregar Hi. Please provide minimal repo with reproduction.

**Comment by bonbonsiregar** [comment]
> @bonbonsiregar Hi. Please provide minimal repo with reproduction. 

done

**Comment by dangreen** [comment]
@bonbonsiregar Sorry, but i don't see the link to the repo.

**Comment by scottodea** [comment]
I'm also having this issue

**Comment by bonbonsiregar** [comment]
It seems that I have to downgrade both chart.js and react-chartjs-2 to previous version, chartjs to v3.9.1 and react-chartjs-2 to 4.3.1 in order for it to work.

while using the latest version of chart.js and react-chartjs-2 require a modification in package,json, I think so. [here](https://react-chartjs-2.js.org/docs/migration-to-v5)
