### ISSUE TITLE
[Bug]: CJS support for Jest

### ISSUE THREAD

**Issue by LouisYoungGMSL** [reactchartjs/react-chartjs-2#1115]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Jest tests that render a tree containing a chart appear to fail after v5.x.x.

```
Cannot find module 'react-chartjs-2' from 'src/components/LineChart/index.tsx'
```

I tested this using Create React App with the default Jest configuration. I think this is caused by the removal of the CJS build. I don't think Jest supports ESM-only modules out of the box. From what I can see, I don't think people who use CRA can use the new version of this library without ejecting and configuring Jest themselves. 

Please can you let me know if this is an expected consequence or if I'm missing something? 

Thanks 🙂 

### Reproduction

https://github.com/louis-young/chartjs-cjs-jest-issue

### chart.js version

v5.0.1

### react-chartjs-2 version

v.4.0.0

**Comment by dangreen** [comment]
@LouisYoungGMSL Hi. Chart.js v4 is ESM only. So react-chartjs-2 can't be commonjs module.

**Comment by igorlukanin** [comment]
> From what I can see, I don't think people who use CRA can use the new version of this library without ejecting and configuring Jest themselves.

@dangreen Is this true? WDYT?

**Comment by LouisYoungGMSL** [comment]
> Hi. Chart.js v4 is ESM only. So react-chartjs-2 can't be commonjs module.

Hi @dangreen, thanks for getting back to me. I understand that it's written using ESM but could you not build for CJS too like a lot of other React libraries for better compatibility?

**Comment by LouisYoungGMSL** [comment]
> Chart.js is ESM only. We can't import ESM in CommonJS module. So react-chartjs-2 can't have CommonJS bundle.

I thought there were tools available to build for different module formats as there's plenty of packages written using ESM that publish ESM, CJS and UMD bundles but perhaps that's not possible here.

> Yes. CRA at all is poorly supported and has rare updates.

> If you will eject react-scripts you should follow [this doc](https://jestjs.io/docs/ecmascript-modules) to enable ESM support in > jest. Or, I can recommend you migrate to vitest. Vitest has ESM support out of the box and has almost the same API as jest. > My example of migration: https://github.com/reactchartjs/react-chartjs-> 2/commit/7f3ec96101d21e43cae8cbfe5e09a46a17cff1ef

I understand that CRA has a few limitations but it's still one of the most popular React build tooling abstractions and has been for years. I use Vite and Vitest myself but there are lots of organisations that have products built using CRA that can't eject or switch tooling and test framework easily. I'm not making a point to try and push this further as you've kindly clarified that unejected CRA support isn't something you're aiming for with v5. I wanted to make sure this is the case as we'll have to stay on v4 until we have a chance to change tooling. 

Thanks for your time 🙂

**Comment by WPaczula** [comment]
I found a workaround for testing components that use chart:
1. Create a separate file which imports all modules connected to chart.js. In my case it was:
```javascript
import * as ChartJSModule from 'chart.js'
import { Chart } from 'react-chartjs-2'
import zoomPlugin, { pan } from 'chartjs-plugin-zoom'
import 'chartjs-adapter-date-fns'

const {
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  TimeScale,
  PointElement,
  LineElement,
  Chart: ChartJS,
} = ChartJSModule

export {
  ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  TimeScale,
  PointElement,
  LineElement,
  Chart,
  zoomPlugin,
  pan,
}
```
2. Import your dependencies from that file
3. In your tests mock the file that exports your chartjs module
```javascript
jest.mock('./chart', () => {
  return {
    ChartJS: { register: jest.fn() },
    CategoryScale: jest.fn(),
    LinearScale: jest.fn(),
    BarElement: jest.fn(),
    Title: jest.fn(),
    Tooltip: jest.fn(),
    Legend: jest.fn(),
    TimeScale: jest.fn(),
    PointElement: jest.fn(),
    LineElement: jest.fn(),
    zoomPlugin: jest.fn(),
    pan: jest.fn(),
    Chart: () => null,
  }
})
```

There is no more error about chartjs not being found and I'm able to test ChartJS as a blackbox - checking if register is called properly or if my Chart has correct props

**Comment by leonardobrito** [comment]
My workaround was create a datum `file` on mocks folder and do a [mapper](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring) for this `file` on jest config:
```js
moduleNameMapper: {
  'react-chartjs-2': '<rootDir>/src/tests/mocks/datum/react-chartjs-2.js',
},
```
At the file (`<rootDir>/src/tests/mocks/datum/react-chartjs-2.js`) we need to export the used components when needed:
```js 
function Doughnut({ children, ...rest }) {
  return <div {...rest}>{children}</div>
}

function Line({ children, ...rest }) {
  return <div {...rest}>{children}</div>
}

export {
  Doughnut,
  Line,
}
```

**Comment by adameichelkraut** [comment]
nice! @leonardobrito that's a great workaround.

I do agree that CRA has it's issues -- but it _does_ provide a cleaner all-in-one experience than ejecting. It's a shame that we've taken that stance towards this library supporting a ton of folks that use it.

**Comment by jean-webdev** [comment]
I also ran into this issue when trying to run Jest for an app made with CRA. It's frustrating that the most obvious choice for adding charts to React doesn't actually support the default tooling for React. But I see the issue is closed so I'll just have to use a workaround.
