### ISSUE TITLE
[Bug]: Doughnut Chart size is decreasing automatically when mouse hover

### ISSUE THREAD

**Issue by WowDarkHole** [reactchartjs/react-chartjs-2#1118]
### Would you like to work on a fix?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I used 2 Doughnut charts in my react app with javascript.
`const stamina_data = {
  datasets: [
    {
      label: "%",
      data: [5, 30],
      backgroundColor: ["#f83472", "#4c565d"],
      borderColor: ["rgba(255, 99, 132, 1)", "rgba(54, 162, 235, 1)"],
      borderWidth: 0,
    },
  ],
};`
`const power_data = {
  datasets: [
    {
      label: "boost",
      data: [40],
      backgroundColor: ["#f83472"],
      borderColor: ["rgba(255, 99, 132, 1)"],
      borderWidth: 0,
    },
  ],
};`
<Doughnut data={stamina_data} />

The issue happened with another developer who checked the chart when the mouse hovered over the chart.
He asked me why the charts go decreased sometimes and I tried.
But It was working on my side and others' side too.
With some problem, I tried zooming in and out of the website.
All other cases are working but at zoom 90%, the issue happened to me too.

Auto decrease happening cases.

1. Zoom change from 80% to 90%, 100% to 90%.
2. Mouse hover when zoom is 90%
3. Any size change events make the chart decrease.

### Reproduction

Not sure How can I do this

### chart.js version

^4.0.1

### react-chartjs-2 version

^5.0.1

**Comment by WowDarkHole** [comment]
https://react-chartjs-2.js.org/examples/doughnut-chart/

This is the react-chartjs example link and also at 90% zoom, the mouse hover event makes the chart animated.

Thank you.

**Comment by dangreen** [comment]
@WowDarkHole Hi. react-chartjs-2 is just the wrapper around Chart.js, so if you are experiencing an issue with charts rendering, please create a related issue in Chart.js repository.

https://github.com/chartjs/Chart.js/issues

**Comment by WowDarkHole** [comment]
Okay. I will. thank you.

**Comment by selvamtechjays** [comment]
got any solutions?
