### ISSUE TITLE
[Bug]: indexAxis: 'y' yields error.  Type 'string' is not assignable to type '"x" | "y"'.

### ISSUE THREAD

**Issue by Randall-Coding** [reactchartjs/react-chartjs-2#1122]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I'm trying to create a horizontal bar chart and set indexAxis: 'y' on my options like so.  

```
const options = {
        indexAxis: "y"...
```

But I'm getting this rather strange type error.  `Type 'string' is not assignable to type '"x" | "y"'.` on compilation with webpacker-dev-server.   When I set `<Bar options={options}...`

### Reproduction

https://codesandbox.io/s/jovial-danny-f3t87l

### chart.js version

v3.8.0

### react-chartjs-2 version

v4.2.0

### Possible solution

I think changing this datatype for indexAxis option to simply `string` should do it.

**Comment by dangreen** [comment]
@Randall-Coding Hi.

You should set type directly

```ts
const options: ChartOptions<'bar'>
```

or use `as` operator

```ts
indexAxis: "y" as const
```

**Comment by Randall-Coding** [comment]
Thanks Dan.  You're the man.
