### ISSUE TITLE
Improve the getting started documentation

### ISSUE THREAD

**Issue by JLCarveth** [reactchartjs/react-chartjs-2#1124]
### Would you like to work on this feature?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

When looking at the getting started information, it seems that creating a chart is as simple as installing the necessary packages, and then importing and using the component. 

However this is not the case. If you look at https://react-chartjs-2.js.org/docs/migration-to-v4/#tree-shaking it's clear that additional imports / configuration is needed to get a working example. 

I am using Chart.js / react-chartjs-2 for the first time, so I never felt compelled to read the migration documents. All required information to get started should be available at a quick glance.

### Describe the solution you'd like

Update the quickstart examples to be accurate:

```
import "chart.js/auto";
import { Doughnut } from 'react-chartjs-2';

<Doughnut data={...} />
```

**Comment by Arantiryo** [comment]
Hi @JLCarveth 👋 

Thank you for the suggestion, it's a great idea! Although I think having an example with tree-shaking might work better as it would introduce this pretty important feature to new users. 

I'll make a PR with the changes momentarily.
