### ISSUE TITLE
[Bug]: Module not found issue ( Can't resolve 'react-chartjs-2')

### ISSUE THREAD

**Issue by super1114** [reactchartjs/react-chartjs-2#1131]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

![image](https://user-images.githubusercontent.com/85962586/208174796-6ed3ada2-c342-40af-a6b7-385b86e6a779.png)

### Reproduction

npm install 

### chart.js version

4.1.0

### react-chartjs-2 version

5.0.1

**Comment by dangreen** [comment]
@super1114 Hi. Please read:

https://react-chartjs-2.js.org/docs/migration-to-v5

https://react-chartjs-2.js.org/faq/esm-only

**Comment by robinalexandre** [comment]
Hello,

It's not working for me even with "chart.js": "^4.1.1" and "react-chartjs-2": "^5.1.0".
I still got the error : Module not found: Can't resolve 'react-chartjs-2'

**Comment by dangreen** [comment]
@robinalexandre Hi. Please provide repo with minimal issue reproduction.

**Comment by robinalexandre** [comment]
I just installed : 

```
    "chart.js": "^4.1.1",
    "chartjs-plugin-annotation": "^2.1.1",
    "chartjs-plugin-zoom": "^2.0.0",
    "react": "^16.8.0",
    "react-chartjs-2": "^5.1.0"
```

Then, importing in a js file : `import {Line} from 'react-chartjs-2';`

And got the error above

**Comment by dangreen** [comment]
@robinalexandre Here is working example: https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/chart/events

Without your reproduction I can't debug your issue.

**Comment by luffespresso** [comment]
I am getting the same issue as @robinalexandre on a brand new install today:
```
    "chart.js": "^4.1.2",
    "react-chartjs-2": "^5.1.0",
    "react": "^18.2.0",
```

**Comment by dangreen** [comment]
@robinalexandre @luffespresso Hi. Please try react-chartjs-2 v5.2.0
