### ISSUE TITLE
[Bug]: Multi Series Pie labels displayed incorrectly

### ISSUE THREAD

**Issue by dzyubadmytro** [reactchartjs/react-chartjs-2#1141]
I am trying to implement [Multi Series Pie](https://www.chartjs.org/docs/latest/samples/other-charts/multi-series-pie.html)
```
  const data = {
    labels: ["a1", "a2", "a3", "a4", "a5", "b1", "b2", "b3"],
    datasets: [
      { data: [1, 2, 4, 5, 11], backgroundColor: ["grey", "blue", "yellow", "aqua", "green"] },
      { data: [3, 9, 11], backgroundColor: ["orange", "red", "black"] },
    ],
  };
  
  <Pie data={data} />
  ```
  
  I expect labels on my data to correspond to data, for example:   
  1 - "a1"
  2 - "a2"
  4 - "a3"
  5 - "a4"
  11 - "a5"

  3 - "b1"
  9 - "b2"
  11 - "b3"
  
  But the actual result is: 
  1 - "a1"
  2 - "a2"
  4 - "a3"
  5 - "a4"
  11 - "a5"

  3 - "a1"
  9 - "a2"
  11 - "a3"
  
  Am I doing something wrong or is it a bug?

### Reproduction

https://codesandbox.io/s/zealous-goldberg-tsbdgt?file=/App.tsx

### chart.js version

4.1.1

### react-chartjs-2 version

5.1.0

**Comment by dangreen** [comment]
@dzyubadmytro Hi.

react-chartjs-2 is just the wrapper around Chart.js, so if you are experiencing an issue with charts rendering, please create a related issue in Chart.js repository.

https://github.com/chartjs/Chart.js/issues
