### ISSUE TITLE
[Bug]: react-chartjs-2 is not working with React Parcel

### ISSUE THREAD

**Issue by musmanzpak** [reactchartjs/react-chartjs-2#1143]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I am trying to use React ChartJs-2 in React Parcel but every time I get the error:
@parcel/core: Failed to resolve 'react-chartjs-2' from './src/App.js'

### Reproduction

https://react-chartjs-2.js.org/

### chart.js version

v4.1.1

### react-chartjs-2 version

v5.1.0

**Comment by dangreen** [comment]
@musmanzpak Hi. Please provide repo with minimal issue reproduction.

**Comment by dangreen** [comment]
@musmanzpak Hi. Please try react-chartjs-2 v5.2.0
