### ISSUE TITLE
[Bug]: live examples page is not functioning properly

### ISSUE THREAD

**Issue by ctmckee** [reactchartjs/react-chartjs-2#1145]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

When I open a "live example" the entire chart begins shrinking up towards the top left of the page until it disappears.  The chart reappears and then cycles back to a completely diminished chart?  This cycle repeats non-stop.

### Reproduction

got to the live examples page

### chart.js version

v2

### react-chartjs-2 version

v2

**Comment by dangreen** [comment]
@ctmckee Hi. Please provide a link where you are exactly seeing this issue.

**Comment by ctmckee** [comment]
https://react-chartjs-2.js.org/examples/bubble-chart

**Comment by dangreen** [comment]
@ctmckee What browser are you using?

**Comment by ctmckee** [comment]
Chrome.  This also happens when I visit examples on chartjs.org

**Comment by ctmckee** [comment]
[Video0.webm](https://user-images.githubusercontent.com/40606780/213537321-e1693cdc-9d8b-4de2-b0e3-3aa529c2e21d.webm)
here is a screen shot of issue

**Comment by ThuyenPV** [comment]
I got the same issue as you. Do you have any solution to solve this issue ?

**Comment by mpalmaira** [comment]
This is happening to me as well. Any updates?

**Comment by Rikki407** [comment]
HI, this is happening with me as well

**Comment by HostedDinner** [comment]
Had the same problem after updating, found this one: https://github.com/chartjs/Chart.js/issues/11139

**Comment by ctmckee** [comment]
I no longer observe the issue
