### ISSUE TITLE
[Bug]: In nextjs 13 while using any of the charts I am getting a category error

### ISSUE THREAD

**Issue by vashisth00** [reactchartjs/react-chartjs-2#1150]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

While using ChartJS-2 I am geting an error while on my nextjs webapp 

Nextjs version is : 13.1.4

Unhandled Runtime Error
Error: "category" is not a registered scale.

Call Stack
Registry._get
node_modules/chart.js/dist/chart.js (5027:0)
Registry.getScale
node_modules/chart.js/dist/chart.js (4980:0)
eval
node_modules/chart.js/dist/chart.js (5738:0)

### Reproduction

Next:13.1.4

### chart.js version

v4.2.0

### react-chartjs-2 version

v5.2.0

**Comment by dangreen** [comment]
https://react-chartjs-2.js.org/faq/registered-scale
