### ISSUE TITLE
[Bug]: Radar Chart, borderDash not working?

### ISSUE THREAD

**Issue by Iulxim** [reactchartjs/react-chartjs-2#1155]
### Current and expected behavior

I am not sure if im doing something wrong or its not working correctly.
Its working on chartjs, but not in react for some reason with the same options. Maybe im not importing everything i need for the border to show as dashed?
```
// Options
const options = {
  maintainAspectRatio: false,
  scales: {
    r: {
      angleLines: {
        lineWidth: 2,
        color: 'rgba(0,0,0, 0.3)',
      },
      pointLabels: {
        color: '#00A24E',
        font: {
          weight: '700',
          size: '12px',
        },
      },
      ticks: {
        beginAtZero: true,
        display: false,
        maxTicksLimit: 4,
      },
      grid: {
        circular: true,
        color: 'rgba(0,0,0, 0.3)',
        borderDash: [2, 4],
      },
    },
  }
}
```

And this are the imports
```
// Imports
Chart.register(PointElement,
  LineElement,
  RadialLinearScale,
  Filler
);
```

### Reproduction

https://codesandbox.io/p/sandbox/ecstatic-pine-jp4zmw

### chart.js version

latest

### react-chartjs-2 version

lastest

**Comment by sweeta-sinha** [comment]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/63840245/232791659-1d989579-ece6-4506-87c0-071365300d0f.png">

**Comment by Iulxim** [comment]
@ChrisWU012 Do you know if there is a way for the labels to be a default gray color, and only to highlight them green or other color if they have value ? ( Side Question )

**Comment by ChrisWU012** [comment]
> @ChrisWU012 Do you know if there is a way for the labels to be a default gray color, and only to highlight them green or other color if they have value ? ( Side Question )

I've got a very similar problem and my radar chart didn't start at zero.
Here is my data and option:

```
const data = {
  labels: ["Thing 1", "Thing 2", "Thing 3", "Thing 4", "Thing 5", "Thing 6"],
  datasets: [
    {
      label: "# of Votes",
      data: [2, 9, 3, 5, 2, 3],
      backgroundColor: "rgba(255, 99, 132, 0.2)",
      borderColor: "rgba(255, 99, 132, 1)",
      borderWidth: 1,
    },
  ],
};
const options = {
  scales: {
    r: {
      ticks: {
        beginAtZero: true,
        min: 0,
        max: 60,
      },
    },
  },
};
```

Result:
![image](https://github.com/reactchartjs/react-chartjs-2/assets/67308492/0be99691-f887-4065-9879-b34073a2b47a)
