### ISSUE TITLE
[Bug]: Website is down

### ISSUE THREAD

**Issue by atlanteh** [reactchartjs/react-chartjs-2#1217]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Going to the website shows an error page
https://react-chartjs-2.js.org/

![image](https://github.com/reactchartjs/react-chartjs-2/assets/3952700/242c555a-08cd-469f-a40d-957d127c0fa0)

### Reproduction

Not relevant

### chart.js version

Not relevant

### react-chartjs-2 version

Not relevant

**Comment by dracarys55** [comment]
Same here

**Comment by samuelkime267** [comment]
same here

**Comment by BadMachine** [comment]
same

**Comment by cnlgks1** [comment]
same

**Comment by imsuvesh** [comment]
It looks like no one is maintaining, last release was 1 year back.
Tagging a few people who worked on it in the past. 

@igorlukanin @dangreen

**Comment by DevinWalker** [comment]
Uh oh. That's too bad... This is a nice libary.

**Comment by dracarys55** [comment]
It's still down.

**Comment by BadMachine** [comment]
Hey guys, while original website is down I deployed current website version [https://react-chartjs-2-two.vercel.app/](url)
U r welcome :)

**Comment by dracarys55** [comment]
> https://react-chartjs-2-two.vercel.app/

Thanks soooo much! That helps a lot man.

**Comment by OGSoftSystem** [comment]
> Hey guys, while original website is down I deployed current website version [https://react-chartjs-2-two.vercel.app/](url) U r welcome :)

Thanks a million.

**Comment by Kasun002** [comment]
Can someone suggest a similar library for React web?

Because it seems not maintaining properly

**Comment by dracarys55** [comment]
> Can someone suggest a similar library for React web?
> 
> Because it seems not maintaining properly

Maybe using Rechart : https://recharts.org/en-US
But I still love react charts more..

**Comment by dangreen** [comment]
🎄Happy New Year 🎁

https://react-chartjs-2.js.org
