### ISSUE TITLE
[Bug]:  official website is down 

### ISSUE THREAD

**Issue by cmingxu** [reactchartjs/react-chartjs-2#1219]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

official website is down

### Reproduction

https://react-chartjs-2.js.org/

### chart.js version

v0.1.1

### react-chartjs-2 version

v0.1.1

**Comment by dulara1994** [comment]
The issue persists. till then we can use [webarchive](https://archive.org/details/github.com-reactchartjs-react-chartjs-2_-_2021-04-23_12-03-35)

**Comment by ayoubbyr** [comment]
> dulara1994

Very smart, thanks for sharing

**Comment by BadMachine** [comment]
Hey guys, while original website is down I deployed current website version [https://react-chartjs-2-two.vercel.app/](https://github.com/reactchartjs/react-chartjs-2/issues/url)
U r welcome :)

**Comment by ayoubbyr** [comment]
> Hey guys, while original website is down I deployed current website version [https://react-chartjs-2-two.vercel.app/](https://github.com/reactchartjs/react-chartjs-2/issues/url) U r welcome :)

People like you make development survivable 🤣 thank you

**Comment by jamietdavidson** [comment]
Please fix this!

**Comment by lladneknai** [comment]
Please fix! Still down two weeks later...

**Comment by K0rmir** [comment]
> > Hey guys, while original website is down I deployed current website version [https://react-chartjs-2-two.vercel.app/](https://github.com/reactchartjs/react-chartjs-2/issues/url) U r welcome :)
> 
> People like you make development survivable 🤣 thank you

Life saver thank you!

**Comment by Zafkiel45** [comment]
It's been weeks that the official website is down... Happiness a workaround was found. But, the last commit was 9 months ago... The repository isn't more active?

**Comment by github-burner1235** [comment]
@Zafkiel45 this library has been dead since like a year, migrate to another alternative, there are tons of them.

**Comment by jamietdavidson** [comment]
For anybody who stumbles upon this,

I spent a few days examining all of the alternative options looking for something that struck a good balance of customizability, ease of use, and good docs.

Of all of the options I tried, I opted for https://nivo.rocks.

Yes, its docs look a little odd at first, but when you dive into them they're actually super intuitive.

Hope this is helpful for anyone else!

**Comment by jwalkerinterpres** [comment]
> migrate to another alternative, there are tons of them.

This is the only library listed on the Chart.js site for React; what other alternatives exist?

**Comment by aamir-067** [comment]
> Hey guys, while original website is down I deployed current website version [https://react-chartjs-2-two.vercel.app/](https://github.com/reactchartjs/react-chartjs-2/issues/url) U r welcome :)

you are real hero 🫡

**Comment by sangmin-iam** [comment]
> Hey guys, while original website is down I deployed current website version [https://react-chartjs-2-two.vercel.app/](https://github.com/reactchartjs/react-chartjs-2/issues/url) U r welcome :)

Thank you so much!

**Comment by Vijaybhatia2208** [comment]
> Hey guys, while original website is down I deployed current website version [https://react-chartjs-2-two.vercel.app/](https://github.com/reactchartjs/react-chartjs-2/issues/url) U r welcome :)

Thank you It is very helpful !

**Comment by dangreen** [comment]
https://github.com/reactchartjs/react-chartjs-2/issues/1217#issuecomment-2565954300
