### ISSUE TITLE
Problem about documentation

### ISSUE THREAD

**Issue by RickyKongCoder** [reactchartjs/react-chartjs-2#1221]
I recently read the repo and find out that the documentation page are all gone.
e.g. for components and examples .... ... 
I would like to know is it possible to update new documentation for this repo.

**Comment by waqaspassu** [comment]
The documentation site is down.

**Comment by nevroks** [comment]
when fix?

**Comment by Zafkiel45** [comment]
> It's been down for over a week. Please fix :(

This is probably an abandoned repository. I recommend looking for alternatives. But, if you really need of this, so follow this link: https://react-chartjs-2-two.vercel.app/


Someone deployed the documentation while the official is down. https://github.com/reactchartjs/react-chartjs-2/issues/1219#issuecomment-2206597972

**Comment by Vic-rider** [comment]
thanks @Zafkiel45

**Comment by dangreen** [comment]
https://github.com/reactchartjs/react-chartjs-2/issues/1217#issuecomment-2565954300
