### ISSUE TITLE
[Bug]: Your website is not working!

### ISSUE THREAD

**Issue by Sreejit-Sengupto** [reactchartjs/react-chartjs-2#1225]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

![image](https://github.com/user-attachments/assets/20a4f409-9479-4b14-af82-1913520409ad)

### Reproduction

Go to this link: https://react-chartjs-2.js.org/components

### chart.js version

latest

### react-chartjs-2 version

latest

**Comment by kennedywee** [comment]
I think the whole website is broken

Link: https://react-chartjs-2.js.org/

<img width="823" alt="image" src="https://github.com/user-attachments/assets/4bbc8a56-8935-4732-9f4d-72009a6fb263">

**Comment by kennedywee** [comment]
The official website is down but you can visit https://react-chartjs-2-two.vercel.app/

Refer:
https://github.com/reactchartjs/react-chartjs-2/issues/1219#issuecomment-2206597972

**Comment by Sreejit-Sengupto** [comment]
> I think the whole website is broken
> 
> Link: https://react-chartjs-2.js.org/
> 
> <img width="823" alt="image" src="https://github.com/user-attachments/assets/4bbc8a56-8935-4732-9f4d-72009a6fb263">
> 

Yes!

**Comment by Sreejit-Sengupto** [comment]
> The official website is down but you can visit https://react-chartjs-2-two.vercel.app/
> 
> Refer:
> https://github.com/reactchartjs/react-chartjs-2/issues/1219#issuecomment-2206597972

Thanks! Is this the official one?

**Comment by kennedywee** [comment]
Yup! just use this until the https://react-chartjs-2.js.org is up
