### ISSUE TITLE
[Bug]: The netlify website link is not found (error: 404)

### ISSUE THREAD

**Issue by Burnabaso** [reactchartjs/react-chartjs-2#1226]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Now If I click to visit the website of react-chartjs-2 error 404 is occurring. Usually the website opens normally to check the documentation.

### Reproduction

https://react-chartjs-2.js.org/

### chart.js version

chart.js@4.4.4 

### react-chartjs-2 version

react-chartjs-2@5.2.0

### Possible solution

check the netlify deployment

**Comment by zulianAdryan** [comment]
yeah, it's been like this for about 2 months and has never been fixed. I thought it would be fixed soon but now when I need to see the website again it still shows the same Netlify error

**Comment by andrew-mckeever-voids** [comment]
Is this Library dead then? 2 months down is ages

**Comment by arechsteiner** [comment]
It's a little more cumbersome but you can still browse the docs content in the repo directly:

https://github.com/reactchartjs/react-chartjs-2/tree/master/website/docs

**Comment by andrew-mckeever-voids** [comment]
The chartjs docs are serving as a decent alternative

**Comment by Manoj-nathwani** [comment]
You can access the docs here - https://react-chartjs-2-two.vercel.app/examples/stacked-bar-chart

**Comment by Burnabaso** [comment]
Thank you all for your contribution
