### ISSUE TITLE
[Bug]: Site Not Found - 404 

### ISSUE THREAD

**Issue by iamabhijeet2003** [reactchartjs/react-chartjs-2#1229]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

The current deployment of [ReactChartjs](https://react-chartjs-2.js.org/) can't be accessed. It is showing a 404 error.

![image](https://github.com/user-attachments/assets/7e8e1d50-0e5e-4dac-82ff-a4811c5b3ca3)

### Reproduction

Error 404

### chart.js version

v4.4.4

### react-chartjs-2 version

v5.2.0

**Comment by iamabhijeet2003** [comment]
> Check original vercel url here https://react-chartjs-2-two.vercel.app/

Thanks, I can access this URL.

BTW, the url at the repository home should be changed, as this one is unaccessible:
![image](https://github.com/user-attachments/assets/28d22617-4698-4e0b-9b68-a2bfb1c98ae7)

**Comment by dangreen** [comment]
https://github.com/reactchartjs/react-chartjs-2/issues/1217#issuecomment-2565954300
