### ISSUE TITLE
[Bug]: doc links are not working

### ISSUE THREAD

**Issue by Mah-mu-dul** [reactchartjs/react-chartjs-2#1230]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

![image](https://github.com/user-attachments/assets/7b2e85fc-9ce2-4ffc-a4f4-6e199de1de4e)
![image](https://github.com/user-attachments/assets/3df1ef18-dd53-4514-8a80-4c4df76e9d1e)

### Reproduction

https://github.com/reactchartjs/react-chartjs-2

### chart.js version

current v

### react-chartjs-2 version

current v

**Comment by arrmani88** [comment]
SAME HERE (y)

**Comment by iamabhijeet2003** [comment]
Please try to review other issues before opening new one.

This issue has been discussing in the issue #1229

**Comment by agilgur5** [comment]
> This issue has been discussing in the issue #1229

That issue is itself a duplicate: #1221, #1219, #1217

**Comment by eslachance** [comment]
When you have 6 different tickets over 6 months describing how a simple thing is broken and none of the devs react, you know your library is dead. Sorry y'all, it's clear @dangreen doesn't really care about this lib anymore.

**Comment by dangreen** [comment]
Hi all! Previously my work on react-charjs-2 was sponsored by Cube, but that ended. I can offer you two options:
1) I can add someone who wants as a new maintainer
2) You can sponsor my work on react-charjs-2 using [ko-fi](https://ko-fi.com/dangreen)

**Comment by dangreen** [comment]
https://github.com/reactchartjs/react-chartjs-2/issues/1217#issuecomment-2565954300
