### ISSUE TITLE
[Bug]: All doc links on README github page lead to 404

### ISSUE THREAD

**Issue by dSwiergiel** [reactchartjs/react-chartjs-2#1234]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

All doc links on README github page lead to 404. I expect the doc pages to not be missing.

### Reproduction

https://github.com/reactchartjs/react-chartjs-2.git

### chart.js version

v4.x.x

### react-chartjs-2 version

v5.2.0

### Possible solution

The website hosting the docs seems to be down or misconfigured causing the links to 404.

**Comment by dangreen** [comment]
https://github.com/reactchartjs/react-chartjs-2/issues/1217#issuecomment-2565954300
