### ISSUE TITLE
[Bug]: Site link does not work

### ISSUE THREAD

**Issue by Shatlyk1011** [reactchartjs/react-chartjs-2#1237]
### Current and expected behavior

[Official link ](https://react-chartjs-2.js.org/) leads to 404 page

### Reproduction

click the link in [About](https://github.com/reactchartjs/react-chartjs-2) section of this repo

### chart.js version

~

### react-chartjs-2 version

~

**Comment by pramod0507** [comment]
Link: 
https://react-chartjs-2-two.vercel.app/

**Comment by dangreen** [comment]
https://github.com/reactchartjs/react-chartjs-2/issues/1217#issuecomment-2565954300
