### ISSUE TITLE
Hooks refactor

### ISSUE THREAD

**Issue by Pringels** [reactchartjs/react-chartjs-2#459]
Refactor the chart wrapper into a functional component with hooks.

**Comment by defusioner** [comment]
Am I right saying that the final version should be using react 16 and should be a major cause it will break react 15 support?

**Comment by defusioner** [comment]
@jerairrest what do you think of it? For me, this should be the core ticket in the Chart 3.0 milestone

**Comment by jerairrest** [comment]
> Am I right saying that the final version should be using react 16 and should be a major cause it will break react 15 support?

I believe this is correct.

**Comment by jhonnold** [comment]
Is any progress being made on the 3.0 release? If not I wouldn't mind working through some of these and submitting PRs. Just want to make sure I'm not conflicting with anyone.

**Comment by jerairrest** [comment]
Hey!

Thanks for reaching out to me!

Sadly my work life has chewed up a lot of my open source time.

We did have some folks interested, but it's kinda fallen apart.

If you're still interested I can invite you to our slack channel


Jer
