### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by Pringels** [reactchartjs/react-chartjs-2#462]
Add some issues templates for bugs, feature requests and questions.

The goal is to reduce the number of issues with the following problems:

1.) Not enough information provided to reliably reproduce a bug
2.) Questions, enhancements and bugs related to Chart.js. (this is a very common one)

**Comment by Jareechang** [comment]
hey @Pringels, I think best its best to request people to update their code into https://codesandbox.io/ and post the link.

That way the its easier to re-produce and resolve issues.
