### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by defusioner** [reactchartjs/react-chartjs-2#472]
As I can see, the project is quite outdated:
- old Babel plugins
- old storybook dependencies
- 8 low, 7 moderate, 21 high, 1 critical dependencies

With the #459 and Chart 3.0 milestone, I think we should fix and tree-shake.

@jerairrest

**Comment by Pringels** [comment]
@defusioner we're actively working on a complete overhaul of the library using [tsdx](https://github.com/jaredpalmer/tsdx). This will form part of the Chart 3.0 milestone. See branch: https://github.com/jerairrest/react-chartjs-2/tree/feature/chartjs3-rewrite

**Comment by defusioner** [comment]
@Pringels Thanks for the feedback.

Can I help you somehow?

**Comment by Pringels** [comment]
@defusioner sure :) I will set up a project with issues for the 3.0 refactor. If you're keen to contribute regularly we have a small slack group we use to coordinate things.  (ask @jerairrest for an invite)
