### ISSUE TITLE
Migrate tests from Mocha to Jest

### ISSUE THREAD

**Issue by Pringels** [reactchartjs/react-chartjs-2#478]
We want to use Jest and `react-testing-library` to test the 3.0 version. Migrate all the existing tests to Jest syntax, and make any required adjustments to the mocks/specs if required.

**Comment by theashraf** [comment]
I'd like to help with this one

**Comment by Pringels** [comment]
@theashraf sure thing! you can check out https://github.com/jerairrest/react-chartjs-2/tree/feature/chartjs3-rewrite and start there. The Jest setup is already up and running. you'll have to copy the tests from what is currently on master. 

If you experience any issues with Typescript let me know. I hastily added some types but I suspect it's not quite 100% yet.
