### ISSUE TITLE
Implement the new chart.js 3.0 API

### ISSUE THREAD

**Issue by Pringels** [reactchartjs/react-chartjs-2#480]
Implement changes (if any) required to be compliant with the new 3.0 API of chart.js.

Track their progress here:
https://github.com/chartjs/Chart.js/issues/6598
https://github.com/chartjs/Chart.js/milestone/16

**Comment by benmccann** [comment]
Chart.js 3.0.0-alpha is now available. Get it with `npm install chart.js@next --save`

* [Release notes](https://github.com/chartjs/Chart.js/releases/tag/v3.0.0-alpha)
* [npm](https://www.npmjs.com/package/chart.js)
* [Migration guide](https://www.chartjs.org/docs/next/getting-started/v3-migration.html)
* [Docs](https://www.chartjs.org/docs/next/)
* [API](https://www.chartjs.org/docs/next/typedoc/)
* [Samples](https://www.chartjs.org/samples/next/)

**Comment by jerairrest** [comment]
Thanks for the heads up Ben!

**Comment by kashifshamaz21** [comment]
@jerairrest Do we have any approx. timeline for when we'll have Chartjs v3 supported in this library? Thanks for any information or update you can provide about this milestone.

**Comment by benmccann** [comment]
Chart.js 3.0 final is out now
