### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Pringels** [reactchartjs/react-chartjs-2#481]
Update the readme and relevant code docs to include the following:

- New usage of chart.js 3.0 (if required)
- New information on how to set up the project locally (See tsdx docs)
- Compatibility notes regarding react hooks and chart.js 3.0 dependency
- Link to legacy docs?

**Comment by jonathantvrs** [comment]
Hi @Pringels. Do you think about the legend options in all the examples? and add the code for these examples on the example page?

**Comment by YakovlevCoded** [comment]
@igorlukanin
