### ISSUE TITLE
Can't word-wrap legend text

### ISSUE THREAD

**Issue by ksandr-dev** [reactchartjs/react-chartjs-2#488]
![Screen Shot 2020-01-30 at 6 17 20 AM](https://user-images.githubusercontent.com/25770330/73457318-58746f80-4328-11ea-828d-8033bb8db768.png)

**Comment by Arantiryo** [comment]
I’m closing this issue because it has been inactive for some time. 

There's an [issue](https://github.com/chartjs/Chart.js/issues/3641) on `Chart.js` page that has a possible solution.
