### ISSUE TITLE
[Bug] Legend does not update color.

### ISSUE THREAD

**Issue by jpirzent** [reactchartjs/react-chartjs-2#489]
Not sure if this is an issue with this wrapper, or with the base project, but the legend color does not seem to update between data changes... I have 3 "sections" on my page, that display different data sets, with different colors. I use the same chart for all 3 sections, with selectors to change to a different section. When I change sections, the data changes properly, and the color on the chart updates properly, but the color in the legend does not update until a different section is selected, and then it updates to the previous color. 

I'm not sure if I'm just using the package wrong. TIA.

**Comment by philippfrank** [comment]
@jpirzent Same issue here. Did you come up with a solution?

**Comment by jpirzent** [comment]
Ah, cool. I didn't find a solution yet, ended up just leaving the legend out for now.

**Comment by dangreen** [comment]
Closed due to inactivity.
