### ISSUE TITLE
ToolTip Customize problem

### ISSUE THREAD

**Issue by morijenab** [reactchartjs/react-chartjs-2#492]
Hello 
I am trying to customize ToolTip of react chart2. I found this piece of code:

     ```
const options = {
        tooltips: {
          enabled: false,
          custom: showTooltip,
        }
     }

    const showTooltip = (tooltip) => {
        console.log("opacity:"tooltip.opacity);
        if (tooltip.opacity === 0) {
          console.log('opacity is === 0');
    
          setState({
            showTooltip: false,
            tooltip: undefined
          })
        } else {
          setState({
            ...state,
            top: tooltip.caretY - 600,
            left: tooltip.caretX,
            data: "payload.date",
            showTooltip: true,
          });
        }
      }
```

the problem is when i click on one data node  the code set ShowToolTip but it never changed!
even when i click other sides of charts. the line that i wrote for test console.log('opacity is === 0');
never executed, and all logs are "opacity:1". why when i leave that node the custom tooltip function doesn't  invoke again that i can set ShowTooltip:false. 

anyone have the same problem ?

Best Regards.

**Comment by gks66** [comment]
I have the same issue when there are setState in custom, callback->label function. 
I am planning to make tooltips allow custom label have a onClick on different label.

**Comment by Morteza-Jenabzadeh** [comment]
this the way how I handle the problem:
`const [state, setState] = React.useState<IState>({
    top: 0,
    left: 0,
    data: "",
    showTooltip: false,
    node: 0,
    tooltip: undefined
  });




  const showTooltip = (tooltip: ITooltip) => {
    if (tooltip.opacity === 0) {
      setState({
        showTooltip: false,
        tooltip: undefined
      })
    } else {
      setState({
        ...state,
        top: tooltip.caretY - 400,
        left: tooltip.caretX + 20,
        data: "payload.date",
        showTooltip: true,
        node: tooltip.dataPoints[0].index
      });
    }
  }
const hide = () => {
    if (state.showTooltip) {
      setState({
        showTooltip: false,
        tooltip: undefined
      })
    }
  }
  const options = {
    onHover: hide,
    tooltips: {
      enabled: false,
      custom: showTooltip,
    },
    mode: "index"
  }
useEffect(() => {
    if (!dataSource) {
      return
    }
    setData({
      labels: Array(edges.length).fill(""),
      datasets: [
        {
          label: '',
          fill: false,
          lineTension: 0.1,
          backgroundColor: 'rgba(75,192,192,0.4)',
          borderColor: 'rgba(75,192,192,1)',
          borderCapStyle: 'butt',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointBorderColor: 'rgba(75,192,192,1)',
          pointBackgroundColor: '#fff',
          pointBorderWidth: 5,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: 'rgba(75,192,192,1)',
          pointHoverBorderColor: 'rgba(220,220,220,1)',
          pointHoverBorderWidth: 5,
          pointRadius: 5,
          pointHitRadius: 5,
          data: generateRandomNumber(edges.length)
        }
      ]
    })
  }, [dataSource])

JSX  ->

 {state.showTooltip
              ? <div
                style={{
                  position: 'absolute',
                  color: 'white',
                  backgroundColor: 'rebeccapurple',
                  top: state.top,
                  left: state.left,
                }}
              >
                <Card url={edges[(state.node as number)].node.display_url}
                  like={edges[(state.node as number)].node.edge_liked_by.count}
                  comment={edges[(state.node as number)].node.edge_media_to_comment.count}
                />
              </div>
              : null
            }
          </div>
`

of course its not the best solution as the event handler called on every single hover movement but still works!

**Comment by gks66** [comment]
I used the onHover function and customize the point, onHover only close when hover on customize tooltip.
it is some how works now! Thanks
