### ISSUE TITLE
Line chart Legend on top left

### ISSUE THREAD

**Issue by Vitali883** [reactchartjs/react-chartjs-2#505]
Hi. I have i problem with legend stuff. i want it to be on top left. BUT, i dont know how to do that. I tried everything i can, like: position, align, but nothing works for me. Please, help.

P.S Look at the picture.

![chartIssue](https://user-images.githubusercontent.com/33987786/77255522-ec035600-6c70-11ea-8114-4a609b3e494a.png)

**Comment by nicholasess** [comment]
@Vitali883 You can try to seeing the documentation oficial
https://www.chartjs.org/docs/latest/configuration/legend.html

**Comment by nasr18** [comment]
@nicholasess  I tried, but not working. Legend position not changing.

**Comment by Vitali883** [comment]
> @nicholasess I tried, but not working. Legend position not changing.
> 
> ```
> const lineData = {
>     labels,
>     datasets,
>     options: {
>       legend: {
>         align: 'start',
>       },
>     },
>   }
> 
>   return <Line data={lineData} />
> ```
> 
> ![image](https://user-images.githubusercontent.com/7514936/85194183-5b2d2c80-b2ea-11ea-8cb2-15b3af3802fd.png)

I think it's not possible on this package

**Comment by nasr18** [comment]
@Vitali883 I achieved what I want. Instead of passing inside `lineData`, we have to pass it as a separate props. 

`<Line legend={{position: 'bottom', align: 'start' }} options={options} data={lineData} />`

**Comment by ArtStepanyuk** [comment]
Having the same issue with `"react-chartjs-2": "^2.7.6"` @nasr18  your code didn't for me either what versions of "chartjs" and  "react-chartjs-2" are you using?

**Comment by brianwachira** [comment]
> @Vitali883 I achieved what I want. Instead of passing inside `lineData`, we have to pass it as a separate props.
> 
> `<Line legend={{position: 'bottom', align: 'start' }} options={options} data={lineData} />`

It's 2022, still experiencing the same problem. I am using typescript and I am getting the error 

> Type '{ data: { labels: string[]; datasets: { label: string; data: number[]; backgroundColor: string[]; }[]; }; options: { responsive: true; maintainAspectRatio: true; }; legend: { position: string; align: string; }; }' is not assignable to type 'IntrinsicAttributes & Omit<ChartProps<"doughnut", number[], string>, "type"> & { ref?: ForwardedRef<ChartJSOrUndefined<"doughnut", number[], string>> | undefined; }'.
  Property 'legend' does not exist on type 'IntrinsicAttributes & Omit<ChartProps<"doughnut", number[], string>, "type"> & { ref?: ForwardedRef<ChartJSOrUndefined<"doughnut", number[], string>> | undefined; }'.t

**Comment by Arantiryo** [comment]
>> @Vitali883 I achieved what I want. Instead of passing inside lineData, we have to pass it as a separate props.
>> <Line legend={{position: 'bottom', align: 'start' }} options={options} data={lineData} />

> It's 2022, still experiencing the same problem. I am using typescript and I am getting the error

To configure chart legend you should remove 'legend' prop and define options like this:

```typescript
const options = {
  plugins: {
    legend: {
      position: "bottom" as const,
      align: "start" as const
    },
  title: {
      display: true,
      text: "Chart.js Line Chart"
    }
  }
};
```

For more information you can check out [chartjs docs on legend](https://www.chartjs.org/docs/latest/configuration/legend.html).
