### ISSUE TITLE
Line chart on react chart-js disappears in long graphs

### ISSUE THREAD

**Issue by gathanasprot** [reactchartjs/react-chartjs-2#508]
Line disappears about halfway in graphs with great width (above 10000px) and only the data points (dots) remain.
Graph is wrapped around a div with smaller width and overflow:auto so that there is a scrollbar to navigate it.
I haven't found any other way to show graphs with large datasets (may reach above 300 points).
If i don't use this trick, graph works normally but chart is unreadable.

Issue with big width:
![graph_issue_big_width](https://user-images.githubusercontent.com/45594407/78643724-5ea14200-78bd-11ea-8252-0e3781eb6f4a.jpg)

When no extra width is applied:
![graph_no_extra_width_applied](https://user-images.githubusercontent.com/45594407/78643729-606b0580-78bd-11ea-955d-254fac49fcb0.jpg)

**Comment by wakenn** [comment]
I'm looking for the answer to this as well. Labels get skipped but the data points do not. Here's 3 years of data by day.
<img width="1056" alt="Screen Shot 2020-07-13 at 9 52 46 PM" src="https://user-images.githubusercontent.com/3969616/87378384-4c394300-c553-11ea-971e-5fa560da0f33.png">

**Comment by farrukhrashid1997** [comment]
Can you post the code?
