### ISSUE TITLE
Tooltip on hover not working 

### ISSUE THREAD

**Issue by PeterHassaballah** [reactchartjs/react-chartjs-2#512]
I am using the doughnut example from the repo but the tootip simply does not appear while hovering over the doughnut sections , I tried clicking aggressive hovering nothing happens and the console does not show any errors .
react-chartjs-2 version: "2.9.0",
"chart.js": "2.9.3",
"react": "16.13.1",
OS: Windows 10,
Chrome Version:81.0.4044.113 
I honestly don't know if this repo is maintained or not that's why I haven't created any demo to reproduce the issue

**Comment by imsaha** [comment]
Hi guys, any solution so far? I am also facing the same issue.

"chart.js": "^2.9.4",
 "react": "^17.0.1",
 "react-chartjs-2": "^2.11.1",

**Comment by barrychapman** [comment]
I have this same issue

**Comment by dangreen** [comment]
Closed due to inactivity.

**Comment by Spomsoree** [comment]
I've ran into the same issue. I feel like I'm missing a import maybe

```
Chart.register(
    LineController,
    LineElement,
    PointElement,
    LinearScale,
    Title,
    Legend,
    CategoryScale,
);
```

**Comment by lymine1996** [comment]
According to the answer from @dangreen in #907, the tooltip component needs to be imported and registered so that it can actually show up in the chart:
```
import {..., Tooltip} from 'chart.js';
...
ChartJS.register(..., Tooltip );
```
