### ISSUE TITLE
Grouped and Stacked Bar Graph

### ISSUE THREAD

**Issue by C-reddd** [reactchartjs/react-chartjs-2#518]
Hello,

I am currently trying created a "Stacked-Grouped" Bar graph. I am able to do so but when I try to have two different Datasets with the same "label" but different "Stacks", they're associating both Datasets together.

For example:
`datasets: [
      {
        label: 'Connor',
        backgroundColor: 'red',
        data: [20, 10, 30, 50],
        stack: 1
      },
      {
        label: 'Connor',
        backgroundColor: 'blue',
        data: [40, 50, 20, 50],
        stack: 2
      }
    ],
    labels
  };`
Will produce something like this:

![image](https://user-images.githubusercontent.com/61790284/82499560-d9b26680-9abf-11ea-9d07-a3de35fdc626.png)

However, if i change the code to:
`datasets: [
      {
        label: 'Connor',
        backgroundColor: 'red',
        data: [20, 10, 30, 50],
        stack: 1
      },
      {
        label: 'Connor1,
        backgroundColor: 'blue',
        data: [40, 50, 20, 50],
        stack: 2
      }
    ],
    labels
  };`

It produces: 
![image](https://user-images.githubusercontent.com/61790284/82499651-0f574f80-9ac0-11ea-9e77-8f65b8292ad6.png)

Is there anyway around this or is it simply a limitation?

Thanks :)

**Comment by smootoo** [comment]
I think this part of the readme addresses your question
https://github.com/jerairrest/react-chartjs-2#working-with-multiple-datasets

**Comment by kamok** [comment]
Did you figure this out?

**Comment by Arantiryo** [comment]
I'm closing this because the issue has been fixed in a newer version as [demonstrated here](https://codesandbox.io/s/holy-glitter-l4edj2?file=/App.tsx).
