### ISSUE TITLE
Chart resizing

### ISSUE THREAD

**Issue by juliangsibecas** [reactchartjs/react-chartjs-2#531]
Hi! I'm having troubles with chart's resizing when parents size changes. When I toggle the sidebar the chart doesn't resize.

![image](https://user-images.githubusercontent.com/25715495/85186302-9e49ba00-b26e-11ea-9d91-df32cf3a2f2b.png)
![image](https://user-images.githubusercontent.com/25715495/85186314-ab66a900-b26e-11ea-8ecb-20a4a6b11757.png)

**Comment by typpo** [comment]
Have you set `responsive: true` in options?  Can you post an example?  Also note that the parent container must be set up correctly: https://www.chartjs.org/docs/latest/general/responsive.html#important-note

**Comment by juliangsibecas** [comment]
I forgot to add the position relative to the parent. Thanks and regards @typpo !

**Comment by sam-eah** [comment]
I have the same exact issue, however setting position relative to the parent and responsive: true doesn't seem to work for me.
I have noticed that closing the sidebar correctly enlarges the chart, whereas opening the sidebar doesn't shrink it. Same thing with resizing the window, the chart can grow but never shrinks. 
If I reload the page or the component (putting it in some tabs for example and switching tabs), then it will take the correct size.

**Comment by OlgaPolunina** [comment]
I had problems resizing the chart because of Chart.platform.disableCSSInjection = true;

With **Chart.platform.disableCSSInjection = false;** Working resizing

**Comment by juhaelee** [comment]
@sam-eah did you ever figure out the issue?
