### ISSUE TITLE
add vertical line to Line chart

### ISSUE THREAD

**Issue by mahdihasanzadeh-dev** [reactchartjs/react-chartjs-2#532]
Hello
How can I add a vertical line to Line chart like screenshot below?
![Untitled](https://user-images.githubusercontent.com/25902202/85231127-ef41e580-b409-11ea-8efd-17c4c805f92f.png)

**Comment by typpo** [comment]
Check out [chartjs-plugin-annotation](https://github.com/chartjs/chartjs-plugin-annotation) to add annotations such as vertical lines to your chart.

Then register it per [this section](https://github.com/jerairrest/react-chartjs-2/#chartjs-object) of the readme.
