### ISSUE TITLE
Small values do not appear on the chart

### ISSUE THREAD

**Issue by ali27001** [reactchartjs/react-chartjs-2#536]
I am using donut chart. Since there is a lot of difference between the values, I cannot see some values in color on the chart. How can I do that

  const newData = [11973.57,253.83,17280, 4451.81,154.16]
  const options = {
    legend: {
      display: true
    },
    responsive: true,
    maintainAspectRatio: false,
    animation: false,
    cutoutPercentage: 80,
    layout: { padding: 0 },
    tooltips: {
      enabled: true,
      mode: 'index',
      intersect: false,
      borderWidth: 1,
      borderColor: theme.palette.divider,
      backgroundColor: theme.palette.white,
      titleFontColor: theme.palette.text.primary,
      bodyFontColor: theme.palette.text.secondary,
      footerFontColor: theme.palette.text.secondary
    },
    offset:true
  };
![Ekran Resmi 2020-07-03 16 18 42](https://user-images.githubusercontent.com/34340185/86473059-e37aeb00-bd48-11ea-9b03-b2e48d08429e.png)

**Comment by owen-duncan-snobel** [comment]
I think it has to do mainly with the difference in size of the data. If you toggle off the larger data are you able to see the smaller ones with colour? Think about how the doughnut works it is proportional to the size of the specific data compared to the rest of the data. When it is that small compared to size of the other data point it is almost infinitesimal. I'm not sure this is a good graph to display data that differs that vastly in size like this.

**Comment by ali27001** [comment]
> Bence bunun esas olarak veri boyutundaki farkla ilgisi var. Daha büyük verileri kapatırsanız, küçük olanları renkli olarak görebilirsiniz? Donut'un nasıl çalıştığını düşünün, verilerin geri kalanıyla karşılaştırıldığında belirli verilerin boyutuyla orantılı olduğunu düşünün. Diğer veri noktasının boyutuna kıyasla bu kadar küçük olduğunda neredeyse sonsuzdur. Bunun, bu şekilde büyük ölçüde farklılık gösteren verileri görüntülemek için iyi bir grafik olduğundan emin değilim.

why not? For example, to set a minimum value for coloring (there are 5 different values, 5/360 ', even if it is at least 1 value, it can be displayed in a color slice such as 5%). if the value is 5% (let's assume that it is the minimum value that is color), it is represented in color.

**Comment by ali27001** [comment]
> I think it has to do mainly with the difference in size of the data. If you toggle off the larger data are you able to see the smaller ones with colour? Think about how the doughnut works it is proportional to the size of the specific data compared to the rest of the data. When it is that small compared to size of the other data point it is almost infinitesimal. I'm not sure this is a good graph to display data that differs that vastly in size like this.

why not? For example, to set a minimum value for coloring (there are 5 different values, 5/360 ', even if it is at least 1 value, it can be displayed in a color slice such as 5%). if the value is 5% (let's assume that it is the minimum value that is color), it is represented in color.

**Comment by owen-duncan-snobel** [comment]
> > I think it has to do mainly with the difference in size of the data. If you toggle off the larger data are you able to see the smaller ones with colour? Think about how the doughnut works it is proportional to the size of the specific data compared to the rest of the data. When it is that small compared to size of the other data point it is almost infinitesimal. I'm not sure this is a good graph to display data that differs that vastly in size like this.
> 
> why not? For example, to set a minimum value for coloring (there are 5 different values, 5/360 ', even if it is at least 1 value, it can be displayed in a color slice such as 5%). if the value is 5% (let's assume that it is the minimum value that is color), it is represented in color.

I am not entirely sure what you are getting at. But If I understand you correctly you want there to be a minimum size for each piece to fit. So lets say it is less then 5% you still want it to display on the doughnut as a larger piece then what it is proportionally. I wouldn't know how to go about doing that without manipulating the data.  The Doughnut is working as intended if you find the average size of each index in the data for your example it should be as follows. 

[35.099346678443084, 0.7440777618863219, 50.65462603079086, 13.050044601280963, 0.4519049275987684] (All as percents %) 

Which is representative of the percent it occupies on the doughnut.

**Comment by ali27001** [comment]
I found the problem. Actually it works as expected as you said. borderWidth has been added to make the donut look thinner. Little value started to appear when I removed it.
```
const data = {
  maintainAspectRatio: false,
  responsive: false,
  labels: ["a", "b", "c", "d","e"],
  datasets: [
    {
      data: [35.099346678443084, 0.7440777618863219, 50.65462603079086, 13.050044601280963, 0.4519049275987684],
      backgroundColor: chartColors,
      hoverBackgroundColor: chartColors,
      //borderWidth: 8
    },
  ]
};
```
