### ISSUE TITLE
auto skip // Keep the last element(data)

### ISSUE THREAD

**Issue by AntenehYalew** [reactchartjs/react-chartjs-2#540]
I have relatively longer array data to show on x axis (Line) . The auto skip value varies depending on the screen size.

I wanted to keep the first and last data labels of the dataset displayed at each instance (mobile, tablet or laptop) for the user 

Here is a good example 
 data = 
["6/1/20","6/2/20","6/3/20","6/4/20","6/5/20","6/6/20","6/7/20","6/8/20","6/9/20","6/10/20","6/11/20","6/12/20","6/13/20","6/14/20","6/15/20","6/16/20","6/17/20","6/18/20","6/19/20","6/20/20","6/21/20","6/22/20","6/23/20","6/24/20","6/25/20","6/26/20","6/27/20","6/28/20","6/29/20","6/30/20","7/1/20","7/2/20","7/3/20","7/4/20","7/5/20","7/6/20","7/7/20","7/8/20","7/9/20","7/10/20","7/11/20","7/12/20","7/13/20","7/14/20","7/15/20","7/16/20","7/17/20","7/18/20"]

Screenshots below from three screen sizes show data labels at Xaxis ending on different dates while the actual data ends on 18th JUL.

How can I make sure and tweak the xAxes option to make sure, the first and last (06/01/20 and 07/18/20) are always displayed?

Or what is the best way to do so?

Note:- The dataset increases daily as we go forward as it is capturing a daily info.

![Capture](https://user-images.githubusercontent.com/32172325/87901206-717ef300-ca24-11ea-9ae1-1e105a7387ea.JPG)

**Comment by owen-duncan-snobel** [comment]
Hey, I think this is less of a problem with react-chartjs-2 and more so with Chart js and setting the default ticks. I'd refer to the chart.js documentation. This may help you as somewhere to look.

https://stackoverflow.com/questions/37922518/how-to-set-start-value-as-0-in-chartjs
https://www.chartjs.org/docs/latest/axes/

**Comment by MrHarry2003** [comment]
x: {
        offset: true,
        ticks: {
          autoSkip: true,
          autoSkipPadding: 0,
          color: 'rgb(85, 85, 85)',
          maxRotation: 60,
          minRotation: 60,
          font: {
            size: 12,
          },
        },
        beforeFit: function (axis: ForceAny) {
          const selectedAxis = axis.ticks[axis.ticks.length - 1]
          selectedAxis.value = axis.max // making sure that the x-axis label always contain the last label sent by the backend
          selectedAxis.label = context.chartData.labels[context.chartData.labels.length - 1]
        },
        grid: {
          display: false,
        },
      },
      
      pass this beforeFit function and you problem will be resolved
