### ISSUE TITLE
Render legend items equally on both sides

### ISSUE THREAD

**Issue by g14a** [reactchartjs/react-chartjs-2#548]
Hello! I'm trying to render a pie chart using the library with the following options:

```
<Doughnut
       data={this.state.doughnutData}
            options={{
               responsive: true,
                title: {
                    display: true,
                    text: 'Primary Languages',
                    fontSize: 18,
                    fontColor: '#fff',
                 },
                legend: {
                     display: true,
                     position: 'left',
                     labels: {
                        boxWidth: 20,
                   },
                   align: 'start',
               },
       }}
         width={100}
         height={60}
/>
```
And it renders in the following way:

![Screenshot from 2020-08-03 17-09-05](https://user-images.githubusercontent.com/17702388/89179568-98edc800-d5ad-11ea-807a-6b3abd3ae8f8.png)

Is there any way I can wrap all the legends i.e (the small rectangle boxes) equally on both sides? Right now it looks like 10 of them are on the left and 5 of them on the right.

Thank you in advance :)

**Comment by owen-duncan-snobel** [comment]
Hey, I'd recommend adding a JSFiddle / Code pen with this problem added to it. I think it is a more specific problem to Chart.js as opposed to react-chartjs-2 

I'd suggest maybe try changing the padding but that is just a guess.
[Checkout The Legend Documentation](https://www.chartjs.org/docs/latest/configuration/legend.html#align)
