### ISSUE TITLE
How to achieve anti clockwise rendering in doughtnut cart ?

### ISSUE THREAD

**Issue by naveenvignesh5** [reactchartjs/react-chartjs-2#553]
![Screenshot 2020-09-07 at 12 00 33 PM](https://user-images.githubusercontent.com/19146999/92355445-db9d4580-f101-11ea-94ee-a5c5c42f0f2d.png)

Current options that I am using.

```json
{
   "aspectRatio":1,
   "layout":{
      "padding":{
         "left":0,
         "right":0,
         "top":0,
         "bottom":0
      }
   },
   "responsive":true,
   "cutoutPercentage":88
}
```

**Comment by Arantiryo** [comment]
Hi @naveenvignesh5 👋 

If the issue is still relevant, please check out [a similar one](https://github.com/chartjs/Chart.js/issues/5524) in `chart.js` issues.
