### ISSUE TITLE
Left Align Chart Title

### ISSUE THREAD

**Issue by PrateekGoyal18** [reactchartjs/react-chartjs-2#569]
When I am adding the `align: 'start'` property to title in options it is not taking it.
Is there any problem with it?

**Comment by ryanC1993** [comment]
+1

**Comment by jhonnold** [comment]
I don't see that as an option within the [Chart.js title documentation](https://www.chartjs.org/docs/latest/configuration/title.html#position).

**Comment by Arantiryo** [comment]
I’m closing this issue because it has been inactive for some time.

With `chartjs` version `3.7.1` title positioning options can be found in the link in the answer above.
