### ISSUE TITLE
How I can draw custom Y-axes color full line attachments

### ISSUE THREAD

**Issue by yogitadheeraj** [reactchartjs/react-chartjs-2#576]
I need two Y-axes for custom color  like screen attached.. also text/label will appear same as ..

![image](https://user-images.githubusercontent.com/69039185/97210885-3be86380-17e4-11eb-9d6d-401efcf22424.png)
I am using blow code 

<Line
                    redraw
                    data={{
                      datasets: dataSets,//Dynamic for 2 Line
                    }}
                    options={{
                      fill: false,
                      animation: {
                        animateRotate: true,
                        animateScale: true,
                      },
                      legend: {
                        display: false,
                      },
                      responsive: true,
                      maintainAspectRatio: false,
                      scales: {
                        yAxes: [
                          {
                            gridLines: {
                              color:
                                'red',
                            },
                            display: true,
                            ticks: {
                              autoSkip: false,
                              offset: true,
                              maxRotation: 10,
                              beginAtZero: false,
                              userCallback: label => {
                                if (Math.floor(label) === label) {
                                  return label;
                                }
                                return null;
                              },
                            },
                            position: 'left',
                            scaleLabel: {
                              display: true,
                              labelString: chart?.yUnit,
                              fontStyle: 'bold',
                            },
                          },
                          {
                            ticks: {
                              autoSkip: false,
                              offset: true,
                              maxRotation: 10,
                              beginAtZero: false,
                              padding: 30,
                              userCallback: label => {
                                if (Math.floor(label) === label) {
                                  return label;
                                }
                                return null;
                              },
                            },
                            position: 'right',
                            scaleLabel: {
                              display: true,
                              labelString: chart?.yUnit,
                              fontStyle: 'bold',
                            },
                          },
                        ],
                        xAxes: xAxesArray,// dynamically 
                      },
                    }}
                  />

**Comment by yogitadheeraj** [comment]
Please help me - Its urgent###

**Comment by Arantiryo** [comment]
This is not a react-specific question and should probably be asked in [chartjs repo](https://github.com/chartjs/Chart.js).

To provide you with a starting point, you can check out [patterns and gradients section of chartjs docs](https://www.chartjs.org/docs/latest/general/colors.html#patterns-and-gradients).

And here's a [codesandbox](https://codesandbox.io/s/heuristic-elgamal-fkveqc?file=/App.tsx) to try out different styling options.
