### ISSUE TITLE
How to add text to the instance of “doughnut” and customize “legend” to achieve the same effect as the following picture

### ISSUE THREAD

**Issue by fu1996** [reactchartjs/react-chartjs-2#577]
![UI截图](https://user-images.githubusercontent.com/42232973/97403959-4748a580-1930-11eb-9f2c-8226589465f9.png)

code URL:
[https://github.com/jerairrest/react-chartjs-2/blob/react16/example/src/charts/Doughnut.js](https://github.com/jerairrest/react-chartjs-2/blob/react16/example/src/charts/Doughnut.js)

**Comment by ali27001** [comment]
I have applied a solution like this. You can review https://stackoverflow.com/questions/64892859/how-do-i-dynamically-adjust-the-size-of-the-react-chart-2-pie-chart/64965852#64965852
