### ISSUE TITLE
OnClick Slow

### ISSUE THREAD

**Issue by gabrielMoran23** [reactchartjs/react-chartjs-2#579]
Hello every one, im doing this with my chart component on react

onClick: (e, element) => {
       setIsLoaded(true)
       var ind="";
        if(element.length > 0){
           ind = element[0]._model.label;
        }  
        props.setSelection2FromChart(ind);  
      }

im getting the clicked bar label and sending it to another component, but when i click on the some bar everything  gets  cold .
What should i do 
![carbon](https://user-images.githubusercontent.com/61819174/97460336-46008400-1902-11eb-9259-0412443818a3.png)

**Comment by Arantiryo** [comment]
Hi @gabrielMoran23 👋 

Is the issue still relevant for you with the latest versions of `chart.js` and `react-chartjs-2`?
