### ISSUE TITLE
Each dataset needs a unique key

### ISSUE THREAD

**Issue by bmccorm2** [reactchartjs/react-chartjs-2#580]
Hi all - 

I am getting this warning when i try to render my chart with two datasets.  (just a warning it renders fine)

`[react-chartjs-2] Warning: Each dataset needs a unique key. By default, the "label" property on each dataset is used. Alternatively, you may provide a "datasetKeyProvider" as a prop that returns a unique key. `

I see it says it tries to use label as a key but since i am putting a variable in there it is not guaranteed to be unique.  I saw some solutions where people used Math.random() as a prop passed into the component but when i do this it removes one of my datasets.  Is there a best practice on how to remove this warning?

Thanks!

```
const data = {
    labels: [
      "1MO",
      "3MO",
    ],
    datasets: [
      {
        label: props.chartItems?.[0]["create_date"],
        data: [
          props.chartItems?.[0]["one_month"],
          props.chartItems?.[0]["three_month"],
        ],
        backgroundColor: "red",
        borderColor: "red",
        fill: false,
        lineTension: 0,
        radius: 8,
      },
      {
        label: props.chartItems?.[1]["create_date"],
        data: [
          props.chartItems?.[1]["one_month"],
          props.chartItems?.[1]["three_month"],
        ],
        backgroundColor: "green",
        borderColor: "lightgreen",
        fill: false,
        lineTension: 0,
        radius: 4,
      },
    ],
  };

  return (
    <React.Fragment>
      <Line data={data} />
    </React.Fragment>
  );
```

**Comment by owen-duncan-snobel** [comment]
Hey is there anyway you could create a code pen for this. It sounds like strange behaviour if by passing a prop to be used as the key it would remove a dataset?

**Comment by chiragmansata** [comment]
Hi @bmccorm2 ,
Just add an unique id to your dataset (if your chart data is not having anything, add Math.random()) as in below sample and shall solve your problem
datasets: [
      {
		id: Math.random(),

        label: props.chartItems?.[0]["create_date"],
        data: [
          props.chartItems?.[0]["one_month"],
          props.chartItems?.[0]["three_month"],
        ],
        backgroundColor: "red",
        borderColor: "red",
        fill: false,
        lineTension: 0,
        radius: 8,
      },
]
It works at my end, do share if it worked at your side.

**Comment by dangreen** [comment]
For react-chartjs-2@v4, we have [documentation for that](https://react-chartjs-2.netlify.app/docs/working-with-datasets).
