### ISSUE TITLE
Dependency conflict with latest version of react (17.0.1)

### ISSUE THREAD

**Issue by JossWritesCode** [reactchartjs/react-chartjs-2#582]
I have React 17.0.1. When I try to add react-chart-js-2 to my dependencies I get a conflict.
<img width="775" alt="Screen Shot 2020-11-04 at 9 40 44 AM" src="https://user-images.githubusercontent.com/31298759/98124950-d3ebea00-1e81-11eb-88b2-0fcc7627bf70.png">

**Comment by jhonnold** [comment]
Thank for bringing this up, it is currently being worked on in #585

**Comment by jerairrest** [comment]
This has been deployed under 2.11.0
