### ISSUE TITLE
Is there a dotted line style option for points in a graph/scatter chart?

### ISSUE THREAD

**Issue by Kobeboy15** [reactchartjs/react-chartjs-2#586]
So I'm working on a Map type of system that pinpoints things. I decided to use the Chartjs scatterplot as a way pinpoint things on a map through coordinates.

One of the designs I'm struggling to achieve is something like this...

![image](https://user-images.githubusercontent.com/23691843/98218699-09c6c680-1f87-11eb-88e6-200ba27aa6b1.png)

What I have so far is something like this...

![image](https://user-images.githubusercontent.com/23691843/98218790-28c55880-1f87-11eb-95f3-fa3e94f7f9fa.png)

I'm wondering if its possible to style the type of border like making it dashes or dots, aside from just the width and color?

**Comment by jhonnold** [comment]
[The documentation](https://www.chartjs.org/docs/latest/charts/line.html#dataset-properties) seems to have some values that associate with a dashed border.
