### ISSUE TITLE
The docs website is not found Error

### ISSUE THREAD

**Issue by lifeeric** [reactchartjs/react-chartjs-2#591]
when browsing the docs website it shows a 404 error. kindly fix it as soon as possible!

**Comment by iMojtaba** [comment]
Hi,
Use this url:
https://reactchartjs.github.io/react-chartjs-2/

**Comment by jerairrest** [comment]
The page should be updated to http://reactchartjs.github.io/react-chartjs-2/#/ now

Let me know if you have troubles still
