### ISSUE TITLE
Data Not loading in Line Chart , Loading when double clicking on legend

### ISSUE THREAD

**Issue by litelo** [reactchartjs/react-chartjs-2#607]
So I am using Line plot  for displaying some data but it is showing only first element of data array  but when I click on legend and reclick on it then only it loads all data. Can someone please help. 
In the below image i click two times one "votes legend" then all data loads but currently it is showing only one.
Here is my config for Chart

 <Line data={{
                labels: this.state.labels,
                datasets: [
                    {
                        label: '# of Votes',
                        data: this.state.data,
                        fill: false,
                         backgroundColor: 'rgba(75,192,192,1)',
                        pointHoverRadius: 10,
                        borderColor: '#383d45',
                        borderWidth:3,
                        radius:5,
                        borderCapStyle: 'butt'
                        
                    },
                ]
                
            }} 
     width={2} height={1} />
<img width="1007" alt="Screenshot 2020-12-27 at 8 17 54 PM" src="https://user-images.githubusercontent.com/27894559/103173394-c0a53b80-4880-11eb-8c7b-214d57930be6.png">

**Comment by owen-duncan-snobel** [comment]
Hey, sorry for the late reply. Could you attach perhaps a code pen of this / the data array itself so I can try to replicate this to see the expected result. I feel like it has something to do with when the data is been passed and the components state updating but cannot be positive.

**Comment by dangreen** [comment]
Closed due to inactivity
