### ISSUE TITLE
Options are not applied

### ISSUE THREAD

**Issue by nihil-pro** [reactchartjs/react-chartjs-2#608]
I have a problem with options.
My code:
`
  <>
        {charts && charts.map((chart, index) => {
            return (
                <div className="row border-bottom pt-5 pb-5" key={index}>
                    <div class="col-12">
                        <code>chart.statistic.options</code>
                        <pre>
                            {JSON.stringify(chart.statistic.options)}
                        </pre>
                    </div>
                    <div className="col-9">
                        <Line data={chart.statistic.data} options={chart.statistic.options} height={100} />
                    </div>
                </div>
            )
        })}
 </>
`
result:  
<img width="1437" alt="Screenshot 2021-01-08 at 12 56 36" src="https://user-images.githubusercontent.com/39807476/104003087-03d1a980-51b3-11eb-8911-4b91dd381cb4.png">

**Comment by cristihandev** [comment]
Hi @nihil-pro , I found a work around for now and its basically like this:

`
import { Line, defaults } from 'react-chartjs-2';

defaults.global.legend.labels.fontSize = 14;
`

you can change other default options as well  like color and fontFamily

**Comment by nihil-pro** [comment]
This method only works for top labels, but anyway thanks
<img width="1085" alt="Screenshot 2021-01-10 at 11 58 30" src="https://user-images.githubusercontent.com/39807476/104118576-3efee480-533b-11eb-8bee-ccc8edc2b559.png">

**Comment by chiragmansata** [comment]
Hi @nihil-pro,
Actually you need change the options of your xaxes: ticks section to make this work.
Here's an sample chartOptions object for reference:
chartOptions: {
                scales: {
                    xAxes: [{ id: 'xaxis1', type: 'linear',
                        ticks: {autoSkip: false,fontSize: 20}}],
                },
}
It works at my end, do share if it worked for you as well.
