### ISSUE TITLE
How can i hide the y-axis data as in the image below?

### ISSUE THREAD

**Issue by lucasfelixc** [reactchartjs/react-chartjs-2#609]
I would like the value of the line to be shown only on the **hover**, that is, hide the information on the y axis. **In addition, I also wanted to hide the lines inside the graph.**
![Captura de tela de 2021-01-12 10-30-38](https://user-images.githubusercontent.com/64923932/104320775-84e5b500-54c1-11eb-9a3a-1235139d2737.png)

**Comment by owen-duncan-snobel** [comment]
Do you have a code pen for this it would make it easier to try and help.

**Comment by lucasfelixc** [comment]
In fact I was wondering if there is any predetermined option that interferes with the axes.

**Comment by lucasfelixc** [comment]
As opções do meu gráfico são essas:
```
export const data = {
  labels: [
    'Jan',
    'Fev',
    'Mar',
    'Abr',
    'Mai',
    'Jun',
    'Ago',
    'Set',
    'Out',
    'Nov',
    'Dez'
  ],
  datasets: [
    {
      label: 'Gastos',
      fill: false,
      lineTension: 0.4,
      backgroundColor: 'rgba(75,192,192,0.4)',
      borderColor: 'rgba(71, 51, 166, 1)',
      borderWidth: 5,
      borderCapStyle: 'butt',
      borderDash: [],
      borderDashOffset: 0.1,
      borderJoinStyle: 'miter',
      pointBorderColor: 'rgba(71, 51, 166, 1)',
      pointBackgroundColor: '#fff',
      pointBorderWidth: 2,
      pointHoverRadius: 5,
      pointHoverBackgroundColor: 'rgba(71, 51, 166, 1)',
      pointHoverBorderColor: 'rgba(220,220,220,1)',
      pointHoverBorderWidth: 2,
      pointRadius: 1,
      pointHitRadius: 10,
      data: monthlySpendingTotal
    }
  ]
}
```

**Comment by lucasfelixc** [comment]
The options on my chart are these:
```
export const data = {
  labels: [
    'Jan',
    'Fev',
    'Mar',
    'Abr',
    'Mai',
    'Jun',
    'Ago',
    'Set',
    'Out',
    'Nov',
    'Dez'
  ],
  datasets: [
    {
      label: 'Gastos',
      fill: false,
      lineTension: 0.4,
      backgroundColor: 'rgba(75,192,192,0.4)',
      borderColor: 'rgba(71, 51, 166, 1)',
      borderWidth: 5,
      borderCapStyle: 'butt',
      borderDash: [],
      borderDashOffset: 0.1,
      borderJoinStyle: 'miter',
      pointBorderColor: 'rgba(71, 51, 166, 1)',
      pointBackgroundColor: '#fff',
      pointBorderWidth: 2,
      pointHoverRadius: 5,
      pointHoverBackgroundColor: 'rgba(71, 51, 166, 1)',
      pointHoverBorderColor: 'rgba(220,220,220,1)',
      pointHoverBorderWidth: 2,
      pointRadius: 1,
      pointHitRadius: 10,
      data: monthlySpendingTotal
    }
  ]
}
```

**Comment by lucasfelixc** [comment]
And they are generating this graph for me:
![Captura de tela de 2021-01-14 12-42-38](https://user-images.githubusercontent.com/64923932/104614059-a59b3f80-5666-11eb-8e33-cf18b1747867.png)

**Comment by lucasfelixc** [comment]
But I wanted to take this data off the y axis

**Comment by owen-duncan-snobel** [comment]
> But I wanted to take this data off the y axis

If you mean to remove the labels on the y axis, you can do the following. For the component you need to add an options prop

`export const options = {
    scales: {
     yAxes: [{
         ticks: {
            display: false
          }
      }]
  }
}


<Line data={data} options={options} />


`

**Comment by lucasfelixc** [comment]
Very good, it worked. Do you know how to get those dark lines out of the background?

**Comment by owen-duncan-snobel** [comment]
> Very good, it worked. Do you know how to get those dark lines out of the background?

```
var options = {
    scales: {
        xAxes: [{
            gridLines: {
                display:false
            }
        }],
        yAxes: [{
            gridLines: {
                display:false
            }   
        }]
    }
}
```

**Comment by lucasfelixc** [comment]
And how can I edit the chart extensions? like, height, width...

**Comment by owen-duncan-snobel** [comment]
> And how can I edit the chart extensions? like, height, width...

If you are looking to change the height and width of the grid you can set it to automatically fill the space by default or pass it as a prop with any of the following patterns.
```
<Line data={data} options={options} width={400} />
<Line data={data} options={options} height={200} />
<Line data={data} options={options} width={400}  height={400} />
```

**Comment by lucasfelixc** [comment]
I want to edit the dimensions because if I leave it automatic, it goes beyond the maximum seen and looks like this:
![Captura de tela de 2021-01-14 17-47-08](https://user-images.githubusercontent.com/64923932/104647490-ba8cc880-5690-11eb-9591-097d942804ee.png)

**Comment by lucasfelixc** [comment]
The month of December was under the scroll bar

**Comment by owen-duncan-snobel** [comment]
> I want to edit the dimensions because if I leave it automatic, it goes beyond the maximum seen and looks like this:
> ![Captura de tela de 2021-01-14 17-47-08](https://user-images.githubusercontent.com/64923932/104647490-ba8cc880-5690-11eb-9591-097d942804ee.png)

You are going to have to create a codepen / codesandbox. Most of these issues aren't specific to react-chartjs-2 but to chart.js and how to style graphs etc. 

https://www.chartjs.org/docs/latest/

I'd look at the size of the container that is holding the graph component and increasing its size and seeing if that fixes. Otherwise create a codepen and I can try to help you further.

**Comment by tushartiwari7** [comment]
> > But I wanted to take this data off the y axis
> 
> If you mean to remove the labels on the y axis, you can do the following. For the component you need to add an options prop
> 
> ```
> 
> export const options = {
>     scales: {
>      yAxes: [{
>          ticks: {
>             display: false
>           }
>       }]
>   }
> }
> <Line data={data} options={options} />
> ```
> 
> or you can also try
> 
> ```
> export const options = {
>     scales: {
>      yAxes: [{
>             display: false
>       }]
>   }
> }
> ```

It doesn't worked for me, Are there any new changes?

**Comment by vettloffah** [comment]
Passing those options don't hide the axis labels for me

**Comment by vettloffah** [comment]
Update: if the above don't work for you, try:

`const options = {
    scales: {
     y: { display: false }
  }
}`

**Comment by vivek-wednesday** [comment]
@vettloffah solution worked for me.

**Comment by itsanishmv** [comment]
> > But I wanted to take this data off the y axis
> 
> If you mean to remove the labels on the y axis, you can do the following. For the component you need to add an options prop
> 
> ```
> 
> export const options = {
>     scales: {
>      yAxes: [{
>          ticks: {
>             display: false
>           }
>       }]
>   }
> }
> <Line data={data} options={options} />
> ```
> 
> or you can also try
> 
> ```
> export const options = {
>     scales: {
>      yAxes: [{
>             display: false
>       }]
>   }
> }
> ``change to `
const options = {
  scales: {
    y: {
      ticks: {
        display: false,
      },
    },
  },
};

**Comment by itsanishmv** [comment]
> > > But I wanted to take this data off the y axis
> > 
> > 
> > If you mean to remove the labels on the y axis, you can do the following. For the component you need to add an options prop
> > ```
> > 
> > export const options = {
> >     scales: {
> >      yAxes: [{
> >          ticks: {
> >             display: false
> >           }
> >       }]
> >   }
> > }
> > <Line data={data} options={options} />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or you can also try
> > ```
> > export const options = {
> >     scales: {
> >      yAxes: [{
> >             display: false
> >       }]
> >   }
> > }
> > ```
> 
> It doesn't worked for me, Are there any new changes?

const options = {
  scales: {
    y: {
      ticks: {
        display: false,
      },
    },
  },
};

this worked for me 

>

**Comment by itsanishmv** [comment]
> > > But I wanted to take this data off the y axis
> > 
> > 
> > If you mean to remove the labels on the y axis, you can do the following. For the component you need to add an options prop
> > ```
> > 
> > export const options = {
> >     scales: {
> >      yAxes: [{
> >          ticks: {
> >             display: false
> >           }
> >       }]
> >   }
> > }
> > <Line data={data} options={options} />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or you can also try
> > ```
> > export const options = {
> >     scales: {
> >      yAxes: [{
> >             display: false
> >       }]
> >   }
> > }
> > ```
> 
> It doesn't worked for me, Are there any new changes?

Updated code 
`const options = {
  scales: {
    y: {
      ticks: {
        display: false,
      },
    },
  },
};`
