### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by dluc** [reactchartjs/react-chartjs-2#618]
Could you make "chart.js" an internal dependency, so instead of

```
yarn add react-chartjs-2 chart.js
```

one can simply do

```
yarn add react-chartjs-2
```

Thanks

**Comment by dangreen** [comment]
@dluc Hi. chart.js is peer dependency because the end-user should decide which version of chart.js he wants to use.

**Comment by dluc** [comment]
@dangreen for people needing a specific version you could suggest using "resolutions" or a different installation approach. My guess is that the majority of users will just want to install react-chartjs-2 without worrying about the version, i.e. hoping they get the latest and greatest
