### ISSUE TITLE
Line chart doesn't display when I set min and max ticks in time scale

### ISSUE THREAD

**Issue by Clish254** [reactchartjs/react-chartjs-2#621]
I'm trying to plot a line chart with time series data but the chart breaks when I add `min` and `max` values for ticks.
Here is my configuration for the x-axis which has the time data
```Javascript
      xAxes: [
        {
          type: 'time',
          gridLines: {
            display: false
          },
          time: {
            unit: 'minute',
            unitStepSize: 60
          },
          ticks: {
            min: startDate.getTime(),
            max: stopDate.getTime()
          },
          scaleLabel: {
            display: true,
            labelString: 'time'
          }
        }
      ],
```
The chart works well when I comment out these three lines 
```Javascript
  ticks: {
            min: startDate.getTime(),
            max: stopDate.getTime()
          },
```
Otherwise it just doesn't plot the ticks and I don't see any errors in the console. However, x-axis values are spread according to the `min` and `max` ticks that I set.

**Comment by owen-duncan-snobel** [comment]
Hey, this is more of an issue with chart.js as opposed to react-chartjs-2 the wrapper.

But I would refer you to this 

```
options: {
    scales: {
        xAxes: [{
            type: "time",
            time: {
                min: 1471174953000,
                max: 1473853353000
            }
        }]
    }
}
```
 https://stackoverflow.com/a/39535213

As well as insure that the version of chart.js is still under 2.* and not updated to 3
as for version 3 their have been updated to ticks.min and ticks.max 
https://www.chartjs.org/docs/next/getting-started/v3-migration/#options

**Comment by Clish254** [comment]
> Hey, this is more of an issue with chart.js as opposed to react-chartjs-2 the wrapper.
> 
> But I would refer you to this
> 
> ```
> options: {
>     scales: {
>         xAxes: [{
>             type: "time",
>             time: {
>                 min: 1471174953000,
>                 max: 1473853353000
>             }
>         }]
>     }
> }
> ```
> 
> https://stackoverflow.com/a/39535213
> 
> As well as insure that the version of chart.js is still under 2.* and not updated to 3
> as for version 3 their have been updates to ticks.min and ticks.max
> https://www.chartjs.org/docs/next/getting-started/v3-migration/#options

I tried the proposed solutions, still doesn't work. I'll ask on chartjs's github. Thank you.

**Comment by Arantiryo** [comment]
I’m closing this issue because it has been inactive for a few months.
