### ISSUE TITLE
Forecast to include heatmap chart

### ISSUE THREAD

**Issue by leosilva-dev** [reactchartjs/react-chartjs-2#622]
Hello, do you have a forecast do include this type of chart? (heatmap)

See an example here: https://apexcharts.com/wp-content/uploads/2018/05/heatmap-mutiple-series.svg

**Comment by owen-duncan-snobel** [comment]
Hey,  

So this repository is just a wrapper for chart.js for react. I went and looked through the examples on the chart.js documentation and they don't have any built in heatmaps charts. I would recommend trying to find another library as it currently doesn't have functionality in chart.js let alone the react wrapper. 

I found some added chart functionality that people have externally developer maybe one of these might help.
[https://github.com/chartjs/awesome](https://github.com/chartjs/awesome)

**Comment by majulahsingapuri** [comment]
Hi I'm trying to use the chart matrix library mentioned in one of my react projects. I cant seem to get the chart to render the data on initial load but it renders correctly when i force a typescript error and undo the change (on my local machine at least. it doesnt happen in the sandbox).

Similar code works for my candlestick chart using [chartjs-financial](https://github.com/chartjs/chartjs-chart-financial). See the [codesandbox](https://codesandbox.io/s/react-typescript-forked-kffrov?file=/src/App.tsx) for implementation. I have duplicated the [typedCharts.tsx](https://github.com/reactchartjs/react-chartjs-2/blob/master/src/typedCharts.tsx) to get the chart to work.
