### ISSUE TITLE
How can I display the values of a pie chart as labels, off the pie itself?

### ISSUE THREAD

**Issue by sebzapata** [reactchartjs/react-chartjs-2#624]
Hi,
I have a pie chart which has 7 segments. I want to display the value that each segment represents as a label that is pointing to the segment, rather than directly on the segment.
I have used `chartjs-plugin-datalabels` and have managed to get the labels onto the chart as can be seen here: 
![image](https://user-images.githubusercontent.com/33514373/110225552-7a063a00-7ede-11eb-8eea-ecd28265b56b.png)

I would prefer to have them brought out slightly, much more like here: ![image](https://user-images.githubusercontent.com/33514373/110225336-ad47c980-7edc-11eb-9ece-7aad55212d19.png)

All help is much appreciated.
Thanks

**Comment by Arantiryo** [comment]
Hi @sebzapata 👋 

Please check out [chartjs-plugin-datalabels docs](https://chartjs-plugin-datalabels.netlify.app/guide/positioning.html) on positioning. Specifically sections on `Anchoring` and `Alignment and Offset`.

And in the `Samples` section they have a great [example of a polar chart](https://chartjs-plugin-datalabels.netlify.app/samples/charts/polar.html) for trying out different options.

Hope that helps!
