### ISSUE TITLE
Locale not being set under options.locale

### ISSUE THREAD

**Issue by daniel-moya** [reactchartjs/react-chartjs-2#627]
When setting the options for my chart, i want to see the numbers formatted accordingly to my locale code.

Instead of having `1000.23` i want to see `1.000,23`

So, i setted like this 

``` javascript
const options = {
		...
		maintainAspectRatio: true,
		legend: {
			display: false,
		},
		locale: 'nl-NL',
}

but the numbers appear with the same `1000.23`

**Comment by Arantiryo** [comment]
Hi @daniel-moya 👋 

I'm closing this issue because It looks like it has been fixed in a newer version. Here's an [example](https://codesandbox.io/s/awesome-mendel-eri2y5) with 
it working as expected.

If you still experience this behavior please feel free to comment and I'll reopen it.

Thanks!
