### ISSUE TITLE
How can I show the tooltip all the time?

### ISSUE THREAD

**Issue by BrunoSette** [reactchartjs/react-chartjs-2#628]
I need to print a pola area showing the data with all the tooltips at the same time.

Is there a option to do that?

**Comment by BrunoSette** [comment]
I did set the tootltip intersect option to true. It doesn't desapear anymore, but I see them all together. 
![Captura de Tela 2021-03-19 às 13 28 27](https://user-images.githubusercontent.com/5710346/111812646-18b77100-88b7-11eb-9c4e-67a0ff40d839.png)

**Comment by Souvikray** [comment]
Did you find any solution to this?

**Comment by RudrikaJnext** [comment]
Did you found any solution for this @BrunoSette ?

**Comment by Arantiryo** [comment]
Please take a look at a similar issue and a [proposed solution](https://github.com/reactchartjs/react-chartjs-2/issues/682#issuecomment-1113552842).
