### ISSUE TITLE
Compatibility with Chart.js 3

### ISSUE THREAD

**Issue by phiresky** [reactchartjs/react-chartjs-2#634]
Chart.js 3 changes some things, specifically it no longer exports the Chart class as a default export, so react-chartjs-2 fails to start with 

```
Uncaught TypeError: _chart.default is undefined
    <anonymous> index.js:643
```

Migration guide: https://www.chartjs.org/docs/latest/getting-started/v3-migration.html

**Comment by yuan9090** [comment]
I fork the repository, and merge [#599 3.x Migration](https://github.com/reactchartjs/react-chartjs-2/pull/599).
Try this: [@iftek/react-chartjs-3](https://github.com/yuan9090/react-chartjs-3)

**Comment by kenbankspeng** [comment]
@yuan9090 will @iftek/react-chartjs-3 be published to npm? I don't see any movement on the [3.0 release project](https://github.com/reactchartjs/react-chartjs-2/projects/2) for react-charts-2.

**Comment by jerairrest** [comment]
We definitely have lost traction of chartV3. :( Sorry folks, I haven't been keeping up on updates

**Comment by kenbankspeng** [comment]
Now wondering if energies would be better put towards https://github.com/xr0master/chartjs-react

**Comment by yuan9090** [comment]
@kenbankspeng Yes, try `npm i @iftek/react-chartjs-3`

**Comment by YakovlevCoded** [comment]
Hi! We have updated the wrapper. Try to use the latest version ^3.0.2 with Chart.js ^3.x.

**Comment by arheinjohnson** [comment]
I'm using react-chartjs-2@3.0.3 and chartjs@3.2.1, but I can't get options.scales.y.ticks options to work at all. Anyone else still have problems with chartjs@3.x?
