### ISSUE TITLE
A bar chart with one big value and others are much smaller - on small screens all smaller values look like a zero (an empty bar)

### ISSUE THREAD

**Issue by ArielArielArielAriel** [reactchartjs/react-chartjs-2#638]
Code:
https://stackblitz.com/edit/react-dlpdeo
I understand it needs to be proportional, but it doesn't make sense it looks like a zero, although it's not. 

![image](https://user-images.githubusercontent.com/41476930/114062943-c14a6680-98a0-11eb-8fdb-feb5f3de2b1f.png)

Maybe is there a chart option to prevent it?

**Comment by Arantiryo** [comment]
Hey @ArielArielArielAriel 👋 

You can set property `minBarLength` to ensure that bars have a minimum length in pixels.

```typescript
datasets: [{
    label: 'My First Dataset',
    data: [1, 59, 80, 81, 56, 55, 40],
    ...
    minBarLength: 50,
  }]
```

Hope that helps!
