### ISSUE TITLE
How I can show the percentage value in doughnut chart?

### ISSUE THREAD

**Issue by MaiUbeid** [reactchartjs/react-chartjs-2#643]
How I can show the percentage value in the doughnut chart?
![لقطة الشاشة 2021-04-18 002909](https://user-images.githubusercontent.com/20427049/115127321-47238b80-9fde-11eb-9c35-6368a5e1c438.png)

**Comment by Zoniaina** [comment]
Think this can help `https://chartjs-plugin-datalabels.netlify.app/`

**Comment by Daniel-Raz-Supersmart** [comment]
> How I can show the percentage value in the doughnut chart? ![لقطة الشاشة 2021-04-18 002909](https://user-images.githubusercontent.com/20427049/115127321-47238b80-9fde-11eb-9c35-6368a5e1c438.png)

Hi, how do you do this appearance for the chart?

**Comment by humarkx** [comment]
@MaiUbeid w

> How I can show the percentage value in the doughnut chart? ![لقطة الشاشة 2021-04-18 002909](https://user-images.githubusercontent.com/20427049/115127321-47238b80-9fde-11eb-9c35-6368a5e1c438.png)

Would you be able to share how did you achieve that rounded doughnut it the correct overlap.

I am trying to achieve exactly what you have there. Thanks

**Comment by Daniel-Raz-Supersmart** [comment]
> 

join to your question and will be glad if you find the answer and let me know

**Comment by flymauntains** [comment]
To show percent values, use `npm install chart.js chartjs-plugin-datalabels`

**Comment by flymauntains** [comment]
```
import React from "react";
import { Doughnut } from "react-chartjs-2";
import { Chart, ArcElement } from "chart.js";
import ChartDataLabels from "chartjs-plugin-datalabels";

Chart.register(ArcElement, ChartDataLabels);

export default function TestChart() {
  const data = {
    datasets: [
      {
        data: [55, 10, 30, 5],
        backgroundColor: ["#8D53BB", "#BF7BF5", "#311746", "#5E3280"],
      },
    ],
  };

  const options = {
    plugins: {
      datalabels: {
        display: true,
        color: '#FF0000',
        formatter: (value, context) => {
          console.log('Test Data Index:', context.dataIndex);
          console.log('Test Value:', value);
          const staticLabels = [55, 10, 30, 5];
          return staticLabels[context.dataIndex];
        },
        anchor: 'center',
        align: 'center',
        font: {
          weight: 'bold',
          size: 16,
        },
      },
    },
  };

  return <Doughnut data={data} options={options} />;
}

```
