### ISSUE TITLE
How to export Chartjs v3 to base64?

### ISSUE THREAD

**Issue by ubinatus** [reactchartjs/react-chartjs-2#646]
On the previous react-chartjs-2 v2.x (chartjs v2), we could access directly to the `chartInstance` of any chart using refs. Whenever we wanted to export the image to base64, we called the `chartInstance.toBase64Image()` method.

Since the update to react-chartjs-2 v3.x there is no `chartInstance`. How can we access the old `toBase64Image` method?

Thanks :)

**Comment by ubinatus** [comment]
My bad! 🙃 

For anyone looking the answer, there is no`chartInstance`. If you wish to export the chart to base64, just call `toBase64Image` directly with the created `ref`.

Example:
Given the following ref:

```
        <Line
          ref={node => this.someRefName = node}
          {...restOfProps}
        />
```


Just call the method directly:
`
const base64Image = this.someRefName.toBase64Image();
`

**Comment by charlesanim499** [comment]
can you call this method outside of the child chart component?
