### ISSUE TITLE
How to get onClick Event for a Label in Chart.js [React]?

### ISSUE THREAD

**Issue by rahulrsingh09** [reactchartjs/react-chartjs-2#654]
I have a Radar chart with labels, I want to have a click event on the Label of the Radar chart but the element always returns null. I have looked at other Stack over flow questions notedly 
[**1**](https://stackoverflow.com/a/65822884/7805613) and this [**2**](https://stackoverflow.com/questions/37028924/how-to-add-onclick-event-on-labels-in-chart-js-v2-0). one talks about doing it in vanilla JS approach and other one just is not working for me , Can some one point me to what am i doing wrong ? 

**End goal** -> I want to get the label which is clicked and add a strike through toggle to that label so that i can toggle the data point on and off in the radar chart. 

My Implementation 

    class Chart extends Component {
      constructor(props) {
        super(props);
        this.state = {
          chartData: props.chartData
        };
      }
      render() {
        return (
          <div className="chart">
            <Radar
              data={this.state.chartData}
              options={{
                title: {
                  display: true,
                  text: "Testing",
                  fontSize: 25
                },
                legend: {
                  display: true,
                  position: "right"
                },
                onClick: function(evt, element) {
                  // onClickNot working element null
                  console.log(evt, element);
                  if (element.length > 0) {
                    console.log(element, element[0]._datasetInde);
                    // you can also get dataset of your selected element
                    console.log(data.datasets[element[0]._datasetIndex]);
                  }
                }
              }}
            />
          </div>
        );
      }
    }

[**Link to the sample imp**](https://stackblitz.com/edit/react-chartjs-app-wtgbm9?file=components%2FChart.js)

**Comment by rahulrsingh09** [comment]
Figured it out in SO

**Comment by keunghk** [comment]
> Figured it out in SO

Could you please tell me how to do it ?

**Comment by tynarbekov** [comment]
> > Figured it out in SO
> 
> Could you please tell me how to do it ?

`
import { Bar } from 'react-chartjs-2'
import { Chart } from 'chart.js'


const BarChart = () => {
  const chartRef = useRef<HTMLCanvasElement>(null)
  ...
  return ( <Bar
    type='horizontalBar'
    data={chartData}
    ref={chartRef}
    getElementAtEvent={(i: any, event: any) => {
      if (chartRef.current) {
      const chart = Chart.getChart(chartRef.current)
      const clickedElements = chart!.getElementsAtEventForMode(event, 'y',{axis: 'x', intersect: false}, true)
      if (clickedElements.length > 0) {
        console.log(clickedElements[0].index) // Here clicked label | data index
      }
     }
    }}
    options={options}/>
  )
}
`

**Comment by amresha** [comment]
@tynarbekov can you please guide how should I implement this with a non-typescript file as it shows an error that type annotations can only be used in TypeScript files.

**Comment by tynarbekov** [comment]
> @tynarbekov can you please guide how should I implement this with a non-typescript file as it shows an error that type annotations can only be used in TypeScript files.

What annotation are you talking about?

**Comment by amresha** [comment]
> > @tynarbekov can you please guide how should I implement this with a non-typescript file as it shows an error that type annotations can only be used in TypeScript files.
> 
> What annotation are you talking about?

On below lines
**(i: any, event: any)
chart!.getElementsAtEventForMode(event, 'y',{axis: 'x', intersect: false}, true)**

I have posted my query and screenshot here https://github.com/reactchartjs/react-chartjs-2/issues/946 can you please check and guide.

**Comment by kritikjain9** [comment]
@tynarbekov Thanks for sharing!

But I am getting this error while trying to implement the same
my code 

`const chartRef = useRef<HTMLCanvasElement>(null);`

`return (
<Bar
              data={ticketData}
              options={graphOptions}
              ref={chartRef}
              getElementAtEvent={(i: any, event: any) => {
                if (chartRef.current) {
                  const chart = Chart.getChart(chartRef.current);
                  const clickedElements = chart!.getElementsAtEventForMode(
                    event,
                    "y",
                    { axis: "x", intersect: false },
                    true
                  );
                  if (clickedElements.length > 0) {
                    console.log(clickedElements[0].index); // Here clicked label | data index
                  }
                }
              }}
            />
)`


Error : 

> Type 'RefObject<HTMLCanvasElement>' is not assignable to type 'ForwardedRef<ChartJSOrUndefined<"bar", number[], unknown>> | undefined'.
  Type 'RefObject<HTMLCanvasElement>' is not assignable to type 'MutableRefObject<ChartJSOrUndefined<"bar", number[], unknown> | null>'.
    Types of property 'current' are incompatible.



![image](https://user-images.githubusercontent.com/55712009/200231686-4a28eb19-c4bb-4d39-a81b-97a2366cbcee.png)

**Comment by mma-altow** [comment]
I found this old thread by google. If someone else comes here. There is a working example with the current version
chart.js 4.0.0 
react-chart-js-2 5.0.0

`https://codesandbox.io/s/reactchartjs-react-chartjs-2-events-32ex0`

**Comment by muhammadharis1212** [comment]
> ref={chartRef}

const chartRef = useRef<ChartJS<"radar">>(null);

You can add different chart name as string inside <>. This solved my error.
