### ISSUE TITLE
Specifying any chart item type when it already knows it's type. Typescript

### ISSUE THREAD

**Issue by atliunnsteins** [reactchartjs/react-chartjs-2#656]
Using Typescript with @types/chart.js 2.9.32 and react-chartjs-2 3.0.3

My Pie component(chart) has required attribute type, but it already knows what it is. Why is it required?

From this code:
```
const TestingChart: React.FC<TestingChartProps> = () => {
  return (
    <div>
      <Pie data={data} options={options}/>
    </div>
  );
}
```

Error code:
TS2741: Property 'type' is missing in type '{ data: { labels: string[]; datasets: { label: string; fill: boolean; lineTension: number; backgroundColor: string; borderColor: string; borderCapStyle: string; borderDash: never[]; borderDashOffset: number; ... 10 more ...; data: number[]; }[]; }; options: { ...; }; }' but required in type 'Props'. 

FIX - all the same
```
const TestingChart: React.FC<TestingChartProps> = () => {
  return (
    <div>
      <Pie type='DOESNOTMATTER' data={data} options={options}/>
    </div>
  );
}

const TestingChart: React.FC<TestingChartProps> = () => {
  return (
    <div>
      <Pie type='line' data={data} options={options}/>
    </div>
  );
}

const TestingChart: React.FC<TestingChartProps> = () => {
  return (
    <div>
      <Pie type={pie} data={data} options={options}/>
    </div>
  );
}
```

**Comment by YakovlevCoded** [comment]
#659

**Comment by riichinomics** [comment]
Are typing working for you @aunnsteinsson? I'm using the same package version as you, but besides this error around type I'm also not getting any type safety around the props of chart components.

**Comment by peterbe** [comment]
Pretty sure this can be closed now. You no longer need to specify the `type` prop.
