### ISSUE TITLE
Doughnut cutoutPercentage & tooltip disabled not working on Next.js project

### ISSUE THREAD

**Issue by albanSR0309** [reactchartjs/react-chartjs-2#660]
I have this code in my next.js project where I am using the react-chartjs-2 library to create charts. the cutoutPercentage property in chart.js theoretically makes the donut chart thinner, but in next.js it doesn't work. Does anyone know if I am misplacing the property or is it an issue?

PD: the option to deactivate the tooltip does not work either I have tried it as you will see in the code example as with the `tooltips: disabled` and `tooltips: false`

```█[javascript]
import React from "react";
import { Doughnut  } from 'react-chartjs-2';

const data = {
  datasets: [
    {
      data: [15, 12, 40, 30],
      backgroundColor: ["#c5e99b", "#8fbc94", "#548687", "#56445d"],
    },
  ],
};

const Options = {
    tooltips: {
      enabled: false,
    },
    cutoutPercentage: 70,
    responsive: true,
    maintainAspectRatio: false,
}

export default () => (
    <Doughnut 
      data={data}
      width={290}
      height={290}
      options={Options}
    />
);

█```

**Comment by YakovlevCoded** [comment]
@albanSR0309 
Hi! You can see more about tooltip configuration [here](https://www.chartjs.org/docs/latest/configuration/tooltip.html#tooltip-configuration). In short, you need to use options.plugins.tooltip

**Comment by YakovlevCoded** [comment]
[Doughnut cutoutPercentage was renamed to cutoutand accepts pixels as numer and percent as string ending with %.](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html#specific-changes)

**Comment by albanSR0309** [comment]
thanks
