### ISSUE TITLE
Options Legend and fonts doesn't work 

### ISSUE THREAD

**Issue by dalelantowork** [reactchartjs/react-chartjs-2#663]
I have these options script inside the app : 

const options = {
        maintainAspectRatio: false,
        legend: {
            display: false,
            labels: {
                fontColor: "white",
                fontSize: 20,
            }
        },
        scales: {
            yAxes: [
            {
                ticks: {
                    fontColor: "white",
                    stepSize: 1,
                    beginAtZero: true,
                },
            },
            ],
        },
        };
 
And here is the Line Chart I use 

<Line 
                data={data} 
                options={options}
                width={100}
            	height={50}
                className={classes.lineChart}/>

But nothing changes

**Comment by dalelantowork** [comment]
I've been searcjhing for answers for quite a while and it seems that the issue is on version 3.0.3 , the options don't work on it and when i try to install older versions like 2.9.4  it always says to me peer depency error, and whenever i try to force install it i get this other error : module not found can't resolve chart.js/auto

**Comment by YakovlevCoded** [comment]
@dalelantowork Hi! If you want to install an older version of Chart.js, like 2.9.4, you need to use the old version of the react-chartjs-2, like 2.11.1.

**Comment by YakovlevCoded** [comment]
@dalelantowork If you want to customize the legend, you need to use [options.plugins.legend](https://www.chartjs.org/docs/latest/configuration/legend.html#legend

**Comment by mikayla-bryant** [comment]
I'm having this issue as well, except with changing the color of grid lines. I'm using CRA if that means anything.

**Comment by Hideman85** [comment]
To add my voice to the issue the update to version 3x broke the options. In my case `maintainAspectRatio: false` is not taken in consideration.
Please have a look and fix this :)

**Comment by dyusef** [comment]
try like this :

<Pie data={this.state.dataPie} options={{ responsive: false, maintainAspectRatio: false, **plugins**:{legend: { labels:{usePointStyle: true, color: "white"}, position:'right' }} }} redraw={true} width={250} height={130}/>

you need to add '**plugins**' before object '**legend**' initiate

**Comment by Hideman85** [comment]
@dyusef 
Since when the order of keys in an object is important or do you mean we have to wrap the `options` in a `plugins` object? and where come from the props `plugins`?
Can you link us the piece of doc so we can have a clear understanding?

**Comment by dyusef** [comment]
@Hideman85

https://www.chartjs.org/docs/latest/configuration/legend.html#legend

You can read the documentation url as explained by @YakovlevCoded

**Comment by elrichi31** [comment]
I'm having a problem changing the color of the grid lines
`const options = {
     scales: {
                xAxes: [{
                    gridLines:{
                        display: true,
                        color: "#FF0618"
                    }
                }],
                yAxes: [{
                    gridLines:{
                        display: true,
                        color: "#FF0618"
                    }
                }]
    }
}`

**Comment by Upguard** [comment]
> @dalelantowork Hi! If you want to install an older version of Chart.js, like 2.9.4, you need to use the old version of the react-chartjs-2, like 2.11.1.

This worked for me, until they fix the issue.

**Comment by dangreen** [comment]
Closed due to inactivity
