### ISSUE TITLE
Axes position: 'right' doesn't seem to have any effect

### ISSUE THREAD

**Issue by trydalch** [reactchartjs/react-chartjs-2#664]
I followed the example shown here: https://reactchartjs.github.io/react-chartjs-2/#/multi-axis-line and have looked at closed issues here with examples. 

It appears something has changed and which has broken displaying axes on the right.

**Comment by trydalch** [comment]
Figured it out. Instead of following the example by providing an array of yAxes objects with an id property like this: 

```ts
const options = {
  scales: {
    yAxes: [
      {
        type: 'linear',
        display: true,
        position: 'left',
        id: 'y-axis-1',
      },
      {
        type: 'linear',
        display: true,
        position: 'right',
        id: 'y-axis-2',
        gridLines: {
          drawOnArea: false,
        },
      },
    ],
  },
};
```

Do this:
```ts
const options = {
  scales: {
    'y-axis-1': {
      type: 'linear',
      display: true,
      position: 'left',
      id: 'y-axis-1',
    },
    'y-axis-2': {
      type: 'linear',
      display: true,
      position: 'right',
      gridLines: {
        drawOnArea: false,
      },
    },
  },
};
```

**Comment by westmelon** [comment]
> Figured it out. Instead of following the example by providing an array of yAxes objects with an id property like this:
> 
> ```ts
> const options = {
>   scales: {
>     yAxes: [
>       {
>         type: 'linear',
>         display: true,
>         position: 'left',
>         id: 'y-axis-1',
>       },
>       {
>         type: 'linear',
>         display: true,
>         position: 'right',
>         id: 'y-axis-2',
>         gridLines: {
>           drawOnArea: false,
>         },
>       },
>     ],
>   },
> };
> ```
> 
> Do this:
> 
> ```ts
> const options = {
>   scales: {
>     'y-axis-1': {
>       type: 'linear',
>       display: true,
>       position: 'left',
>       id: 'y-axis-1',
>     },
>     'y-axis-2': {
>       type: 'linear',
>       display: true,
>       position: 'right',
>       gridLines: {
>         drawOnArea: false,
>       },
>     },
>   },
> };
> ```

it still not effect in my project ,i just use like 
```
const data = {
    labels: lables,
    datasets: [
        {
            type: 'line',
            label: 'Dataset 1',
            borderColor: 'rgb(54, 162, 235)',
            borderWidth: 2,
            fill: false,
            data: userCounts,
            yAxisID: 'y-axis-2',
        },
        {
            type: 'bar',
            label: 'Dataset 2',
            backgroundColor: 'rgb(255, 99, 132)',
            data: usables,
            borderColor: 'white',
            borderWidth: 2,
            stack: 'Stack 0',
            yAxisID: 'y-axis-1',
        },
        {
            type: 'bar',
            label: 'Dataset 3',
            backgroundColor: 'rgb(75, 192, 192)',
            data: useds,
            stack: 'Stack 0',
            yAxisID: 'y-axis-1',
        },
    ],
};
```

**Comment by cguldogan** [comment]
using yAxisID in the data set really helped me. I was trying to get rid of the scale on the rightmost right-end side. 

Previously my graphic was like 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/7687931/209677337-3a22bfbb-efad-482d-9a66-28e951046613.png">

Which is now 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/7687931/209677412-5ef83526-14d9-43c8-b129-35eed6d79a71.png">

My Set Up is like 
```
export const options = {
  responsive: true,
  plugins: {
    legend: {
      position: "top"
    },
    title: {
      display: false
    },
  },
  scales: {
    'heat': {
      type: 'linear',
      display: true,
      position: 'right',
      id: 'heat',
      gridLines: {
        display: false,
        drawBorder: false,
      },
      max: 120,
      min:0,
      beginAtZero: true,
    },
    'flow': {
      id: 'flow',
      type: 'linear',
      display: true,
      position: 'left',
      gridLines: {
        display: false,
        drawBorder: false,
      },
      max: 15,
      min:0,
      beginAtZero: true,
    },
  },
};


export const data = {
  labels,
  datasets: [
    {
      label: "Flow",
      data: labels.map(() => faker.datatype.number({ min: 7, max: 15 })),
      backgroundColor: "rgba(255, 99, 132, 0.5)",
      yAxisID: "flow"
    },
    {
      label: "Heat",
      data: labels.map(() => faker.datatype.number({ min: 80, max: 120 })),
      backgroundColor: "rgba(53, 162, 235, 0.5)",
      yAxisID: "heat"
    }
  ]
};
```
