### ISSUE TITLE
Remove border between segments in doughnut charts.

### ISSUE THREAD

**Issue by nparoski** [reactchartjs/react-chartjs-2#666]
I am trying to remove border between each segment in doughnut chart but keep the outside one, I will attach images to explain my self better.

This is what I am trying to achieve, ignore that pale pink background circle.
![image](https://user-images.githubusercontent.com/35550355/117436752-a1ee3a00-af2f-11eb-8f37-4125a8afde70.png)

And this is what currently happens when I apply border
![image](https://user-images.githubusercontent.com/35550355/117436907-cba76100-af2f-11eb-8ac0-7f4a997eefd6.png)

I have tried 
```
 datasets: [
      {
        borderWidth: 2,
        borderColor: '#3f2e75',
        data: dataNumbers,
        backgroundColor: dataColors,
      },
    ],
```

And

```
elements: {
      arc: {
        borderWidth: 2,
        borderColor: '#3f2e75',
      },
    },
```

But they seem to have same effect, what am I missing 🤔

**Comment by Arantiryo** [comment]
Hi @nparoski 👋 

Thank you for providing such a detailed explanation! 

You can achieve this effect by using another series with the following values:
```typescript
datasets: [
    {
      data: [1],
      borderWidth: 0,
      backgroundColor: "rgba(120, 40, 132, 0.8)",
      weight: 0.05
    },
    ...
  ]
```

`weight` property can be used to change thickness of the 'border'. Please feel free to check out this example on [codesandbox](https://codesandbox.io/s/gracious-pascal-xov02l?file=/App.tsx).

Hope that helps : )
