### ISSUE TITLE
Cannot set default font family - defaults.global is undefined

### ISSUE THREAD

**Issue by dancherb** [reactchartjs/react-chartjs-2#667]
```
import { defaults } from 'react-chartjs-2';

defaults.global.defaultFontFamily = 'Montserrat'
```

Gives error:

```
TypeError: Cannot set property 'defaultFontFamily' of undefined
Module../src/screens/X.js
xxx/X.js:13
  12 | 
> 13 | defaults.global.defaultFontFamily = 'Montserrat'
```

Creating a defaults.global object `defaults.global = defaults.global || {}` does not fix it.

`"react-chartjs-2": "^3.0.3"`

Nothing that there's also trouble getting any "callbacks" options to work.

**Comment by daniel-salas-angeles** [comment]
This worked for me: `defaults.font.family ='Noto Sans'`.

**Comment by dangreen** [comment]
Closed due to inactivity
