### ISSUE TITLE
Bar chart ref is null or undefined

### ISSUE THREAD

**Issue by anthonyc-intact** [reactchartjs/react-chartjs-2#668]
I'm using `"react-chartjs-2": "^3.0.3"`.
Testing in Chrome Version 90.0.4430.93 (Official Build) (x86_64) on MacOS Catalina 10.15.7.

My code looks like this :
```ts
import { Bar } from 'react-chartjs-2'

const BarChart = ({...}: BarChartProps): JSX.Element => {
    const chartRef = useRef<any | null>(null)
    // other variables are declared here
    ...

    console.log('CHART REF', chartRef.current)

    return (
        <Bar
            ref={chartRef}
            type="bar"
            height={chartHeight}
            data={data}
            options={options}
        />
    )
}
```

The issue is that `chartRef.current` is either null or undefined, and one way to have a value for it is to resize the window.

**Comment by Quirksmode** [comment]
@anthonyc-intact having the same issue, were you able to solve this?

**Comment by anthonycaron** [comment]
@Quirksmode I had to use a nasty hack to update my component until I have a value for my ref. Not proud of it but it works.

See [this code sandbox](https://codesandbox.io/s/react-chartjs-2-bar-with-groups-and-patterns-forked-qyy0z?file=/src/BarChart.js).

**Comment by Quirksmode** [comment]
@anthonycaron thanks for this, will take a look

**Comment by Quirksmode** [comment]
Sadly this hack wouldn't get through code review for our production app, am hoping there is an official fix or workaround? The issue seems to be related to chartInstance no longer being required, is there another way to check for the ref?

**Comment by jkincheloe33** [comment]
Having this same issue and need access to the ref so that I can change the fillColor of the legend boxes. Any update from the contributors?

**Comment by jkincheloe33** [comment]
This is a pretty clean workaround for now until a fix is made. It's working for me every time:
```
useEffect(() => {
  setLoaded(true)
}, [])

useEffect(() => {
  if (loaded && ref?.current) console.log(ref.current)
}, [loaded])

**Comment by dangreen** [comment]
[Here](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/chart/ref?from-embed=&file=/App.tsx) you can see the correct `ref` usage example.

**Comment by eog-ppirault** [comment]
> [Here](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/chart/ref?from-embed=&file=/App.tsx) you can see the correct `ref` usage example.

This no longer loads

**Comment by anthonycaron** [comment]
@eog-ppirault The important part:
```
export function App() {
  const chartRef = useRef<ChartJS>(null);

  useEffect(() => {
    const chart = chartRef.current;

    triggerTooltip(chart);
  }, []);

  return <Chart ref={chartRef} type='bar' data={data} />;
}
```
Which means you need to wait for your component to be mounted to have access to the chart ref.
