### ISSUE TITLE
./node_modules/react-chartjs-2/dist/index.modern.js - Can't resolve 'chart.js/auto'

### ISSUE THREAD

**Issue by olivblad** [reactchartjs/react-chartjs-2#669]
Hi, i was previously using the @reactchartjs/react-chart.js package and I just switched to 'react-chartjs-2' since it's now deprecated.
Just installed the below:
"chart.js": "^2.9.4",
"react-chartjs-2": "^3.0.3",

Now, the mere fact of importing a chart throws the below compiling error due to the absence of 'chart.js/auto'
`import { Radar } from "react-chartjs-2";`

>>> 
Failed to compile.
./node_modules/react-chartjs-2/dist/index.modern.js
Module not found: Can't resolve 'chart.js/auto'

**Comment by aquashash** [comment]
I was getting the same error and was able to resolve by installing chart.js 3.0.0 version. But now getting below error

Module parse failed: …../chart.js/dist/chart.esm.js Unexpected token (6554:12)
You may need an appropriate loader to handle this file type.
         if (intermediateIndex1 !== startIndex && intermediateIndex1 !== lastIndex) {
           decimated.push({
             ...data[intermediateIndex1],
             x: avgX,
           });

**Comment by andrewmclagan** [comment]
Also seeing this error on `3.0.3`

**Comment by takaoandrew** [comment]
I'm seeing this too. I'm unable to get the package running even after uninstalling the old react-chart package, and am stuck bouncing between 3.0.0 and earlier 2.9 versions, neither work because of the two errors mentioned above.

**Comment by joshverd** [comment]
I believe this is the same issue currently being discussed in the `chart.js` repo: https://github.com/chartjs/Chart.js/issues/9255

**Comment by szalonna** [comment]
But the readme says this lib supports Chart.js v2. So is it or not?
