### ISSUE TITLE
Legend position is not working.

### ISSUE THREAD

**Issue by Emirix** [reactchartjs/react-chartjs-2#670]
I tried everything but i cant set position of the legend. But pie is showing up with the data. Code in below not working for me.
But i got this code from https://www.educative.io/edpresso/how-to-use-chartjs-to-create-charts-in-react works in this site perfetctly....

`import { Pie } from "react-chartjs-2";`

`                <Pie
                  data={this.state}
                  options={{
                    legend: {
                      display: true,
                      position: "right",
                    },
                  }}
                />`

**Comment by Ndifreke** [comment]
I have this same issue on `3.0.3`

**Comment by Emirix** [comment]
> I have this same issue on `3.0.3`

did you fixed?

**Comment by Ndifreke** [comment]
@Emirix

**Comment by Ndifreke** [comment]
@Emirix I upgraded the following the dependencies

`"chart.js": "^3.2.1"`
`"react-chartjs-2": "^3.0.3"`
Then apply plugins in option as

<Chart options={{
	plugins: {
	     legend: {
		position: 'top'
		}
	}
}}/>

**Comment by Emirix** [comment]
> @Emirix I upgraded the following the dependencies
> 
> `"chart.js": "^3.2.1"`
> `"react-chartjs-2": "^3.0.3"`
> Then apply plugins in option as
> 
> ```
> <Chart
>   options={{
>     plugins: {
>       legend: {
>         position: 'top',
>      },
>  },
> }}
> />
> ```

Thanks this is worked
