### ISSUE TITLE
Unable to create a Multi Series Pie Chart

### ISSUE THREAD

**Issue by ausgray10** [reactchartjs/react-chartjs-2#672]
For some reason whenever trying to make a Multi Series Pie chart, every datasets data array is modified to be the last datasets data array.
It's not an error with the code as far as I can tell.  Here is my example. 

```
import { Pie } from "react-chartjs-2";
const data = {
  labels: ["n1", "n2", "n3"],
  datasets: [
    { data: [75, 88, 71], backgroundColor: ["white", "blue", "yellow"] },
    { data: [99, 105, 0], backgroundColor: ["white", "blue", "yellow"]] },
    { data: [0, 157, 0], backgroundColor: ["white", "blue", "yellow"]] },
  ],
};

function App() {
  return (
    <div className="App">
      <Pie type="pie" data={data} />
    </div>
  );
}

export default App;
```

Also here's a link to the [git repository](https://github.com/ausgray10/react-chartjs-2-issue)

[resulting chart](https://github.com/ausgray10/react-chartjs-2-issue/blob/master/public/result.png)
[expected chart](https://github.com/ausgray10/react-chartjs-2-issue/blob/master/public/expected.png)

Through testing I found that the Multi Series Pie chart displays correctly if you remove [this](https://github.com/reactchartjs/react-chartjs-2/blob/master/src/chart.tsx#L158) from the src/chart.tsx file.  So I came to the conclusion that it has to be something in the updateChart() function that is causing the issue.

**Comment by Mottoweb** [comment]
Getting a similar issue here,

I am getting incorrect colors for multi dataset pie chart

<img width="751" alt="Screenshot 2021-05-26 at 9 56 29 AM" src="https://user-images.githubusercontent.com/5813134/119616012-c770b400-be08-11eb-9902-fa2268ea771b.png">

When this is what somewhat expected:

![Uploading Screenshot 2021-05-26 at 9.56.42 AM.png…]()

**Comment by brunohpaiva** [comment]
I managed to reproduce this issue in my app. React chartjs 2 v3.0.3 and Chartjs v3.3.0

**Comment by dangreen** [comment]
@ausgray10 @brunohpaiva Hi. Would you please provide issue reproduction by forking [this](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/pie/default?from-embed=&file=/App.tsx) codesandbox?

**Comment by Arantiryo** [comment]
I’m closing this issue because it has been inactive for a few months and has probably been fixed in a newer version.
