### ISSUE TITLE
Always Show Tooltip : Bubble Chart

### ISSUE THREAD

**Issue by satejrajam30** [reactchartjs/react-chartjs-2#682]
Hi, I am using the latest version of react-chartjs plugin.

I am trying to get all the tooltip to show on the respective bubble/circles on the bubble chart.

I tried all the possible solutions but none of them are working as expected, can someone please help?

Thank you.

Current Code for enabling tooltip:

`options={{
                plugins: {
                  legend: {
                    display: false,
                  },
                  tooltip: {
                    enabled: true,
                    // external: context => {
                    //   // Tooltip Element
                    //   var tooltipEl = document.getElementById(
                    //     'chartjs-tooltip',
                    //   );

                    //   // Create element on first render
                    //   if (!tooltipEl) {
                    //     tooltipEl = document.createElement('div');
                    //     tooltipEl.id = 'chartjs-tooltip';
                    //     tooltipEl.innerHTML = '<table></table>';
                    //     document.body.appendChild(tooltipEl);
                    //   }

                    //   console.log(tooltipEl, ' <<<');

                    //   // Hide if no tooltip
                    //   var tooltipModel = context.tooltip;
                    //   if (tooltipModel.opacity === 0) {
                    //     tooltipEl.style.opacity = 1;
                    //     return;
                    //   }

                    //   // Set caret Position
                    //   tooltipEl.classList.remove(
                    //     'above',
                    //     'below',
                    //     'no-transform',
                    //   );
                    //   if (tooltipModel.yAlign) {
                    //     tooltipEl.classList.add(tooltipModel.yAlign);
                    //   } else {
                    //     tooltipEl.classList.add('no-transform');
                    //   }

                    //   function getBody(bodyItem) {
                    //     return bodyItem.lines;
                    //   }

                    //   // Set Text
                    //   if (tooltipModel.body) {
                    //     var titleLines = tooltipModel.title || [];
                    //     var bodyLines = tooltipModel.body.map(getBody);

                    //     var innerHtml = '<thead>';

                    //     titleLines.forEach(function(title) {
                    //       innerHtml += '<tr><th>' + title + '</th></tr>';
                    //     });
                    //     innerHtml += '</thead><tbody>';

                    //     bodyLines.forEach(function(body, i) {
                    //       var colors = tooltipModel.labelColors[i];
                    //       var style = 'background:' + colors.backgroundColor;
                    //       style += '; border-color:' + colors.borderColor;
                    //       style += '; border-width: 2px';
                    //       var span = '<span style="' + style + '"></span>';
                    //       innerHtml += '<tr><td>' + span + body + '</td></tr>';
                    //     });
                    //     innerHtml += '</tbody>';

                    //     var tableRoot = tooltipEl.querySelector('table');
                    //     tableRoot.innerHTML = innerHtml;
                    //   }

                    //   var position = context.chart.canvas.getBoundingClientRect();
                    //   // var bodyFont = Chart.helpers.toFont(
                    //   //   tooltipModel.options.bodyFont,
                    //   // );

                    //   // Display, position, and set styles for font
                    //   tooltipEl.style.opacity = 1;
                    //   tooltipEl.style.position = 'absolute';
                    //   tooltipEl.style.left =
                    //     position.left +
                    //     window.pageXOffset +
                    //     tooltipModel.caretX +
                    //     'px';
                    //   tooltipEl.style.top =
                    //     position.top +
                    //     window.pageYOffset +
                    //     tooltipModel.caretY +
                    //     'px';
                    //   tooltipEl.style.backgroundColor = 'rgba(0,0,0,0.3)';
                    //   tooltipEl.style.padding =
                    //     tooltipModel.padding +
                    //     'px ' +
                    //     tooltipModel.padding +
                    //     'px';
                    //   tooltipEl.style.pointerEvents = 'none';
                    //   tooltipEl.style.opacity = 1;
                    // },
                  },
                },`

**Comment by Souvikray** [comment]
Did you find any solution to this?

**Comment by Arantiryo** [comment]
Hi @satejrajam30 👋 

Have you tried [chartjs-plugin-datalabels](https://github.com/chartjs/chartjs-plugin-datalabels)? It supports Chart.js 3.0 and looks exactly like what you are looking for.

Here's an [example](https://v2_0_0-beta_1--chartjs-plugin-datalabels.netlify.app/samples/charts/bubble.html) of a bubble chart with tooltips displayed on their respective bubbles.

Hope that helps : ) Cheers!
