### ISSUE TITLE
Getting dependency error while installing chartjs-plugin-datalabels?

### ISSUE THREAD

**Issue by NandhiniMuthuramalingam** [reactchartjs/react-chartjs-2#695]
Hello All,

How to build a doughnut chart only using chart.js and typescript?

I have the following versions
"chart.js": "^3.3.2" and "@types/chart.js": "^2.9.32".

I am able to display the chart. But I want to achieve the below requirements as well.

Display text inside the doughtnut chart
Display DataLabels in each segment
Need to change the color of hidden legend instead of Strike-Through

1. I am getting the dependency error when I try to install npm chartjs-plugin-datalabels. 

**npm ERR! node_modules/chart.js
npm ERR! chart.js@"^3.3.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer chart.js@">= 2.7.0 < 3" from chartjs-plugin-datalabels@1.0.0
npm ERR! node_modules/chartjs-plugin-datalabels**

2. Also getting ,**Type 'ChartOptions' is not assignable to type error**

Any suggestion please to resolve this issue?

Source Code:

`import {Chart,ChartType, ChartOptions, registerables} from 'chart.js';

		var labelValue  =['Green', 'Red', 'Yellow'];
		var dataValue = [83,13,3];
		const chartOptions:  Chart.ChartOptions = {
			legend: {
				display: true, 
				labels: {
					fontColor: '#000000'
				}, 
				position: 'bottom'
			},
			//scale: scaleOptions,
			responsive: true,
			animation: {
				animateScale: true,
				animateRotate: true
			},
			title: {
				display: true,
				text: "Sample Chart"
			},
		};
		var _canvasElement = document.createElement('canvas');
		_canvasElement.id = "myChart";

		this._container.appendChild(_canvasElement);
		
		const chart: Chart = new Chart(_canvasElement, {				
			data: {
				labels: labelValue,
				datasets: [{data: dataValue, backgroundColor:["#F24F21", "#7FBA00", "#00A4EF", "#FFB900", "#006EC4", "#7719AA"]}],
			},			
			type : 'doughnut',
			options : chartOptions 
		});
	`
Thanks!

**Comment by Arantiryo** [comment]
Hi @NandhiniMuthuramalingam 👋 

Is the issue still relevant with the latest versions of `react-chartjs-2` and `Chart.js`?

**Comment by LeeLenaleee** [comment]
Issue does have nothing to do with `react-chartjs-2` or `chart.js`. The datalabels plugin V1 only works with Chart.js V2. To use the datalabels plugin in Chart.js V3 as he is using you need to use at least version 2.0.0 of the datalabels plugin.

This is because there are breaking changes in V3 of Chart.js that are only solved in version 2 of the datalabels plugin

**Comment by Arantiryo** [comment]
Thank you for the explanation @LeeLenaleee !

This is resolved then, closing the issue.
