### ISSUE TITLE
Using a gradient stroke on line chart in React causes line to disappear when you scroll the browser window

### ISSUE THREAD

**Issue by kaizenlabs** [reactchartjs/react-chartjs-2#696]
I have a line chart with multiple data sets on it for multiple lines. They look like this:

---------------
________________

----------------

When I add a gradient stroke to any line, when the chart is first rendered all lines are visible, but soon as a scroll down or up event occurs in the browser window, the lower line always disappears. 

When I remove all the gradient strokes and just use solid colors, the lower line persists on scroll events and does not disappear ever.

Any idea what may be causing this with gradient strokes?

**Comment by dangreen** [comment]
Closed due to inactivity
