### ISSUE TITLE
Version 3.X notes?

### ISSUE THREAD

**Issue by Ltchoc221** [reactchartjs/react-chartjs-2#698]
npmjs has v 3.0.3 has the latest published version and this is reflected in the package.json on the master Branch, however there is no tag or release notes beyond v 2.11.1...Was this version unpublished?  If not, are there notes on any breaking changes?

**Comment by DalderupMaurice** [comment]
There's a project for the 3.0 release but it's been sitting there for ages:
https://github.com/reactchartjs/react-chartjs-2/projects/2

**Comment by dangreen** [comment]
Hi. Current releases are synchronized with tags and notes: https://github.com/reactchartjs/react-chartjs-2/releases
