### ISSUE TITLE
Multi Axis Positioning Not Working

### ISSUE THREAD

**Issue by AndyyTaylor** [reactchartjs/react-chartjs-2#702]
Best seen in the `react-chartjs-2` example: http://reactchartjs.github.io/react-chartjs-2/#/multi-axis-line

Setting the `position: 'right'` of the second y axis doesn't appear to work, leaving both axes on top of each other on the left hand side

Expected behaviour is like the chartjs example: https://www.chartjs.org/docs/latest/samples/line/multi-axis.html

**Comment by dangreen** [comment]
Please see [new website with documentation](https://react-chartjs-2.netlify.app/examples/multiaxis-line-chart)
