### ISSUE TITLE
maxTicksLimit not working in react-chartjs-2

### ISSUE THREAD

**Issue by nvanandsah** [reactchartjs/react-chartjs-2#710]
When I am creating a Line chart using ChartJS I am able to achieve the desired results by
`xAxes: [{
        time: {
            unit: 'date'
        },
        gridLines: {
            display: false,
            drawBorder: false
        },
        ticks: {
            maxTicksLimit: 10
        }
    }]
`
in scales in options. 
But while trying to do the same in react-chartjs-2, all the labels are displayed and maxTicksLimit is not working.

**Comment by dangreen** [comment]
Closed due to inactivity
