### ISSUE TITLE
how to change a doughnat thickness ? please help me

### ISSUE THREAD

**Issue by arunabhverma** [reactchartjs/react-chartjs-2#719]
I want to customize doughnut thickness, i need this type of doughnut.

![Screenshot 2021-08-16 at 3 53 54 PM](https://user-images.githubusercontent.com/59590144/129549623-ba2184a0-c334-4436-8647-02650ebc5d7e.png)

**Comment by adamkss** [comment]
Check out the `cutout` config.
Example:
 ```
<Doughnut
          data={data}
          width={250}
          options={{
            cutout: '80%',
          }}
        />
```

More info here: https://www.chartjs.org/docs/latest/charts/doughnut.html#config-options.

**Comment by arunabhverma** [comment]
Thanks
