### ISSUE TITLE
Data decimation doesn't work.

### ISSUE THREAD

**Issue by hydrognomik** [reactchartjs/react-chartjs-2#721]
Hi there. Please help, how to make decimation work? I have 500+ points. Decimation works only if I pass `redraw` prop (or by toggling `enabled` off and then on in react devtools).

```js
decimation: {
  enabled: true,
  algorithm: 'lttb',
  samples: 12,
  threshold: 12,
},
```

**Comment by dangreen** [comment]
Closed due to inactivity.

**Comment by lifenouveau** [comment]
Still cannot get it to work in v4.0.0

**Comment by aklein24** [comment]
@lifenouveau Do you have a link? I've been trying hard to get decimation to work without success.

**Comment by applesin** [comment]
Still not working...

**Comment by emab** [comment]
A quick fix that seemed to work for me:

```tsx
const Chart = (data) => {
  const chart = useRef(chartRef);
  const options = {
    // ...
  };

  const datasets = data.map((datum) => {
    // do your mapping here
  });

  return (
    <Line
      options={options}
      data={{
        datasets: [...datasets],
      }}
      ref={chartRef}
    />
  );
};
```

The important bit being that you're passing a copy of your datasets to the chart component, rather than something that is contained in the component lifecycle. For me it was enough to use the spread operator.

**Comment by digiage** [comment]
with `react-chartjs-2 v5.2.0` the decimation seems to work, but just for `lttb`. I was not able to make it work with `min-max`

**Comment by hpertaia** [comment]
`react-chartjs-2 v5.2.0` with `chart.js v4.4.1` decimation isn't working. Error: `Сannot destructure property 'x' of 'data[a]' as it is undefined`

**Comment by mhai217** [comment]
any update?

**Comment by takuro-kira** [comment]
In my case.

datasets inner data's x is

Date
Graph can drawing, but decimation enable cause
`Сannot destructure property 'x' of 'data[a]' as it is undefined` error

epoch time milliseconds
It's works

But, some sampling setting value cause same error again.
I think, In development time, because of small data.
I can't figure out.

If it helps someone.
