### ISSUE TITLE
Line chart Background color based on condition

### ISSUE THREAD

**Issue by Mindbowser** [reactchartjs/react-chartjs-2#723]
Hi,

We are looking for dynamic background color based on values, something like this

![image](https://user-images.githubusercontent.com/1574260/130916912-e4260488-ed9c-4044-978b-d92781368b8e.png)

Let me know how we can achieve it.

**Comment by Arantiryo** [comment]
Hi @Mindbowser 👋 

You can achieve this effect by using two different series and the fact that Chart.js doesn't plot null values.

Please check out [this codesandbox](https://codesandbox.io/s/epic-engelbart-fhmnml?file=/App.tsx) with an example.

Also feel free to check out a [similar issue on stackoverflow](https://stackoverflow.com/questions/33793675/chartjs-different-fill-colour-between-data-points) for more information.

Hope that helps : )
