### ISSUE TITLE
How to use adapter and block moment js?

### ISSUE THREAD

**Issue by simpsonphile** [reactchartjs/react-chartjs-2#727]
Hello, I'm trying to block moment.js and use adapter for dayjs,
Is it possible with this wrapper?
thanks in advance

**Comment by Arantiryo** [comment]
> Hello, I'm trying to block moment.js and use adapter for dayjs, Is it possible with this wrapper? thanks in advance

Hi @simpsonphile, it looks like [since v3.0 Chart.js no longer requires moment.js as a dependency](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html). Is this issue still relevant to you?
