### ISSUE TITLE
Individual tooltip getting created for grouped stacked graph

### ISSUE THREAD

**Issue by vinayaksh42** [reactchartjs/react-chartjs-2#745]
https://github.com/reactchartjs/react-chartjs-2/blob/master/example/src/charts/GroupedBar.js

Expected:
![opera_WecJlURj2Q](https://user-images.githubusercontent.com/54861487/136819775-49814e5c-ac5b-45b9-bc69-c907df718034.png)

Outcome of my code:
![opera_iKKBDQcILg](https://user-images.githubusercontent.com/54861487/136819838-271f6bd7-9c35-4dcf-88ef-9f4a6bac2c73.png)

I tried using the exact same code as this one https://github.com/reactchartjs/react-chartjs-2/blob/master/example/src/charts/GroupedBar.js

**Comment by dangreen** [comment]
@vinayaksh42 Hi. Considering [chart.js documentation](https://www.chartjs.org/docs/latest/samples/tooltip/interactions.html), you should set intersection mode to `'index'`:

```
const options = {
  interaction: {
    intersect: false,
    mode: 'index',
  },
};
```

**Comment by chrisl777** [comment]
Note, if using TypeScript, add an `as const`, otherwise you'll get an error, `Type 'string' is not assignable to type '"index" | "x" | "y" | "dataset" | "point" | "nearest" | undefined'.` Like so: 

const options = {
  interaction: {
    intersect: false,
    mode: 'index' as const 
  },
};
