### ISSUE TITLE
Line chart with big data resizes very slow

### ISSUE THREAD

**Issue by nemanja3** [reactchartjs/react-chartjs-2#812]
i am using a line chart graph. I have an array of datasets. Each dataset has in data prop with over 10k points. When i resize the screen it takes a few seconds for the chart to resize. Can someone help me speed up the resize process ? is there a prop that needs to be set or some other method that can be created so the chart would resize faster ?
example of how my chart looks like:
![image](https://user-images.githubusercontent.com/26413661/138856361-2e4295e0-0bdd-4f53-9934-5988d25c4243.png)

Thank you

**Comment by dangreen** [comment]
@nemanja3 Hi. You can use [data decimation](https://www.chartjs.org/docs/latest/samples/advanced/data-decimation.html) to speed up your chart.

**Comment by dangreen** [comment]
@nemanja3 Is this issue still relevant for you?

**Comment by Arantiryo** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please feel free to leave a message and I'll reopen it if you still encounter this issue with version `4.1.0` or above. 

Thank you!
