### ISSUE TITLE
Issue with production build of react.

### ISSUE THREAD

**Issue by adityamulik** [reactchartjs/react-chartjs-2#814]
Please find the attached error in production build of ReactJS app. It works fine in dev server.

<img width="438" alt="Screen Shot 2021-10-26 at 2 46 14 PM" src="https://user-images.githubusercontent.com/10626835/138941979-2a7b73b0-37da-48a3-9168-b7c0fc656f7b.png">

**Comment by TimHuynh0905** [comment]
> Please find the attached error in production build of ReactJS app. It works fine in dev server.
> 
> 
> 
> <img width="438" alt="Screen Shot 2021-10-26 at 2 46 14 PM" src="https://user-images.githubusercontent.com/10626835/138941979-2a7b73b0-37da-48a3-9168-b7c0fc656f7b.png">
> 
> 

Got the same error

**Comment by dangreen** [comment]
@adityamulik It seems like you are passing `undefined` to the `data` prop. `data` prop is required; it must be an object with a `datasets` array.

**Comment by santiacho** [comment]
The same is happening to me with the version (**v3.3.0**).
**Code:**
``` 
  const chartData = {
      labels: ['Green', 'Yellow', 'Red'],
      datasets: [
        {
          data: [50, 25, 25],
          showLine: true,
          label: 'myLabel',
          backgroundColor: [DATA_COLORS.DETRACTOR, DATA_COLORS.PASSIVE, DATA_COLORS.PROMOTER],
          borderWidth: 0,
          rotation: 270,
          circumference: 180,
          hoverOffset: 2,
        },
      ],
  }
 ...
<Doughnut
  data={chartData}
  options={{
    plugins: {
      legend: {
        display: false,
      },
      title: {
        display: false,
      },
      tooltip: { enabled: false },
    },
    responsive: true,
    maintainAspectRatio: false,
  }}
/>
```

**Error:**
![Screenshot 2021-11-05 at 14 13 00](https://user-images.githubusercontent.com/608537/140515788-32bba851-2efc-46b2-8406-9021ebad1a70.png)

**Comment by santiacho** [comment]
I think the problem should be when the chart renders. If the render cycle didn't feed the data on time will crash. The same happened to me and I just fixed that controlling when the data is ready before rendering the Doughnut chart:
```
{chartData && (
    <Doughnut
      data={chartData}
      options={{
        plugins: {
          legend: {
            display: false,
          },
          title: {
            display: false,
          },
          tooltip: { enabled: false },
        },
        responsive: true,
        maintainAspectRatio: false,
      }}
    />
  )}
```
That solved my problem.

**Comment by dangreen** [comment]
@adityamulik @santiacho Hi. Please check out [v4.0.0](https://github.com/reactchartjs/react-chartjs-2/releases/tag/v4.0.0) with the new [`datasetIdKey `](https://react-chartjs-2.netlify.app/docs/working-with-datasets) prop.

**Comment by Dmitriy-Krivetsky** [comment]
@dangreen, hi i have a similar problem.
I tried
```
chart.js.       - 3.6.0 / 3.3.0 / 3.6.0
react-chartjs-2 - 3.3.0 / 3.3.0 / 4.0.0
```

it works on the test server, but I get an error in production. The difference in assembly scripts in
```
production: "build": "NODE_ENV=production webpack --mode production --progress", 
test: "new_test": "cross-env NODE_ENV=test webpack --mode production --progress",
```

![IMAGE 2021-12-01 10:16:27](https://user-images.githubusercontent.com/50628244/144188873-a2a70cdd-787c-44cb-a74b-c1d0aedc13ba.jpg)
![IMAGE 2021-12-01 10:16:38](https://user-images.githubusercontent.com/50628244/144188901-be3bd111-123f-4469-9e45-03ea88cb3b7c.jpg)

**Comment by dangreen** [comment]
@Dmitriy-Krivetsky Hi. This is a different problem. It seems like minification is broken in your configuration.

**Comment by Dmitriy-Krivetsky** [comment]
@dangreen, thank you. Updating babel-eslint from 10.1 to 10.1.0 helped me

**Comment by dangreen** [comment]
@adityamulik Is this issue still relevant for you?

**Comment by adityamulik** [comment]
@dangreen Hi Dan, I seem to not have checked yet. I will cross check and confirm at the earliest. Thanks for your prompt support.

**Comment by adityamulik** [comment]
@dangreen Thanks, the issue is fixed. Updated my package.json file and all seems to be working.
