### ISSUE TITLE
Remove left gap in mixed bar/line chart

### ISSUE THREAD

**Issue by aleemb** [reactchartjs/react-chartjs-2#821]
Is there a good configuration-based workaround to the left-gap in the line seen below?

![image](https://user-images.githubusercontent.com/46616/139436464-fba9e605-b626-4b88-a40b-56c223f90894.png)

**Comment by aleemb** [comment]
@dangreen  https://codesandbox.io/s/lingering-wind-j1x7x?file=/App.tsx

![image](https://user-images.githubusercontent.com/46616/140259849-23b7bcf3-0733-448b-aaa2-bef7b40c0d51.png)

The lines don't go all the way left to the y-axis.

**Comment by dangreen** [comment]
@aleemb Would you please make the same chart as on your image?

**Comment by aleemb** [comment]
@dangreen updated as per the image now

**Comment by dangreen** [comment]
@aleemb 
1) I don't think it is possible with a combination with bar chart. 
2) This question is about chart.js , not about react wrapper, so will be better if you ask this question in [chart.js repo](https://github.com/chartjs/Chart.js/issues), or in stackoverflow.

**Comment by aleemb** [comment]
Thanks @dangreen asked on chartjs repo https://github.com/chartjs/Chart.js/issues/9821
