### ISSUE TITLE
ChartOptions and Typescript

### ISSUE THREAD

**Issue by peterbe** [reactchartjs/react-chartjs-2#822]
Right. Hmm? 
<img width="1335" alt="Screen Shot 2021-10-29 at 9 35 02 AM" src="https://user-images.githubusercontent.com/26739/139444585-9b158671-c813-4094-bd2b-e3259f113896.png">

 What type should I import and use to create my `options` object to make the Typescript woes go away?

I know this sounds more like a question than bug/feature request, but there is very little help in the docs about how to use options in typescript.

**Comment by usahai** [comment]
Hello, would it be possible to get some help with this? I got a similar issue:

```
  const options = {
    responsive: true,
    resizeDelay: 500,
    plugins: {
      title: {
        display: false,
      },
      legend: {
        display: false,
      },
      tooltip: {
        xAlign: 'center',
        yAlign: 'bottom',
        backgroundColor: '#000000',
        displayColors: false,
        bodyAlign: 'center',
        callbacks: {
          beforeBody: (context) => {
            console.log('before body: ', context)
            return 'before body'
          },
          title: (context) => {
            console.log('title context: ', context)
            return 'title'
          },
          beforeLabel: (context) => {
            console.log('before label: ', context)
            return 'before label'
          },
          label: (context) => {
            console.log('label context', context)
            return 'label'
          },
        },
      },
    },
    scales: {
      y: {
        display: false,
      },
    },
  }
```

And am calling the the function:
```
<Bar data={chartData} options={options} />
```

![image](https://user-images.githubusercontent.com/2849176/139584678-db07142e-166f-4112-88cf-851c72606bda.png)
As far as I can tell, I am using all the v3 options.

**Comment by dangreen** [comment]
@usahai Hi. Please use `as const` with align props:

```
xAlign: 'center' as const,
yAlign: 'bottom' as const,
bodyAlign: 'center' as const,
```

**Comment by dangreen** [comment]
Resolved
