### ISSUE TITLE
"Bar" type definition does not allow for multi-type charts

### ISSUE THREAD

**Issue by Sheldonfrith** [reactchartjs/react-chartjs-2#846]
Using typescript.

## Reproduce: 
Simply try out [the official "MultyType" chart example](https://github.com/reactchartjs/react-chartjs-2/blob/master/example/src/charts/MultiType.js
) in typescript.

## Problem:
The "data" object which you have to give to create a Multi-Type chart requires you to specify a "type" other than "bar", ([Click here to see the offending line.](https://github.com/reactchartjs/react-chartjs-2/blob/6a9b2a7527d23e7409c9273ad32eb100122ffb51/example/src/charts/MultiType.js#L10)) but the ``` import {Bar} from 'react-chartjs-2'``` type does not allow for any other value for type besides "bar". 

## Workaround:
Right now I've just set ```//@ts-expect-error``` for the offending line ```type: 'line'```, which solves the problem.

A minor issue, but also a very quick fix so I thought it was worth posting.

**Comment by dangreen** [comment]
@Sheldonfrith Hi. For multitype charts please use `Chart` component. [Example](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/chart/multitype?file=/App.tsx)

**Comment by Sheldonfrith** [comment]
Thank you, in that case the example I referenced above needs to be updated.
