### ISSUE TITLE
Horizontal Stacked Bar Graph

### ISSUE THREAD

**Issue by conye9980** [reactchartjs/react-chartjs-2#853]
Is this possible? For example I have a stacked bar chart like so:
![image](https://user-images.githubusercontent.com/3719375/140924873-74dd45f4-b120-468b-befc-90fa1ecd0dd6.png)

Is it possible to have a Bar Chart stacked Horizontally, something similar to this?
![image](https://user-images.githubusercontent.com/3719375/140924957-7b235889-164a-4b20-a445-a3e9e5a0e1f2.png)
Many thanks!

**Comment by Arantiryo** [comment]
Is [this example](https://codesandbox.io/s/xenodochial-glade-2xivjm?file=/App.tsx) similar to what you are looking for?

This is a [Horizontal Bar Chart](https://react-chartjs-2.js.org/examples/horizontal-bar-chart) that I turned into a stacked bar.
