### ISSUE TITLE
How to remove the tooltip while hovering each of the bubble in the scatter chart?

### ISSUE THREAD

**Issue by APARNAGJ** [reactchartjs/react-chartjs-2#854]
I tried with tooltip: enable property, but it doesn't work. Can you please help me

**Comment by Arantiryo** [comment]
You can disable tooltip by defining options property like this:
```typescript
export const options = {
  plugins: {
    tooltip: {
      enabled: false
    }
  }
};
...
export function App() {
  return <Scatter options={options} data={data} />;
}
```

Here's a [sandbox example](https://codesandbox.io/s/zen-raman-4d42zb?file=/App.tsx:682-759).

More information on configuring tooltips on [the chartjs docs](https://www.chartjs.org/docs/latest/configuration/tooltip.html).
