### ISSUE TITLE
How to return x axes label as html?

### ISSUE THREAD

**Issue by ricardomalagon** [reactchartjs/react-chartjs-2#856]
I want to instead returning a label into the x axes I want to return a custom component.

**Comment by TimMikeladze** [comment]
This solution isn't exactly what you're looking for since it's not HTML, but a way to achieve custom labels is by creating a plugin that draws to the canvas. Specifically one that contains an `afterDraw` function in which you draw your custom content to the canvas. In the example below I'm using it to render images, but in theory this can be adapted to anything, including rendering HTML to the canvas with some SVG hackery. 

Note that you also need to disable ticks and modify the layout to have some additional padding. 


```typescript
<Bar
          plugins={[
            {
              id: `emoji`,
              afterDraw: (chart) => {
                const xAxis = chart.scales.x;
                const yAxis = chart.scales.y;
                xAxis.ticks.forEach((value, index) => {
                  const x = xAxis.getPixelForTick(index);
                  const image = new Image();
                  image.src = getEmojiIconUrl(
                    widgetSubmissionsBarChartQuery.data.widget.settings.theme
                      .iconTheme,
                    value.label as string,
                  );
                  xAxis.ctx.drawImage(
                    image,
                    x - pxToNumber(theme.spacing(2)),
                    yAxis.bottom + pxToNumber(theme.spacing(1)),
                    pxToNumber(theme.spacing(3)),
                    pxToNumber(theme.spacing(3)),
                  );
                });
              },
            },
          ]}
          options={{
            layout: {
              padding: {
                bottom: pxToNumber(theme.spacing(4)),
              },
            },
            scales: {
              x: {
                ticks: {
                  display: false,
                },
              },
            },
            plugins: {
              legend: {
                position: `top`,
                display: false,
              },
            },
            responsive: true,
          }}
          data={data as any}
        />
```

**Comment by dangreen** [comment]
@ricardomalagon Hi.

react-chartjs-2 is just the wrapper around Chart.js, so if you are experiencing an issue with charts rendering, please create a related issue in Chart.js repository.

https://github.com/chartjs/Chart.js/issues

**Comment by LittleCuong** [comment]
When I try to use afterDraw to draw image as the text label. It seems like the function inside the afterDraw runs multiple times even I hover to the chart data. This is annoying and cause reduce significantly my app performance.
