### ISSUE TITLE
TypeScript error when mixing types in data

### ISSUE THREAD

**Issue by peterbe** [reactchartjs/react-chartjs-2#859]
See https://codesandbox.io/s/vibrant-surf-mti3n?file=/src/App.tsx

It's TypeScript. But based on [this wonderful example](https://github.com/reactchartjs/react-chartjs-2/blob/master/example/src/charts/MultiType.js).
As you can see if you open the Codesandbox, **it works**. But you get a TypeScript error, which in my case, means I can run it but not build it because TypeScript doesn't allow the mismatch.

*hovering over the `data=` prop*
<img width="524" alt="Screen Shot 2021-11-11 at 11 59 38 AM" src="https://user-images.githubusercontent.com/26739/141338300-47f2028a-c9ea-418c-8af8-878a3481f01d.png">
 
So, if you use TypeScript, is there a better way to use a `data` when `datasets` contains a `type=....` that is *different* from the name of the imported Component. 
E.g. Is there something like `import { Multi } from 'react-chartjs-2'`?

**Comment by dangreen** [comment]
@peterbe Hi. See https://github.com/reactchartjs/react-chartjs-2/issues/846#issuecomment-962100325

**Comment by peterbe** [comment]
> @peterbe Hi. See [#846 (comment)](https://github.com/reactchartjs/react-chartjs-2/issues/846#issuecomment-962100325)

Awesome! `as const` !
Thanks so much!

**Comment by peterbe** [comment]
@dangreen Pardon me if this is asking a basic TypeScript question, but [your example](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/chart/multitype?file=/App.tsx) has implicit types, simply by typing it all out as 
```js
const data = {
  datasets: [
    ...
  ] 
}
```
What if you get the data from a server and you use `interface` to try to define it. 
I tried to create my own interface called `ChartData`, as seen here: https://codesandbox.io/s/vibrant-surf-mti3n?file=/src/App.tsx
It's basically your example, but no implicit types. 
I get the same error as before. I don't understand the TypeScript error.

**Comment by dangreen** [comment]
@peterbe 

```ts
import { ChartData } from 'chart.js'

let data: ChartData
// Or typed
let data: ChartData<'bar'>
```
