### ISSUE TITLE
Horizontal bar does not work since 3.3.0

### ISSUE THREAD

**Issue by swedieman** [reactchartjs/react-chartjs-2#871]
This example simply does not work when using version 3.3.0 in my dev environment: https://reactchartjs.github.io/react-chartjs-2/#/horizontal-bar

It is always rendered vertically. It seems like `indexAxis: 'y'` does not do anything.

**Comment by dangreen** [comment]
@swedieman Hi. Please see correct example here: https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/bar/horizontal?file=/App.tsx
