### ISSUE TITLE
Mouse hover tooltip erro

### ISSUE THREAD

**Issue by GuilhermeMelati** [reactchartjs/react-chartjs-2#884]
![image](https://user-images.githubusercontent.com/65763317/143225779-5ca10925-e8bd-4a24-be69-ade9eb987661.png)
I'm having an error hovering over the values, the tooltip is showing up incorrectly, in the image above the square would be where the mouse is so the tooltip is displayed, it looks like there is a margin error.
I'm using tailwind and ui stuff.
Thanks.

**Comment by dangreen** [comment]
@GuilhermeMelati Hi. react-chartjs-2 it's just a wrapper around Chart.js. As this issue is about chart rendering, so you should open the issue in [Chart.js repo](https://github.com/chartjs/Chart.js/issues).
