### ISSUE TITLE
Examples not displaying in chrome 96.0.4664.45 (Official Build) (64-bit) (cohort: 96_win_45) on windows 10 21H2

### ISSUE THREAD

**Issue by BEN00262** [reactchartjs/react-chartjs-2#885]
The examples in the official website are not displaying in the stated chrome version. They are working on firefox though

**Comment by dangreen** [comment]
@BEN00262 Hi. Would you please provide more info? Because as I see, all work well.

<img width="2363" alt="Снимок экрана 2021-11-25 в 00 20 46" src="https://user-images.githubusercontent.com/986756/143285828-978cf6fe-2868-457e-a431-1557c0b651df.png">

**Comment by dangreen** [comment]
@BEN00262 Is this issue still relevant for you?
