### ISSUE TITLE
Y axis scaling/alignment incorrect when exported via html2canvas>jsPDF

### ISSUE THREAD

**Issue by Sheldonfrith** [reactchartjs/react-chartjs-2#886]
_I'm not sure if this is an issue more with this package or with html2canvas/jsPDF, but it makes react-chartjs-2 un-useable for me, so I figured it would be relevant to post here in case there is something you guys can do to fix it._ 

### Rendered chart on my page BEFORE conversion with html2canvas:
This is what is should look like.
<img width="370" alt="BeforeHtml2Canvas" src="https://user-images.githubusercontent.com/2314966/143295660-d4d9ccad-c2f2-4dc3-a442-c1d5ca034220.png">

### AFTER conversion with html2canvas:
<img width="360" alt="AfterHtml2Canvas" src="https://user-images.githubusercontent.com/2314966/143295658-7a4576a6-e814-4427-a9b8-e13253b7b726.png">

Incorrect alignment with y axis. Notice how the points are now slightly lower than "1000" and "1500" lines on the y axis. 

My Chart code:
```
<Chart
      // height={100}
      type="line" 
      data={data} 
      options={{
        devicePixelRatio: 6, 
// YES I have tried different devicePixelRatios, they do not seem to have an effect on this issue
// I have to have a devicePixelRatio of at least 3 to avoid resolution drop when converting with html2canvas
      }}
      height={200}
      />
```

**Comment by dangreen** [comment]
@Sheldonfrith Hi. It's not a problem with react-chartjs-2 or chart.js.

**Comment by Sheldonfrith** [comment]
I figured it out, by pure luck. 

The issue was that I was running html2canvas while the initial animation that is the default in react-chartjs-2/chart.js was still running. The default animation has the chart data elements expand outwards from the x-axis so the chart appeared normal, except all the data was lower in magnitude than it should have been. 

All you've got to do to fix this is add this to your chart "options" prop: 
``` 
animation: {
      duration: 0
    }
```
