### ISSUE TITLE
Error: "category" is not a registered scale

### ISSUE THREAD

**Issue by Aditya99111** [reactchartjs/react-chartjs-2#889]
import->
`import { Line } from 'react-chartjs-2';
` 
code where i am using the Line chart
```
<Line
          height={400} 
           width={400}
             data={{
             labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
             datasets: [
                    {
                     label: "label",
                     data: [22, 33, 30, 44, 22, 33],
                     backgroundColor: [
                     'rgba(255, 99, 132, 0.2)',
                     'rgba(54, 162, 235, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(75, 192, 192, 0.2)',
                      'rgba(153, 102, 255, 0.2)',
                      'rgba(255, 159, 64, 0.2)'
                       ],
                       borderColor: [
                       'rgba(255, 99, 132, 1)',
                       'rgba(54, 162, 235, 1)',
                       'rgba(255, 206, 86, 1)',
                       'rgba(75, 192, 192, 1)',
                       'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                                }
                                 ]
                            }}
                       options={{
                     maintainAspectRatio: false
               }}
/>

```

**Comment by dangreen** [comment]
@Aditya99111 Hi. Please see [usage example](https://react-chartjs-2.netlify.app/examples/line-chart) and [migration guide](https://react-chartjs-2.netlify.app/docs/migration-to-v4/#tree-shaking).

**Comment by jSadoski** [comment]
To clarify @dangreen's point, I was trying to follow the [Working with Datasets](https://react-chartjs-2.netlify.app/docs/working-with-datasets) guide and had this same issue. From the [Line Chart usage example](https://react-chartjs-2.netlify.app/examples/line-chart/), I had to include these alongside the `Line`:

```javascript
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";

...

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend);
```

Everything worked for me after adding that!

**Comment by aleeeguevara** [comment]
> To clarify @dangreen's point, I was trying to follow the [Working with Datasets](https://react-chartjs-2.netlify.app/docs/working-with-datasets) guide and had this same issue. From the [Line Chart usage example](https://react-chartjs-2.netlify.app/examples/line-chart/), I had to include these alongside the `Line`:
> 
> ```js
> import {
>   Chart as ChartJS,
>   CategoryScale,
>   LinearScale,
>   PointElement,
>   LineElement,
>   Title,
>   Tooltip,
>   Legend,
> } from "chart.js";
> 
> ...
> 
> ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend);
> ```
> 
> Everything worked for me after adding that!

it actually worked! Thank you!
