### ISSUE TITLE
Node 17 compatibility

### ISSUE THREAD

**Issue by SergioArrighi** [reactchartjs/react-chartjs-2#896]
Hello,
I have been entrusted with a fairly old project and I'm trying to update dependencies as much as possible.
With this library though I have the following error
`npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0" from react-chartjs-3@2.7.7
npm ERR! node_modules/react-chartjs-3
npm ERR!   react-chartjs-3@"^2.7.7" from the root project`

I suspect it is not compatible with Node 17. Am I correct?

Edit: actually I'm using version 3 published on a fork of one of your contributors? Also I've seen mentions in the docs about version 4 but I couln't find it in NPM.

Thanks and best regards

**Comment by dangreen** [comment]
@SergioArrighi Hi. Package named `react-chartjs-3` is not ours. Our package you can find here https://www.npmjs.com/package/react-chartjs-2

**Comment by dangreen** [comment]
@SergioArrighi Is this issue still relevant for you?

**Comment by dangreen** [comment]
Closed due to inactivity
