### ISSUE TITLE
Gradient doesn’t work in backgroundColor property

### ISSUE THREAD

**Issue by Piero87** [reactchartjs/react-chartjs-2#897]
Hello,
I can’t add a background color to my linear chart to get the area under the line filled with a background.

this is an example:

https://codesandbox.io/s/distracted-feynman-tnn96

**Comment by dangreen** [comment]
@Piero87 Hi. As you can see in [this](https://www.chartjs.org/docs/latest/samples/line/styling.html) example, you should use `fill` option in dataset.

https://codesandbox.io/s/magical-lumiere-wvf8e?file=/App.tsx

**Comment by Piero87** [comment]
@dangreen Hi, I have tried it a lot of times but doesn't work, I don't know what is the difference from my code, but this is the same code with **`fill: true`** enable: https://codesandbox.io/s/sad-sun-egxtb and as you can see there is the same problem

**Comment by dangreen** [comment]
@Piero87

```js
import {
  ...
  Filler
} from "chart.js";
...
ChartJS.register(
  ...
  Filler
);
```

**Comment by Piero87** [comment]
@dangreen I was going crazy, thank you very much

**Comment by jchu231** [comment]
Ran into this same issue, thanks for the fix!

I am curious why using but not registering `Filler` doesn't trigger any errors, when missing things like `LineElement` does.
