### ISSUE TITLE
base property in bar chart doesn't work with index

### ISSUE THREAD

**Issue by Lirlisa** [reactchartjs/react-chartjs-2#898]
These are my options and data
```
 const options = {
        indexAxis: 'y',
        barThickness: 6
    }
    const data = {
        labels: ["Caminar solo", "Pararse solo", "Caminar con ayuda", "Gatear", "pararse con ayuda", "Sentarse sin apoyo"],
        datasets: [
            {
                label: 'Dataset1',
                data: [17.5, 17, 13.9, 13.5, 11.5, 9.1],
                borderColor: 'rgb(255, 99, 132)',
                backgroundColor: 'rgba(255, 99, 132, 0.5)',
                base: [8, 7, 6, 5, 4.9, 3.8]
            }
        ]
    };
```

but only the first element in the array given to base is applied.

![imagen](https://user-images.githubusercontent.com/42386589/144778084-91a7ecde-371d-4f40-b54b-31f32c8aea72.png)

The documentation here says that base is indexable https://www.chartjs.org/docs/latest/charts/bar.html

is it a bug or am i missing something?

**Comment by dangreen** [comment]
@Lirlisa Hi. react-chartjs-2 is just the wrapper around Chart.js, so if you are experiencing an issue with charts rendering, please create a related issue in [Chart.js repository](https://github.com/chartjs/Chart.js/issues).
