### ISSUE TITLE
Version 4.0.0 tool tip is not showing for Pie chart

### ISSUE THREAD

**Issue by nikhilb2** [reactchartjs/react-chartjs-2#907]

**Comment by dangreen** [comment]
@nikhilb2 Hi. Would you please provide issue reproduction by forking [this codesandbox](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/bar/horizontal?from-embed) ?

**Comment by nikhilb2** [comment]
https://codesandbox.io/s/bqlr5?file=/index.tsx

**Comment by dangreen** [comment]
@nikhilb2 As you can see in codesandbox, [that i gave you](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/bar/horizontal?from-embed), you should register tooltip component

```js
import {
  ...
  Tooltip
} from 'chart.js';
...
ChartJS.register(
  ...,
  Tooltip
);
```
