### ISSUE TITLE
Fill property not working

### ISSUE THREAD

**Issue by GHarutyunyan** [reactchartjs/react-chartjs-2#908]
I'm installing last version of package, but fill property for line chart not working, but for example in v3 is working

**Comment by dangreen** [comment]
@GHarutyunyan Hi. [Here](https://react-chartjs-2.netlify.app/examples/line-chart) you can see line chart example for v4.

**Comment by GHarutyunyan** [comment]
Yes, I have already check it, but on that version fill property not working.

**Comment by dangreen** [comment]
@GHarutyunyan Please see https://github.com/reactchartjs/react-chartjs-2/issues/897#issuecomment-986593402

**Comment by GHarutyunyan** [comment]
Thanks a lot.

**Comment by GHarutyunyan** [comment]
Please write about it in documentation and create upgrade guide

**Comment by dangreen** [comment]
@GHarutyunyan https://react-chartjs-2.netlify.app/docs/migration-to-v4#tree-shaking

**Comment by GHarutyunyan** [comment]
About `fill` nothing there but thanks :)
