### ISSUE TITLE
Line chart background fill not working

### ISSUE THREAD

**Issue by bulutfatih** [reactchartjs/react-chartjs-2#910]
I just updated `react-chartjs-2 (2.11.2 → 4)` and `chartjs (2.9.4 → 3.6.2)`.
Using line chart with background color, but it doesn't apply the color.

Here is an example I use:
```
  datasets: [
    {
      ...
      backgroundColor: "rgba(255, 0, 0, 0.5)",
      fill: true
    }
```
Sandbox: https://codesandbox.io/s/sharp-haze-v6mrq?file=/App.tsx
Also, `chart.js` documentation for styling: https://www.chartjs.org/docs/3.1.0/samples/line/styling.html

**Comment by dangreen** [comment]
@bulutfatih Hi. Please see https://github.com/reactchartjs/react-chartjs-2/issues/897#issuecomment-986593402 https://github.com/reactchartjs/react-chartjs-2/issues/897#issuecomment-986641055

**Comment by bulutfatih** [comment]
@dangreen Oh, thank you! I think we should update the examples. `Filler` is missing in them.
