### ISSUE TITLE
Specifying 'fill: true' should create an area chart, but does not

### ISSUE THREAD

**Issue by reedshea** [reactchartjs/react-chartjs-2#913]
I'm new to using `chart.js` and `react-chartjs-2`, so I'd be grateful for some guidance if I'm missing something! I believe that creating an area chart is supposed to entail creating a line chart with a `fill: true` (or `fill: 'start'`, etc.). 

The example linked below works as a combination area / line chart if `react-chartjs-2 v3.3.0` is selected, but only a line chart if `v4.0.0` is specified.

[![Edit serene-pine-nb94j](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serene-pine-nb94j?fontsize=14&hidenavigation=1&theme=dark)

Example, in case the link above doesn't work:

```
export const options = {
  responsive: true,
  plugins: {
    legend: {
      position: 'top' as const,
    },
    title: {
      display: true,
      text: 'Chart.js Line Chart',
    },
  },
};

const labels = ['January', 'February', 'March', 'April', 'May', 'June', 'July'];

export const data = {
  labels,
  datasets: [
    {
      label: 'Dataset 1',
      data: labels.map(() => faker.datatype.number({ min: -1000, max: 1000 })),
      fill: true,
      borderColor: 'rgb(255, 99, 132)',
      backgroundColor: 'rgba(255, 99, 132, 0.5)',
    },
    {
      label: 'Dataset 2',
      data: labels.map(() => faker.datatype.number({ min: -1000, max: 1000 })),
      borderColor: 'rgb(53, 162, 235)',
      backgroundColor: 'rgba(53, 162, 235, 0.5)',
    },
  ],
};

export function App() {
  return <Line options={options} data={data} />;
}
```

**Comment by dangreen** [comment]
@reedshea Hi. Please see https://github.com/reactchartjs/react-chartjs-2/issues/897#issuecomment-986593402 https://github.com/reactchartjs/react-chartjs-2/issues/897#issuecomment-986641055 https://react-chartjs-2.netlify.app/docs/migration-to-v4#tree-shaking

**Comment by reedshea** [comment]
Oh, that's great - thank you so much! Importing & registering `Filler` was the missing piece for me.

**Comment by LordTricto** [comment]
@reedshea what package did you import filter from ?
