### ISSUE TITLE
Not able to show labels on bar chart in reactjs

### ISSUE THREAD

**Issue by Rushikeshkalhapure** [reactchartjs/react-chartjs-2#960]
### 🦄

- [ ] Would you like to work on a fix?

### Current and expected behavior

current : not able to show labels on bar chart

expected : label should be appear on bar chart

### Reproduction

  plugins: {                                         legend: {                                             display: false,                                         },                                         datalabels: {                                             display: true,                                             color: 'white',                                             opacity:1,                                         },                                         tooltip:{                                             enabled:false                                         }                                     },

### chart.js version

3.7.0

### react-chartjs-2 version

4.0.0

**Comment by dangreen** [comment]
@Rushikeshkalhapure Hi. Please provide issue reproduction. You can fork [this codesandbox](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/bar/vertical?file=/App.tsx) to reproduce.

**Comment by Rushikeshkalhapure** [comment]
@dangreen  Thanks for the response.
Issue is resolved now

**Comment by RudrikaJnext** [comment]
@Rushikeshkalhapure , how did you resolved this? can you share any reference! I need to display labels with the data count on chart! Thanks in advance!
