### ISSUE TITLE
Want to show datasetlabels at the middle  and data values at the top 

### ISSUE THREAD

**Issue by Rushikeshkalhapure** [reactchartjs/react-chartjs-2#962]
### 🦄

- [ ] Would you like to work on a fix?

### Current and expected behavior

current : not able to show both datasetLabel and datavalue at a time.

expected: both datasetlabel and values should be displayed on the bar chart

### Reproduction

datalabels: { 						color: "white", 						align: "end", 						anchor: "start", 						offset: 0, 						formatter: (val, ctx) => { 							return (ctx.chart.data.labels[ctx.dataIndex]); 						}, 						font: { size: "10" }, 					}

### chart.js version

v3.7.0

### react-chartjs-2 version

v4.0.0

**Comment by dangreen** [comment]
@Rushikeshkalhapure Hi. react-chartjs-2 is just the wrapper around Chart.js, so if you are experiencing an issue with charts rendering, please create a related issue in [Chart.js repository](https://github.com/chartjs/Chart.js/issues).

**Comment by Rushikeshkalhapure** [comment]
ok Thanks @dangreen
