### ISSUE TITLE
 [Bug]: Chart is getting re-rendered while setting state in getElementAtEvent and onZoomComplete functions

### ISSUE THREAD

**Issue by praseetha-nair** [reactchartjs/react-chartjs-2#966]
### 🦄

- [ ] Would you like to work on a fix?

### Current and expected behavior

I am using "react-chartjs-2": "^2.9.4" and "chart.js": "^2.9.4" to render a scatter plot .  I need the following : 
1. Keep adding data of specific points on the chart when clicked to a grid and 
2. I also want to zoom a specific area on the chart and keep the chart in the zoomed position and pick the data from the zoomed area and be able to add to a grid. 

But whenever I try to set the selected data to a state variable the chart re-renders.  

Please refer the following code to get value and setting it to a state variable.
```

<Scatter
                    data={data}
                    options={options}
                    plugins={[borderPlugin]}
                    getElementAtEvent={dataset => {
                      if (dataset.length > 0) {
                        var dataIndex = dataset[0]._datasetIndex;
                        var selectedLabel = data.datasets[dataIndex].label;
                        var valueIndex = dataset[0]._index;
                        var selectedData =
                          data.datasets[dataIndex].data[valueIndex];
                        setSelectedELR(selectedData.y);
                        setSelectedHours(selectedData.x);
                       }
                    }}
                  />

```
Could you please let me know what could be done to fix this issue.

### Reproduction

https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/chart/ref

### chart.js version

v2.9.4

### react-chartjs-2 version

v2.9.4

**Comment by dangreen** [comment]
@praseetha-nair Hi. Please provide issue reproduction. You can fork [this codesandbox](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/scatter/default?file=/App.tsx) to reproduce.

**Comment by dangreen** [comment]
Closed due to inactivity
