### ISSUE TITLE
[Bug]: Broken link in documentation

### ISSUE THREAD

**Issue by alaroche** [reactchartjs/react-chartjs-2#973]
### 🦄

- [ ] Would you like to work on a fix?

### Current and expected behavior

Subject: https://github.com/reactchartjs/react-chartjs-2/blob/master/website/docs/components/pie.mdx#props

Current behavior: Clicking on link reading "See full usage examples." leads to https://github.com/reactchartjs/react-chartjs-2/blob/master/tags/pie-chart which leads to "Page not found."

Expected behavior: Link navigates to page showing full usage examples of the Pie component.

Thank you for your time.

### Reproduction

https://github.com/reactchartjs/react-chartjs-2/blob/master/tags/pie-chart

### chart.js version

latest

### react-chartjs-2 version

latest

**Comment by dangreen** [comment]
@alaroche Hi. You should visit https://react-chartjs-2.netlify.app/tags/pie-chart
